---
permalink: sg6000/shutting-down-sg6000-cn-controller.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, power off, turn off, shut off, shutdown, shut down, sg6000-cn, controller
summary: 'Shut down the SG6000-CN controller to perform hardware maintenance.'
---
= Restore BMC
:icons: font
:imagesdir: ../media/

[.lead]
Shut xxxxxxxxxxxxxxxxxxxdown the SG6000-CN controller to perform hardware maintenance.

.What you'll need

* xxxxxxxxxYou have physically located the SG6000-CN controller requiring maintenance in the data center.
+
link:locating-controller-in-data-center.html[Locate controller in data center]


.About this task

To prevxxxxxxxxxxxxxxxxxxxxxxxds of service disruption are acceptable. See the information about link:../monitor/monitoring-node-connection-states.html[monitoring node connection states].

IMPORTANT: If you haxxxxxxxxxxxxxxxxxxxects during this procedure. +
See information about managing objects with information lifecycle management.

.Steps

_Appliance_IP_

The following commands should be performed as user root from an ssh session to the appliance hosting the BMC that needs to be configured.

 .. Log in to the grid node using PuTTY or another ssh client:
  ... Enter the following command: `ssh admin@_grid_node_IP_`
  ... Enter the password listed in the `Passwords.txt` file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.

. Display the current settings of the appliance and record them.
+
Enter: `*ipmitool lan print*`


As needed, set the IP address (either static or obtain via DHCP), netmask, and gateway




. To restore the BMC configuration to use a static IP, netmask, and gateway, enter the following commands:

ipmitool lan set 1 ipaddr _Appliance_IP_

ipmitool lan set 1 netmask _Netmask_IP_

ipmitool lan set 1 defgw ipaddr _Default gateway_


. To restore the BMC configuration to use DHCP to obtain an IP, netmask, and gateway, enter the following command: 

ipmitool lan set 1 ipsrc dhcp



Note: after restoring BMC network connectivity, connect to the BMC UI to audit and restore any additional custom BMC configuration you might have applied. For example, you should confirm the settings for SNMP trap destinations and email notifications.

See xxxxxxx. 




