---
sidebar: sidebar
permalink: bluexp-integration.html
keywords: netapp, storagegrid, grid manager, bluexp, hybrid, cloud, dashboard, multicloud
summary: Beginning with StorageGRID 11.7, Grid Manager is integrated with BlueXP. With BlueXP, you can manage your hybrid multicloud infrastructure from a single control plane while retaining the familiar Grid Manager dashboard.
---
= Grid Manager integration with BlueXP
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with StorageGRID 11.7, Grid Manager is integrated with BlueXP. With BlueXP, you can manage your hybrid multicloud infrastructure from a single control plane while retaining the familiar Grid Manager dashboard.

== Integration overview

When you access Grid Manager on a StorageGRID system running StorageGRID 11.7 or later with connectivity to the BlueXP service, you'll be prompted to manage the grid directly from BlueXP. From BlueXP, you'll have access to the Grid Manager interface that you're used to, plus access to BlueXP functionality.

BlueXP enables you to create and administer object storage, use NetApp's data services (for example, Cloud Backup), and control many on-premise appliances and other storage devices.

== Manage your StorageGRID system from BlueXP

When you're ready to manage your StorageGRID system from BlueXP, you can follow the link that appears when you try to access Grid Manager, or you can go directly to BlueXP. Going directly to BlueXP provides an advantage, if you'd like to use BlueXP's data services to back up data, scan and categorize your data, and more.

=== What's not supported
With the current implementation, the following Grid Manager features and operations aren't supported from BlueXP:

* Grafana charts don't work in the current implementation.

* The metrics available from the Nodes page and the Traffic Classifications pages don't work. 

* Certain legacy pages, such as the Alarms and Grid Topology pages, don't work.

* The following operations aren't supported from BlueXP, so the following Grid Manager pages are hidden from BlueXP. If you need to perform these operations, sign directly in to the Grid Manager.

** StorageGRID software upgrade page. You can't upgrade StorageGRID software or apply a hotfix from BlueXP.
** Single sign-on (SSO) page.
** Settings page to set the auto-logout timer
** Link to the Swagger documentation for the Grid Management API
** Log page
** Recovery Package page
** Sign out option

* The Tenant Manager user interface is not supported. While you can create new tenant accounts from BlueXP, tenant users can't sign into their accounts from BlueXP.

=== Use the link from Grid Manager

When you connect to the Grid Manager interface from your web browser, you are prompted to manage your StorageGRID system with Grid Manager in BlueXP or to use Grid Manager directly. To use Grid Manager in BlueXP, perform the following steps:

.Steps

. Open a web browser and enter the IP address of the Admin Node.
+
If the node has connectivity to BlueXP, a login prompt displays.

. Select *Continue to BlueXP* to follow the link to BlueXP.

. On the BlueXP login page, select *Log in with your NetApp Support Site Credentials* and enter your credentials.
+
If you've already used BlueXP and have a login using an email and password, then you'll need to continue using that login option instead.
+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html[Learn more about logging in to BlueXP^].

. If you're prompted, enter a name for your new BlueXP account.
+
In most cases, BlueXP automatically creates an account for you based on data from your cluster.

. Enter the sign-in credentials for the user account in StorageGRID.

.Result

Grid Manager displays and you can now manage your grid from BlueXP.

=== Discover your grid directly from BlueXP

BlueXP provides two ways to discover and manage your grid:

* Direct discovery for management through Grid Manager
+
This is the same discovery option described in the previous section with which you follow the redirect.

* Discovery through a Connector 
+
The Connector is software installed in your environment which allows you to access management functions through Grid Manager and also access BlueXP cloud services that provide features such as data replication, backup and recovery, data classification, data tiering, and more.

Go to the https://docs.netapp.com/us-en/cloud-manager-family/index.html[BlueXP documentation^] to learn more about these discovery and management options.

== Learn more about BlueXP

* https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html[BlueXP overview^]

* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html[Manage your NetApp AFF and FAS systems through BlueXP^]
