---
sidebar: sidebar
permalink: bluexp-integration.html
keywords: netapp, storagegrid, grid manager, bluexp, hybrid, cloud, dashboard, multicloud
summary: Grid Manager is now integrated with BlueXP. Accessing your StorageGRID system from BlueXP allows you to use the familiar Grid Manager interface while you are viewing the data across your hybrid multicloud. 
---
= Grid Manager integration with BlueXP
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Grid Manager is now integrated with BlueXP. Accessing your StorageGRID system from BlueXP allows you to use the familiar Grid Manager interface while you are viewing the data across your hybrid multicloud. See https://docs.netapp.com/us-en/cloud-manager-storagegrid/index.html[BlueXP documentation for StorageGRID^] for details and instructions.


With the StorageGRID 11.7 implementation, almost all Grid Manager features and operations are supported from BlueXP. 

The table shows which Grid Manager operations are not available from BlueXP. If a Grid Manager operation is not available, the link to the operation is hidden when you access Grid Manager from BlueXP. If you need to perform these operations, sign in to the Grid Manager directly.

[cols="1a,2a" options=header] 
|===
| Grid Manager menu
| Operations not available from BlueXP

| User
| * Sign out link
* API documentation link

| Alerts
| _All alert options are available from BlueXP._

| Nodes
| You can't access SANtricity System Manager from the Nodes > SANtricity System Manager tab. 

| Tenants
| You can't sign in to a tenant account from the Create a tenant wizard or from the Tenants page.

*Note*: BlueXP doesn't currently support the Tenant Manager. Although you can create new tenant accounts from BlueXP, tenant users can't sign into their accounts from BlueXP.


| ILM
| Storage grades link

| Configuration
| * Traffic classification > Metrics
* Security settings > Browser inactivity timeout
* Single sign-on 

| Maintenance

| * Recovery Package
* Software update

| Support

| 
* Diagnostics
 * Grid topology
 * Logs
* Metrics, including all links to Prometheus metrics and Grafana dashboards from other places in the UI.
* All options for legacy alarms
* Link cost
* NMS entities

|===

