settings:
  name: "StorageGRID 11.7"
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
  # versions:
    # Version selector
    # Current repo stanza comes first
    # - name: StorageGRID
    #  url: /storagegrid-117
    #  version-number: "11.7"
    # Additional releases newest to oldest
    # Release in GitHub (typical)
    # - name: StorageGRID
    #  url: /storagegrid-116
    #  version-number: "11.6"
    # Release in GitHub (typical)
    # - name: StorageGRID
    #  url: /storagegrid-115
    #  version-number: "11.5"
    # Release not in GitHub
    # - name: StorageGRID
    #  url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63374&language=en-US
    #  version-number: "11.4"
    # Release not in GitHub
    # - name: StorageGRID
    #  url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023&archive=true
    #  version-number: "11.3"
sidebar:
  entries:
    - title: StorageGRID 11.7 Docs
      url: /index.html
    - title: Release notes
      url: "/release-notes/index.html"
    - title: Get started
      entries:
      - section: primer
      - section: network
      - title: Quick start for StorageGRID
        url: /primer/quick-start.html      
    - title: Install and upgrade
      entries:
      - section: installconfig
      - section: rhel
      - section: ubuntu
      - section: vmware
      - section: upgrade
    - title: Configure and manage
      entries:
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID
      entries:
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and troubleshoot
      entries:
      - section: monitor
      - section: troubleshoot
      - section: audit
    - title: Maintain
      entries:
      - section: expand
      - section: maintain
      - section: commonhardware
      - section: sg6100
      - section: sg6000
      - section: sg5700
      - section: sg5600
      - section: sg100-1000
    - title: Enable StorageGRID
      url: /storagegrid-enable.html
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
      - title: Release notes
        url: /release-notes/index.html
      - title: What's new
        url: /upgrade/whats-new.html
      - title: Learn about StorageGRID
        url: /primer/index.html
      - title: Networking guidelines
        url: /network/index.html
      - title: StorageGRID quick start
        url: /primer/quick-start.html
    - title: Install & maintain hardware
      links:
      - title: Install and deploy appliances
        url: /installconfig/index.html
      - title: Maintain appliances
        url: /maintain/index.html
    - title: Install & upgrade software
      links:
      - title: Install Red Hat Enterprise Linux or CentOS
        url: /rhel/index.html
      - title: Install Ubuntu or Debian
        url: /ubuntu/index.html
      - title: Install VMware
        url: /vmware/index.html
      - title: Upgrade software
        url: /upgrade/index.html
    - title: Configure the grid
      links:
      - title: Administer StorageGRID
        url: /admin/index.html
      - title: Manage objects with ILM
        url: /ilm/index.html
      - title: System hardening
        url: /harden/index.html
      - title: Configure StorageGRID for FabricPool
        url: /fabricpool/index.html
    - title: Manage objects
      links:
      - title: Use a tenant account
        url: /tenant/index.html
      - title: Use S3 REST API
        url: /s3/index.html
      - title: Use Swift REST API (deprecated)
        url: /swift/index.html
    - title: Monitor & maintain
      links:
      - title: Monitor
        url: /monitor/index.html
      - title: Troubleshoot
        url: /troubleshoot/index.html
      - title: Review audit logs
        url: /audit/index.html
      - title: Expand your grid
        url: /expand/index.html
      - title: Recover & maintain
        url: /maintain/index.html
    - title: Demos & tutorials
      links:
      - title: Learn how to enable StorageGRID
        url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
      - title: StorageGRID video library
        url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
      - title: NetApp learning services
        url: https://www.netapp.com/support-and-training/netapp-university/
    - title: More resources
      links:
      - title: StorageGRID support page
        url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
      - title: NetApp Interoperability Matrix Tool (IMT)
        url: https://imt.netapp.com/matrix/#welcome
      - title: StorageGRID knowledge base
        url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
      - title: NetApp blog
        url: https://netapp.com/blog/
      - title: NetApp community
        url: https://community.netapp.com/
    - title: Earlier versions
      links:
      - title: StorageGRID 11.6 documentation
        url:  https://docs.netapp.com/us-en/storagegrid-116/index.html
      - title: StorageGRID 11.5 documentation
        url: https://docs.netapp.com/us-en/storagegrid-115/index.html
      - title: StorageGRID 11.4 documentation
        url: https://docs.netapp.com/sgws-114/index.jsp
      - title: StorageGRID 11.3 documentation
        url: https://docs.netapp.com/sgws-113/index.jsp
