---
permalink: upgrade/changes-to-grid-management-api.html
sidebar: sidebar
keywords: grid management api, api, api version, swagger, rest api
summary: 'StorageGRID 11.7 uses version 3 of the Grid Management API. Version 3 deprecates version 2; however, version 1 and version 2 are still supported.'
---
= Changes to the Grid Management API
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 11.7 uses version 3 of the Grid Management API. Version 3 deprecates version 2; however, version 1 and version 2 are still supported.

IMPORTANT: You can continue to use version 1 and version 2 of the management API with StorageGRID 11.7; however, support for these versions of the API will be removed in a future release of StorageGRID. After upgrading to StorageGRID 11.7, the deprecated v1 and v2 APIs can be deactivated using the `PUT /grid/config/management` API.

To learn more, go to xref:../admin/using-grid-management-api.adoc[Use the Grid Management API].

== New private cipher API

You can now configure ciphers using the Grid Management API.

Using the private cipher API, you can:

* Remove ciphers from client-facing interfaces.
* Remove SSH algorithms from ECDSA and RSA.
* Re-enable ciphers and algorithms if you have enabled CHACHA or the NIST “transitional” list.
* Re-enable any cipher/algorithm that is available by default.