---
permalink: upgrade/changes-to-tenant-management-api.html
sidebar: sidebar
keywords: tenant management api, api, api version, swagger, rest api
summary: 'StorageGRID 11.7 uses version 3 of the Tenant Management API. Version 3 deprecates version 2; however, version 1 and version 2 are still supported.'
---
= Changes to the Tenant Management API
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 11.7 uses version 3 of the Tenant Management API. Version 3 deprecates version 2; however, version 1 and version 2 are still supported.

IMPORTANT: You can continue to use version 1 and version 2 of the management API with StorageGRID 11.7; however, support for these versions of the API will be removed in a future release of StorageGRID. After upgrading to StorageGRID 11.7, the deprecated v1 and v2 APIs can be deactivated using the `PUT /grid/config/management` API.

== New endpoints for grid federation
You can use the *grid-federation-connections* API endpoints to list grid federation connections for the current tenant and to clear the last cross-grid replication error for the current tenant and selected grid federation connection.

To learn more, go to link:../tenant/understanding-tenant-management-api.html[Understand the Tenant Management API].
