---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html
sidebar: sidebar
keywords: upgrade, firmware, appliance, alert
summary: 'You must understand how your StorageGRID system will be affected during the upgrade.'
---
= How your system is affected during the upgrade
:icons: font
:imagesdir: ../media/

[.lead]
You must understand how your StorageGRID system will be affected during the upgrade.

== StorageGRID upgrades are non-disruptive

The StorageGRID system can ingest and retrieve data from client applications throughout the upgrade process. Grid nodes are brought down one at a time during the upgrade, so there is not a time when all grid nodes are unavailable.

To allow for continued availability, you must ensure that objects are stored redundantly using the appropriate ILM policies. You must also ensure that all external S3 or Swift clients are configured to send requests to one of the following:

* A StorageGRID endpoint configured as a high availability (HA) group
* A high availability third-party load balancer
* Multiple Gateway Nodes for each client
* Multiple Storage Nodes for each client

== Appliance firmware is upgraded

During the StorageGRID 11.7 upgrade:

* All StorageGRID appliance nodes are automatically upgraded to StorageGRID Appliance Installer firmware *version tbd*.
* SG6060 and SGF6024 appliances are automatically upgraded to BIOS firmware *version tbd* and BMC firmware *version BMC tbd*.
* SG100 and SG1000 appliances are automatically upgraded to BIOS firmware *version tbd* and BMC firmware *version tbd*.

== Alerts might be triggered

Alerts might be triggered when services start and stop and when the StorageGRID system is operating as a mixed-version environment (some grid nodes running an earlier version, while others have been upgraded to a later version). Other alerts might be triggered after the upgrade completes. 

For example, you might see the *Unable to communicate with node* alert when services are stopped, or you might see the *Cassandra communication error* alert when some nodes have been upgraded to StorageGRID 11.7 but other nodes are still running StorageGRID 11.6. In general, these alerts will clear when the upgrade completes.

The *ILM placement unachievable* alert might be triggered when Storage Nodes are stopped during the upgrade to StorageGRID 11.7. This alert might persist for 1 day after the upgrade completes.

After the upgrade completes, you can review any upgrade-related alerts by selecting *Recently resolved alerts* or *Current alerts* from the Grid Manager dashboard.

== Many SNMP notifications are generated

Be aware that a large number of SNMP notifications might be generated when grid nodes are stopped and restarted during the upgrade. To avoid excessive notifications, unselect the *Enable SNMP Agent Notifications* check box (*CONFIGURATION* > *Monitoring* > *SNMP agent*) to disable SNMP notifications before you start the upgrade. Then, re-enable notifications after the upgrade is complete.

== Configuration changes are restricted

NOTE: The list of restricted configuration changes can change from release to release. When upgrading to another StorageGRID release, refer to the list in the appropriate upgrade instructions.

Until the *Enable New Feature* task completes:

* Do not make any grid configuration changes.
* Do not change the audit level configuration or configure an external syslog server.
* Do not enable or disable any new features. For example, do not attempt to create a grid federation connection until both StorageGRID systems have been updated to StorageGRID 11.7.
* Do not update the ILM configuration. Otherwise, you might experience inconsistent and unexpected ILM behavior.
* Do not apply a hotfix or recover a grid node.
+
NOTE: Contact technical support if you need to recover a node during upgrade.

* You cannot manage HA groups, VLAN interfaces, or load balancer endpoints while you are upgrading to StorageGRID 11.7.

Until the *Final Upgrade Steps* task completes:

* Do not perform an expansion procedure.
* Do not perform a decommission procedure.

== You cannot view bucket details or manage buckets from the Tenant Manager

During the upgrade to StorageGRID 11.7 (that is, while the system is operating as a mixed-version environment), you cannot view bucket details or manage buckets using the Tenant Manager. One of the following errors appears on the Buckets page in Tenant Manager:

* You cannot use this API while you are upgrading to 11.7.

* You cannot view bucket versioning details in the Tenant Manager while you are upgrading to 11.7.

This error will resolve after the upgrade to 11.7 is complete. 

.Workaround

While the 11.7 upgrade is in progress, use the following tools to view bucket details or manage buckets, instead of using the Tenant Manager:

*	To perform standard S3 operations on a bucket, use either the link:../s3/operations-on-buckets.html[S3 REST API] or the link:../tenant/understanding-tenant-management-api.html[Tenant Management API].
* To perform StorageGRID custom operations on a bucket (for example, viewing and modifying the bucket consistency level, enabling or disabling last access time updates, or configuring search integration), use the Tenant Management API.

== TLS ciphers or SSH configurations might change
If TLS ciphers or SSH configurations have been manually changed or are inconsistent across nodes, all nodes will be overwritten to be either Legacy Compatibility or Modern Compatibility upon upgrade. If you used `fips-ciphers.sh` in StorageGRID 11.6, the Common Criteria policy is applied to all nodes. Otherwise, the Legacy Compatibility policy is applied. If you require Common Criteria validated configurations, you must use the Common Criteria policy or the FIPS strict policy. If you did not use `fips-ciphers.sh`, you should use the new Modern Compatibility setting after upgrade completes. To configure ciphers, go to *CONFIGURATION* > *Security* > *Security settings* and select *TLS and SSH policies*.

== CLB ports might be converted to load balancer endpoints
The legacy Connection Load Balancer (CLB) service has been removed in StorageGRID 11.7. If CLB configuration is detected during upgrade prechecks, the *Legacy CLB load balancer activity detected* alert will be triggered. If custom certificates were set up for the S3 or Swift API in the existing StorageGRID version, the CLB ports 8082, 8083, 8084, and 8085 will be converted to load balancer endpoints during upgrade to StorageGRID 11.7.

See also link:../admin/managing-load-balancing.html[Considerations for load balancing].