---
permalink: upgrade/impact-of-upgrade-on-groups-and-user-accounts.html
sidebar: sidebar
keywords: upgrade, permissions
summary: 'You must understand the impact of the StorageGRID upgrade, so that you can update groups and user accounts appropriately after the upgrade is complete.'
---
= Impact of an upgrade on groups and user accounts
:icons: font
:imagesdir: ../media/

[.lead]
You must understand the impact of the StorageGRID upgrade, so that you can update groups and user accounts appropriately after the upgrade is complete.


== Changes to group permissions and options

After upgrading to StorageGRID 11.7, optionally assign the following updated or new permissions to admin groups or tenant user groups.

[cols="1a,2a" options="header"]
|===
| Permission | Description

| Tenant Manager > Manage objects with S3 Console
| When combined with the Manage all buckets permission, allows users to access the link:../tenant/use-s3-console.html[Experimental S3 Console] and use it to manage objects.

Users who do not have both of these permissions do not see the *Experimental S3 Console* link on the Buckets page.

|===

See link:../tenant/tenant-management-permissions.html[Tenant management permissions].
