---
permalink: upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html
sidebar: sidebar
keywords: upgrade, linux, rpm, deb,
summary: 'If any StorageGRID nodes are deployed on Linux hosts, you must install an additional RPM or DEB package on each of these hosts before you start the upgrade.'
---
= Linux: Download and install the RPM or DEB package on all hosts
:icons: font
:imagesdir: ../media/

[.lead]
If any StorageGRID nodes are deployed on Linux hosts, you must download and install an additional RPM or DEB package on each of these hosts before you start the upgrade.

.Steps
. Go to https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID^].

. Select the button for downloading the latest release, or select another version from the drop-down menu and select *Go*.
+
StorageGRID software versions have this format: 11._x.y_. StorageGRID hotfixes have this format: 11._x.y.z_.

. Sign in with the username and password for your NetApp account.
. If a Caution/MustRead statement appears, read it and select the check box.
+
This statement appears if there is a required hotfix for the release.

. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
+
The downloads page for the version you selected appears. The page contains three columns:

 ** Install StorageGRID
 ** Upgrade StorageGRID
 ** Support files for StorageGRID Appliances

. In the *Upgrade StorageGRID* column, select and download the RPM or DEB archive in either `.tgz` or `.zip` format. Select the `.zip` file if you are running Windows on the service laptop.

* Red Hat Enterprise Linux or CentOS +
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` +
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz`

* Ubuntu or Debian +
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` +
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz`
+
NOTE: No additional files are required for the SG100 or SG1000.
 
. Extract the RPM or DEB packages from the installation file.
. Install the RPM or DEB packages on all Linux hosts.
+
See the steps for installing StorageGRID host services in the installation instructions for your Linux platform.
+
* xref:../rhel/index.adoc[Install Red Hat Enterprise Linux or CentOS]
* xref:../ubuntu/index.adoc[Install Ubuntu or Debian]

+
The new packages are installed as additional packages. Do not remove the existing packages.
