---
permalink: upgrade/performing-upgrade.html
sidebar: sidebar
keywords: upgrade, how to perform a software upgrade
summary: 'You can upgrade to StorageGRID 11.7 and apply the latest hotfix for that release at the same time. The StorageGRID upgrade page provides the recommended upgrade path and links directly to the correct download pages.'
---
= Perform the upgrade
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade to StorageGRID 11.7 and apply the latest hotfix for that release at the same time. The StorageGRID upgrade page provides the recommended upgrade path and links directly to the correct download pages.

.What you'll need
You have reviewed all of the considerations and completed all of the planning and preparation steps.

== Access StorageGRID Upgrade page

. Sign in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
. Select *Maintenance* > *System* > *Software update*.

. From the StorageGRID upgrade tile, select *Upgrade*.
+
The StorageGRID Upgrade page appears.

== Select files

. For the *Select files* step, review the update path to see which major versions (for example, 11.7.0) and hotfixes (for example, 11.7.0.1) you must install to get to the latest StorageGRID release. You should install the recommended versions and hotfixes in the order shown.
+
NOTE: If no update path is shown, your browser might not be able to access the NetApp Support Site, or the *Check for software updates* check box on the AutoSupport page (*SUPPORT* > *Tools* > *AutoSupport*) might be disabled.  

. From the Download files section, select each *Download* link to download the required files from the NetApp Support Site. 
+
If no update path is shown, go to the https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID^] to determine if a new version or hotfix is available and to download the files you need.


. Select *Browse* to upload the version upgrade file to StorageGRID: `NetApp_StorageGRID_11.7.0_Software_uniqueID.upgrade`
+
When the upload and validation process is done, a green checkmark appears next to the file name.

. If you downloaded a hotfix file, select *Browse* to upload that file. The hotfix will be automatically applied as part of the version upgrade.

. Select *Continue*.

== Run prechecks
Running prechecks allows you to detect and resolve any upgrade issues before you start upgrading your grid. 

. For the *Run prechecks* step, start by entering the provisioning passphrase for your grid.

. Select *Download recovery package*.
+
You should download the current copy of the Recovery Package file before you upgrade the primary Admin Node. The Recovery Package file allows you to restore the system if a failure occurs. 

. When the file is downloaded, confirm that you can access the contents, including the `Passwords.txt` file.

. Copy the downloaded file (`.zip`) to two safe, secure, and separate locations.
+
IMPORTANT: The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

. Select *Run prechecks*, and wait for the prechecks to complete. 

. Review the details for each reported precheck, and follow the instructions to resolve any reported errors.
+
You must resolve all precheck errors before you can upgrade your system. However, you do not need to address precheck warnings before upgrading.
+
IMPORTANT: If you have opened any custom firewall ports, you are notified during the precheck validation. You must contact technical support before proceeding with the upgrade.

. If you made any configuration changes to resolve the reported issues, select *Run prechecks* again to get updated results.
+
If all errors have been resolved, you are prompted to start the upgrade.


== Start upgrade and upgrade primary Admin Node
When you start the upgrade, the upgrade prechecks are run again, and the primary Admin Node is automatically upgraded. This part of the upgrade can take up to 30 minutes.

IMPORTANT: You will not be able to access any other Grid Manager pages while the primary Admin Node is being upgraded. Audit logs will also be unavailable.

. Select *Start upgrade*.
+
A warning appears to remind you will temporarily lose access to the Grid Manager.

. Select *OK* to acknowledge the warning and start the upgrade.

. Wait for the upgrade prechecks to be performed and for the primary Admin Node to be upgraded. 
+
NOTE: If any precheck errors are reported, resolve them and select *Start upgrade* again.

. As soon as the primary Admin Node has been upgraded, select *Continue* to upgrade the other nodes.
+
[NOTE]
====

If you refresh your browser or navigate to another Grid Manager page while the primary Admin Node is being upgraded, you might see multiple *503: Service Unavailable* and *Problem connecting to the server* messages. You can safely ignore these messages&#8212;they will stop appearing soon as the node is upgraded.

====



== Upgrade other nodes

You must upgrade all grid nodes, but you can perform multiple upgrade sessions and customize the upgrade sequence. For example, you might prefer to upgrade the nodes at site A in one session and then upgrade the nodes at site B in a later session. If you choose to perform the upgrade in more than one session, be aware that you can't start using the new features until all nodes have been upgraded. 

If the order in which nodes are upgraded is important, approve nodes or groups of nodes one at a time and wait until the upgrade is complete on each node before approving the next node or group of nodes.

IMPORTANT: When the upgrade starts on a grid node, the services on that node are stopped. Later, the grid node is rebooted. To avoid service interruptions for client applications that are communicating with the node, do not approve the upgrade for a node unless you are sure that node is ready to be stopped and rebooted. As required, schedule a maintenance window or notify customers. 

. For the *Upgrade other nodes* step, review the Summary, which provides the status and start time for each major upgrade task.

** *Start upgrade service* is the first upgrade task. During this task, the software file is distributed to the grid nodes, and the upgrade service is started on each node. 

** When the *Start upgrade service* task is complete, the *Upgrade other grid nodes* task starts, and you are prompted to download a new copy of the Recovery Package.

.  When prompted, enter your provisioning passphrase and xref:obtaining-required-materials-for-software-upgrade.adoc#download-the-recovery-package[download a new copy of the Recovery Package].
+
IMPORTANT: You should download a new copy of the Recovery Package file after  the primary Admin Node is upgraded. The Recovery Package file allows you to restore the system if a failure occurs.

. Review the status tables for each type of node. There are tables for  non-primary Admin Nodes, Gateway Nodes, Storage Nodes, and Archive Nodes.
+
A grid node can be in one of these stages when the tables first appear: 
+
* Unpacking the upgrade

* Downloading

* Waiting to be approved, or approved and waiting in the upgrade queue

. [[approval-step]]When you are ready to add grid nodes to the upgrade queue (or if you need to remove approved nodes from the queue), use these instructions:
+

[cols="1a,1a" options="header"]
|===
| Task | Instruction

|Search for specific nodes to approve, such as all nodes at a particular site
|Enter the search string in the *Search* field

|Add all nodes to the queue
|Select *Approve all nodes*

|Add all nodes of the same type to the queue (for example, all Storage Nodes) 
|Select the *Approve all* button for the node type

If you approve more than one node of the same type, the nodes will be upgraded one at a time.

|Add individual nodes to the queue
|Select the *Approve* button for the node

|Remove all nodes from the queue
|Select *Remove all nodes* 

|Remove all nodes of the same type from the queue
|Select the *Remove all* button for the node type

|Remove individual nodes from the queue
|Select the *Remove from queue* button for the node

|===

. Wait for the approved nodes to proceed through these upgrade stages:
+
* Queued
* Stopping services
+
NOTE: You cannot remove a node when its Stage reaches *Stopping services*. The *Remove* button is hidden.

* Stopping container
* Cleaning up Docker images
* Upgrading base OS packages
+
NOTE: When an appliance node reaches this stage, the StorageGRID Appliance Installer software on the appliance is updated. This automated process ensures that the StorageGRID Appliance Installer version remains in sync with the StorageGRID software version.

* Rebooting
* Performing steps after reboot
* Starting services
* Done

. Repeat the <<approval-step,approval step>> as many times as needed until all grid nodes have been upgraded. 

== Complete upgrade

When all grid nodes have completed the upgrade stages, the *Upgrade other grid nodes* task is shown as Completed. The remaining upgrade tasks are performed automatically in the background.

. As soon as the *Enable features* task is complete (which occurs quickly), you can start using the new features in the upgraded StorageGRID version.

. During the *Upgrade database* task, the upgrade process checks each node to verify that the Cassandra database does not need to be updated.
+
NOTE: The upgrade from StorageGRID 11.6 to 11.7 does not require a Cassandra database upgrade; however, the Cassandra service will be stopped and restarted on each Storage Node. For future StorageGRID feature releases, the Cassandra database update step might take several days to complete.

. When the *Upgrade database* task has completed, wait a few minutes for the *Final upgrade steps* to complete.

. When the *Final upgrade steps* have completed, the upgrade is done. The first step, *Select files*, is redisplayed with a green success banner.


. Verify that grid operations have returned to normal:
 .. Check that the services are operating normally and that there are no unexpected alerts.
 .. Confirm that client connections to the StorageGRID system are operating as expected.

