---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 11.7
summary: 'This release of StorageGRID introduces the following features.'
---
= What's new in StorageGRID 11.7
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features and functional changes.

== New features

=== Grid federation, account sync, and cross-grid replication
You can configure a grid federation connection between two StorageGRID systems to clone tenant account information and replicate bucket objects between the grids for disaster recovery. See link:../admin/grid-federation-overview.html[Use grid federation], link:../admin/grid-federation-what-is-account-clone.html[What is account clone], and link:../admin/grid-federation-what-is-cross-grid-replication.html[What is cross-grid replication].

=== Rename grid, sites, and nodes
A new maintenance procedure (*MAINTENANCE* > *Tasks* > *Rename grid, sites, and nodes*) lets you change the display names that are shown throughout the Grid Manager. You can update display names safely and whenever you need. See link:../maintain/rename-grid-site-node-overview.html[Rename grid, sites, and nodes: Overview].

=== FabricPool and S3 setup wizard and dashboard reminder
The new FabricPool and S3 setup wizard guides you through each step of configuring StorageGRID for use with ONTAP FabricPool or other S3 client application and produces a file you can use when entering required values in the other application. Use the wizard to create an HA group, load balancer endpoint, tenant, bucket, and access keys more quickly and to make sure your settings conform to StorageGRID best practices.

As part of this change, a new banner is displayed on the dashboard to remind new users to configure endpoint domain names for S3 virtual-hosted-style requests and to set up email notifications for alerts.

See link:../admin/use-s3-setup-wizard.html[Use S3 setup wizard]  and link:../fabricpool/use-fabricpool-setup-wizard.html[Use FabricPool setup wizard].

=== New firewall controls and changes to untrusted Client Networks
You can now better manage access to your grid using the new Firewall control page (*CONFIGURATION* > *Security* > *Firewall control*). This page enables you to manage the external access of ports on nodes in your grid, and to define host addresses and IP subnets that are allowed access to closed ports. The untrusted Client Network settings have been moved to the Firewall control page and have also been enhanced with the ability to select additional ports you want open when untrusted Client Network is configured. These ports can provide access to the Grid Manager, the Tenant Manager, or both.

===  Enhanced security policies
You can now determine which protocols and ciphers are used to establish secure TLS connections with client applications and secure SSH connections to internal StorageGRID services. See link:../admin/manage-tls-ssh-policy.html[Manage the TLS and SSH policy].

=== Changes to load balancer endpoints
When you link:../admin/configuring-load-balancer-endpoints.html[configure load balancer endpoints], you can now do the following:

* Allow all tenants to access the endpoint (default), or specify a list of allowed or blocked tenants to provide better security isolation between tenants and their endpoints. 
* Use the *Node Type* binding mode to require clients to use the IP address (or corresponding FQDN) of any Admin Node or the IP address of any Gateway Node, based on the type of node you select.

== Grid Manager updates

=== New Grid Manager dashboard
You can now configure custom dashboards for the Grid Manager. See link:../monitor/viewing-dashboard.html[View and manage the dashboard].

=== Volume restoration
Storage volume restoration lets you restore object data if a storage volume fails. For StorageGRID 11.7, volume restoration can be started in Grid Manager in addition to the existing method of entering commands manually. See link:../maintain/restoring-volume.html[Restore object data using Grid Manager]. Using Grid Manager is now the preferred method for restoring object data: entering commands manually to restore object data should only be used when replacing a node where the replacement node has fewer volumes than the original.

=== New upgrade and hotfix process
* You can now use the Grid Manager to upgrade to a future release and apply a hotfix for that release at the same time. The StorageGRID upgrade page shows the recommended upgrade path and links directly to the correct download pages.
* The *Check for software updates* check box on the AutoSupport page (*SUPPORT* > *Tools* >
*AutoSupport*) lets you control this functionality. You can disable the check for available software updates if your system does not have internet access. See link:../admin/configure-autosupport-grid-manager.html[Configure AutoSupport].

=== ILM 
The ILM wizard in the Grid Manager has been improved.

=== Changes to audit messages
A new audit message category was added for ILM operations, which includes the IDEL, LKCU, and ORLM messages. This new category is set to *Normal*. See link:../audit/ilm-audit-messages.html[ILM operations audit messages].

The following new audit messages were added:

* *BROR: Bucket Read Only Request*: Related to the new functionality for emptying a bucket, this message is generated when a bucket enters or exits read-only mode.

* *CGRR: Cross-Grid Replication Request*: This message is generated when StorageGRID attempts a cross-grid replication operation to replicate objects between buckets in a grid federation connection.

* *EBDL: Empty Bucket Delete*: Related to the new functionality for emptying a bucket, this message is generated when the ILM scanner deletes an object in a bucket that is deleting all objects (performing an empty bucket operation).

* *EBKR: Empty Bucket Request*: Related to the new functionality for emptying a bucket, this message is generated when a user sends a request to turn empty bucket on or off (that is, to delete bucket objects or to stop deleting objects).

* *S3SL: S3 Select Request*: Related to the S3 Select functionality, this message is generated after an S3 Select request has been returned to the client.

=== New units setting for storage values
You can now select base 10 or base 2 units for the storage values displayed in the Grid Manager and Tenant Manager. Select the user drop-down in the upper right of the Grid Manager or Tenant Manager, then select *User preferences*.

=== Access MIB from Grid Manager
You can now access SNMP-compliant MIB files from the Grid Manager using the SNMP agent page (*CONFIGURATION* > *Monitoring* > *SNMP agent*).

=== Upgrade drive firmware using the Grid Manager
You can now update the firmware on the drives in your storage appliances by using the Grid Manager. Using the Grid Manager enables you to update the firmware without needing to put the appliance into maintenance mode.

== Tenant Manager updates

=== Delete all objects from bucket
Tenant users can now delete all objects in a bucket, so the bucket can be deleted. See link:../tenant/deleting-s3-bucket-objects.html[Delete objects in bucket].

== S3 updates

=== S3 Object Lock supports governance mode
When specifying the S3 Object Lock settings for an object or the default retention settings for a bucket, you can now use governance mode. This retention mode allows users with special permission to bypass certain retention settings. These users can delete an object version before its retention period has elapsed, or they can increase, decrease, or remove an object's retention period. See link:../tenant/using-s3-object-lock.html[Use S3 Object Lock to retain objects] and link:../s3/use-s3-api-for-s3-object-lock.html[Use S3 REST API to configure S3 Object Lock].

Related to this change, Tenant Manager users can now enable default retention while they are creating a bucket, and they can specify a default retention mode and retention period. See link:../tenant/creating-s3-bucket.html[Create an S3 bucket].

=== New S3 group policy for ransomware mitigation
When added as the group policy for an S3 tenant account, the sample policy helps mitigate ransomware attacks. It prevents older object versions from being permanently deleted. See link:../tenant/creating-groups-for-s3-tenant.html[Create groups for an S3 tenant].

=== NewerNoncurrentVersions threshold for S3 buckets 
The `NewerNoncurrentVersions` action in the bucket lifecycle configuration specifies the number of noncurrent versions retained in a versioned S3 bucket. This threshold overrides lifecycle rules provided by ILM. See link:../ilm/how-objects-are-deleted.html[How objects are deleted].

=== S3 Select supported on bare metal endpoints
You can now use S3 Select with Admin and Gateway load balancer endpoints that are bare metal nodes running a kernel with cgroup v2 enabled.

== Other enhancements

=== Certificate subject optional
The certificate subject field is now optional. If this field is left blank, the generated certificate uses the first domain name or IP address as the subject common name (CN).

=== New alerts
The following new alerts were added for StorageGRID 11.7:

* Appliance DAS drive fault detected
* Appliance DAS drive rebuilding
* Appliance fan fault detected
* Appliance NIC fault detected
* Appliance SSD critical warning
* AutoSupport message failed to send
* Cassandra oversize write error
* Cross-grid replication permanent request failure
* Cross-grid replication resources unavailable
* Debug performance impact
* Expiration of grid federation certificate
* FabricPool bucket has unsupported bucket consistency setting
* Firewall configuration failure
* Grid federation connection failure
* Storage appliance fan fault detected
* Storage Node not in desired storage state
* Storage volume needs attention
* Storage volume needs to be restored
* Storage volume offline
* Trace configuration enabled
* Volume Restoration failed to start replicated data repair

=== Storage pools created for each site during installation
When you install StorageGRID 11.7 on a new grid, storage pools are automatically created for each site to reduce the number of steps required to create new ILM rules. Site-specific storage pools are not created during upgrades to StorageGRID 11.7.

=== Assign custom storage grades to new Storage Nodes
When you perform an expansion to add a new site or new Storage Nodes, you can now assign a custom storage grade to each new node. See link:../expand/performing-expansion.html[Perform expansion].

=== StorageGRID documentation changes

* A quick reference was added to summarize StorageGRID’s support for Amazon Simple Storage Service (S3) APIs.
+
link:../s3/quick-reference-support-for-aws-apis.html[Quick reference: Supported S3 API requests]

* The appliance hardware installation sections were combined and consolidated for ease of use. A quick start was added as a high-level guide to hardware installation.
+
link:../installconfig/index.html[Quick start for hardware installation]

* The maintenance instructions common to all appliance models were combined, consolidated, and moved to the maintenance section.
+
link:../commonhardware/index.html[Common node maintenance: Overview]

* The maintenance instructions specific to each appliance model were moved to the maintenance section.
+
link:../sg100-1000/index.html[Maintain SG100 and SG1000 appliances]
+
link:../sg6000/index.html[Maintain SG6000 appliance]
+
link:../sg5700/index.html[Maintain SG5700 appliance]
+
link:../sg5600/index.html[Maintain SG5600 appliance]