---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 11.7
summary: 'This release of StorageGRID introduces the following features.'
---
= What's new in StorageGRID 11.7
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features.

== Kathy's what's new

=== FabricPool and S3 setup wizard and Dashboard reminder
The new FabricPool and S3 setup wizard guides you through each step of configuring StorageGRID for use with ONTAP FabricPool or other S3 client application and produces a file you can use when entering required values in the other application. Use the wizard to create an HA group, load balancer endpoint, tenant, bucket, and access keys more quickly and to make sure your settings conform to StorageGRID best practices.

As part of this change, a new banner is displayed on the Dashboard to remind new users to configure endpoint domain names for S3 virtual hosted-style requests and to set up email notifications for alerts.

See xref:../admin/use-s3-setup-wizard.adoc[Use S3 setup wizard]  and xref:../fabricpool/use-fabricpool-setup-wizard.adoc[Use FabricPool setup wizard].

=== Control tenant access to load balancer endpoints
When you create a load balancer endpoint, you can now allow all tenants to access the endpoint (default), or you can specify a list of the allowed or blocked tenants.Tenant access lets you provide better security isolation between tenants and their endpoints. 

=== New upgrade and hotfix process
* You can now use the Grid Manager to upgrade to a future release and apply a hotfix for that release at the same time. The StorageGRID upgrade page shows the recommended upgrade path and links directly to the correct download pages.
* The *Check for software updates* check box on the AutoSupport page (*SUPPORT* > *Tools* >
*AutoSupport*) lets you control this functionality. You can disable the check for available software updates if your system does not have WAN access. See xref:../admin/configure-autosupport-grid-manager.adoc[Configure AutoSupport].

=== New S3 group policy for ransomware mitigation
When added as the group policy for an S3 tenant account, the sample policy helps mitigate ransomware attacks. It prevents older object versions from being permanently deleted. See xref:../tenant/creating-groups-for-s3-tenant.adoc[Create groups for an S3 tenant].

=== S3 Object Lock supports governance mode
When specifying the S3 Object Lock settings for an object or the default retention settings for a bucket, you can now use governance mode. This retention mode allows users with special permission to bypass certain retention settings. These users can delete an object version before its retention period has elapsed, or they can increase, decrease, or remove an object's retention period.

See xref:../tenant/configure-s3-object-lock-settings-for-bucket.adoc[Configure S3 Object Lock settings for a bucket] and xref:../s3/using-s3-object-lock.adoc[Use S3 REST API to configure S3 Object Lock].

=== Can rename grid, sites, and nodes
A new maintenance procedure (*MAINTENANCE* > *Tasks* > *Rename grid, sites, and nodes*) lets you change the display names that are shown throughout the Grid Manager. You can update display names safely and whenever you need. See xref:../maintain/rename-grid-site-node-overview.adoc[Rename grid, sites, and nodes: Overview] for details.

=== Storage pools created for each site during installation
When you install StorageGRID 11.7 on a new grid, storage pools are automatically created for each site to reduce the number of steps required to create new ILM rules. Site-specific storage pools are not created during upgrades to StorageGRID 11.7.

=== New audit messages
The following new audit messages were added:

* *BROR: Bucket Read Only Request*: Related to the new functionality for emptying a bucket, this message is generated when a bucket enters or exits read-only mode.


== Kevin's what's new

=== NewerNoncurrentVersions threshold for S3 buckets 
The `NewerNoncurrentVersions` action in the bucket lifecycle configuration specifies the number of noncurrent versions retained in a versioned S3 bucket. This threshold overrides lifecycle rules provided by ILM. See xref:../ilm/how-objects-are-deleted.adoc[How objects are deleted].

=== Certificate subject optional
The certificate subject field is now optional. If this field is left blank, the generated certificate uses the first domain name or IP address as the subject common name (CN).


== Lisa's what's new


== Paul's what's new


== Santhosh's what's new