---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 11.7
summary: 'This release of StorageGRID introduces the following features.'
---
= What's new in StorageGRID 11.7
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features.

== Kathy's what's new

=== New upgrade and hotfix process
* You can now can use the Grid Manager to upgrade to a future release and apply a hotfix for that release at the same time. The StorageGRID upgrade page shows the recommended upgrade path and links directly to the correct download pages.
* The *Check for software updates* check box on the AutoSupport page (*SUPPORT* > *Tools* >
*AutoSupport*) lets you control this functionality. You can disable the check for available software updates if your system does not have WAN access. See xref:../admin/configure-autosupport-grid-manager.adoc[Configure AutoSupport].

=== New S3 group policy for ransomware mitigation
When added as the group policy for an S3 tenant account, the sample policy helps mitigate ransomware attacks. It prevents older object versions from being permanently deleted. See xref:../tenant/creating-groups-for-s3-tenant.adoc[Create groups for an S3 tenant].

=== S3 Object Lock supports governance mode
When specifying the S3 Object Lock settings for an object or the default retention settings for a bucket, you can now use governance mode. This retention mode allows users with special permission to bypass certain retention settings. These users can delete an object version before its retention period has elapsed, or they can increase, decrease, or remove an object's retention period.

See xref:../tenant/configure-s3-object-lock-settings-for-bucket.adoc[Configure S3 Object Lock settings for a bucket] and xref:../s3/using-s3-object-lock.adoc[Use S3 REST API to configure S3 Object Lock].

=== Can rename grid, sites, and nodes
A new maintenance procedure (*MAINTENANCE* > *Tasks* > *Rename grid, sites, and nodes*) lets you change the display names that are shown throughout the Grid Manager. You can update display names safely and whenever you need. See xref:../maintain/rename-grid-site-node.adoc[Rename the grid, sites, and nodes].

== Grid federation
You can now create a connection between two StorageGRID systems. Grid connections let you synchronize account information and replicate objects between grids for disaster recovery. See xref:../admin/grid-federation-overview.adoc[Use grid federation: Overview].


== Kevin's what's new


== Lisa's what's new


== Paul's what's new