---
permalink: ubuntu/planning-and-preparation.html
sidebar: sidebar
keywords: how to prepare for ubuntu or debian installation
summary: 'Before deploying grid nodes and configuring the StorageGRID grid, you must be familiar with the steps and requirements for completing the procedure.'
---
= Before you install (Ubuntu or Debian)
:icons: font
:imagesdir: ../media/

[.lead]
Before deploying grid nodes and configuring StorageGRID, you must be familiar with the steps and requirements for completing the procedure.

The StorageGRID deployment and configuration procedures assume that you are familiar with the architecture and operation of the StorageGRID system.

You can deploy a single site or multiple sites at one time; however, all sites must meet the minimum requirement of having at least three Storage Nodes.

Before starting a StorageGRID installation, you must:

* Understand the compute requirements, including the minimum CPU and RAM requirements for each node.
* Understand how StorageGRID supports multiple networks for traffic separation, security, and administrative convenience, and have a plan for which networks you intend to attach to each StorageGRID node.
+
See the StorageGRID link:../network/index.html[Networking guidelines].

* Understand the storage and performance requirements of each type of grid node.
* Identify a set of servers (physical, virtual, or both) that, in aggregate, provide sufficient resources to support the number and type of StorageGRID nodes you plan to deploy.
* Understand the link:node-container-migration-requirements.html[requirements for node migration], if you want to perform scheduled maintenance on physical hosts without any service interruption.
* Gather all networking information in advance. Unless you are using DHCP, gather the IP addresses to assign to each grid node, and the IP addresses of the DNS and NTP servers that will be used.
* Install, connect, and configure all required hardware, including any StorageGRID appliances, to specifications.
+

IMPORTANT: If your StorageGRID installation will not use StorageGRID appliance (hardware) Storage Nodes, you must use hardware RAID storage with battery-backed write cache (BBWC). StorageGRID does not support the use of virtual storage area networks (vSANs), software RAID, or no RAID protection.
+

NOTE: Hardware-specific installation and integration instructions are not included in the StorageGRID installation procedure. To learn how to install StorageGRID appliances, see link:../installconfig/index.html[Install appliance hardware].

* Decide which of the available deployment and configuration tools you want to use.

