---
permalink: ubuntu/required-materials.html
sidebar: sidebar
keywords: installation materials ubuntu debian
summary: 'Before you install StorageGRID, you must gather and prepare required materials.'
---
= Required materials
:icons: font
:imagesdir: ../media/

[.lead]
Before you install StorageGRID, you must gather and prepare required materials.

[options="header"]
|===
| Item| Notes
a|
NetApp StorageGRID license
a|
You must have a valid, digitally signed NetApp license.

*Note*: A non-production license, which can be used for testing and proof of concept grids, is included in the StorageGRID installation archive.

a|StorageGRID installation archive
a|You must link:downloading-and-extracting-storagegrid-installation-files.html[download the StorageGRID installation archive and extract the files].

a|Service laptop
a|The StorageGRID system is installed through a service laptop.

The service laptop must have:

* Network port
* SSH client (for example, PuTTY)
* link:../admin/web-browser-requirements.html[Supported web browser]

a|StorageGRID documentation
a|
* link:../release-notes/index.html[Release notes]
* link:../admin/index.html[Instructions for administering StorageGRID]
|===

.Related information

https://imt.netapp.com/matrix/#welcome[NetApp Interoperability Matrix Tool^]