---
permalink: installconfig/configuring-hardware.html
sidebar: sidebar
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking
summary: 'After applying power to the appliance, perform the necessary configuration steps. These steps vary depending on the type of appliance you are installing.'
---
= Set up hardware: Overview
:icons: font
:imagesdir: ../media/

[.lead]
After applying power to the appliance, perform the necessary configuration steps. These steps vary depending on the type of appliance you are installing.

If you are using https://configbuilder.netapp.com/index.aspx[ConfigBuilder^], these steps will be completed automatically. See link:automating-appliance-installation-and-configuration.html[Automate appliance installation and configuration].

* All appliances
** Configure network connections
** As needed, enable node encryption and remap network ports

* Storage appliances
** Configure SANtricity System Manager (SG6000 and SG5700) or SANtricity Storage Manager (SG5600), the software you will use to monitor the hardware
** Change the RAID mode

* Services appliances
** Access the BMC interface for the SG100 and SG1000 and the SG6000-CN controller