---
permalink: installconfig/connecting-ac-power-cords-sg5600.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, wire, wiring, cabling, cable, Connecting, connect, power cords, power, ac, ac power, power on, power, start
summary: 'You must connect the AC power cords to the external power source and to the AC power connector on each controller. After you have connected the power cords, you can turn the power on.'
---
= Connect power cords and apply power (SG5600)
:icons: font
:imagesdir: ../media/

[.lead]
You must connect the AC power cords to the external power source and to the AC power connector on each controller. After you have connected the power cords, you can turn the power on.

.What you'll need

Both appliance power switches must be off before connecting power.

CAUTION: *Risk of electrical shock* -- Before connecting the power cords, make sure that the two power switches on the appliance are off.

.About this task

* You should use separate power sources for each power supply.
+
Connecting to independent power sources maintains power redundancy.

* You can use the power cords shipped with the controller with typical outlets used in the destination country, such as wall receptacles of an uninterrupted power supply (UPS).
+
However, these power cords are not intended for use in most EIA-compliant cabinets.

.Steps

. Turn off the power switches in the enclosure or chassis.
. Turn off the power switches on the controllers.
. Connect the primary power cords from the cabinet to the external power sources.
. Connect the power cords to the AC power connector on each controller.

== Turn power on

Powering on the enclosure provides power to both controllers.

.Steps

. Turn on the two power supply switches at the rear of the enclosure.
+
While the power is being applied, the LEDs on the controllers go on and off intermittently.
+
The power-on process can take up to ten minutes to complete. The controllers reboot several times during the initial startup sequence, which causes the fans to ramp up and down and the LEDs to flash.

. Check the Power LED and the Host Link Active LEDs on each controller to verify that the power was turned on.
. Wait for all drives to show a persistent green LED, indicating that they have come online.
. Check for green LEDs on the front and rear of the enclosure.
+
If you see any amber LEDs, make a note of their locations.

. Look at the seven-segment display for the E5600SG controller.
+
This display shows *HO*, followed by a repeating sequence of two digits.
+
----
HO -- IP address for Admin Network -- IP address for Grid Network HO
----
+
In the sequence, the first set of numbers is the DHCP-assigned IP address for the controller's management port 1. This address is used to connect the controller to the Admin Network for StorageGRID. The second set of numbers is the DHCP-assigned IP address used to connect the appliance to the Grid Network for StorageGRID.
+
NOTE: If an IP address could not be assigned using DHCP, 0.0.0.0 is displayed.
