---
permalink: installconfig/gathering-installation-information-overview.html
sidebar: sidebar
keywords: install, information, site, pre-install, preparing, prepare, preinstall, info, preparation
summary: 'As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.'
---
= Gather installation information: Overview
:icons: font
:imagesdir: ../media/

[.lead]
As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes. 

The installation information required to install and configure the hardware is unique for each appliance type. Record the information for each network you connect to the appliance before you install it.

Alternatively, you can work with your NetApp professional services consultant to use the NetApp ConfigBuilder tool to streamline and automate the configuration steps. See link:automating-appliance-installation-and-configuration.html[Automating appliance installation and configuration].

* link:gathering-installation-information-sg6100.html[SGF6112]
* link:gathering-installation-information-sg6000.html[SG6000]
* link:gathering-installation-information-sg5700.html[SG5700]
* link:gathering-installation-information-sg5600.html[SG5600]
* link:gathering-installation-information-sg100-and-sg1000.html[SG100 and SG1000]
