---
sidebar: sidebar
permalink: installconfig/obtaining_additional_equipment_and_tools.html
keywords: stub, layered
summary: Obtaining additional equipment and tools.
---

= Obtaining additional equipment and tools




:icons: font

:imagesdir: ../media/

[.lead]
(New intro container topic.)

Combined into single topic from all appliance guides, if possible.
"Common equipment and tools" and then sub listings from each appliance pub, if needed.

== SG100-and SG1000-specific equipment and tools

Pick up content from existing appliance guide (Obtaining additional equipment and tools SG100 and SG1000).

== SG5600-specific equipment and tools

Pick up content from existing appliance guide (Obtaining additional equipment and tools SG5600).

Check separate "Service laptop requirements SG5600" topic.

== SG5700-specific equipment and tools

Pick up content from existing appliance guide (Obtaining additional equipment and tools SG5700).

== SG6000-specific equipment and tools

Pick up content from existing appliance guide (Obtaining additional equipment and tools SG6000).
