---
permalink: swift/configuring-security-for-rest-api.html
sidebar: sidebar
keywords: configure rest api security
summary: 'You should review the security measures implemented for the REST API and understand how to secure your system.'
---
= Configure security for REST API
:icons: font
:imagesdir: ../media/

[.lead]
You should review the security measures implemented for the REST API and understand how to secure your system.

== How StorageGRID provides security for REST API

You should understand how the StorageGRID system implements security, authentication, and authorization for the REST API.

StorageGRID uses the following security measures.

* Client communications with the Load Balancer service use HTTPS if HTTPS is configured for the load balancer endpoint.
+
When you xref:../admin/configuring-load-balancer-endpoints.adoc[configure a load balancer endpoint], HTTP can optionally be enabled. For example, you might want to use HTTP for testing or other non-production purposes.

* By default, StorageGRID uses HTTPS for client communications with Storage Nodes.
+
Optionally, xref:../admin/enabling-http-for-client-communications.adoc[enable HTTP for these connections]. For example, you might want to use HTTP for testing or other non-production purposes.
+

* Communications between StorageGRID and the client are encrypted using TLS.
* Communications between the Load Balancer service and Storage Nodes within the grid are encrypted whether the load balancer endpoint is configured to accept HTTP or HTTPS connections.
* Clients must supply HTTP authentication headers to StorageGRID to perform REST API operations.

=== Security certificates and client applications

Clients can connect to the Load Balancer service on Gateway Nodes or Admin Nodes, directly to Storage Nodes.

In all cases, client applications can make TLS connections using either a custom server certificate uploaded by the grid administrator or a certificate generated by the StorageGRID system:

* When client applications connect to the Load Balancer service, they do so using the certificate that was configured for the specific load balancer endpoint used to make the connection. Each endpoint has its own certificate, which is either a custom server certificate uploaded by the grid administrator or a certificate that the grid administrator generated in StorageGRID when configuring the endpoint.
* When client applications connect directly to a Storage Node, they use either the system-generated server certificates that were generated for Storage Nodes when the StorageGRID system was installed (which are signed by the system certificate authority), or a single custom server certificate that is supplied for the grid by a grid administrator.

Clients should be configured to trust the certificate authority that signed whichever certificate they use to establish TLS connections.

See xref:../admin/configuring-load-balancer-endpoints.adoc[configuring load balancer endpoints] and xref:../admin/configuring-custom-server-certificate-for-storage-node.adoc[adding a single custom server certificate] for TLS connections directly to Storage Nodes.

=== Summary

The following table shows how security issues are implemented in the S3 and Swift REST APIs:

[options="header"]
|===
| Security issue| Implementation for REST API
a|
Connection security
a|
TLS
a|
Server authentication
a|
X.509 server certificate signed by system CA or custom server certificate supplied by administrator
a|
Client authentication
a|

* S3: S3 account (access key ID and secret access key)
* Swift: Swift account (user name and password)

a|
Client authorization
a|

* S3: Bucket ownership and all applicable access control policies
* Swift: Administrator role access

|===

== Supported hashing and encryption algorithms for TLS libraries

The StorageGRID system supports a limited set of cipher suites that client applications can use when establishing a Transport Layer Security (TLS) session.

=== Supported versions of TLS

StorageGRID supports TLS 1.2 and TLS 1.3.

IMPORTANT: SSLv3 and TLS 1.1 (or earlier versions) are no longer supported.

=== Supported cipher suites

CAUTION: The cipher type must match the server certificate type. For example, RSA ciphers require RSA certificates, and ECDSA ciphers require ECDSA certificates. See xref:../admin/using-storagegrid-security-certificates.adoc[About security certificates].

[cols="1a,1a" options="header"]
|===
| TLS version| IANA name of cipher suite
.3+|1.2
|TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
|TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

.3+|1.3
|TLS_AES_256_GCM_SHA384
|TLS_CHACHA20_POLY1305_SHA256
|TLS_AES_128_GCM_SHA256
|===

=== Deprecated cipher suites

The following cipher suites are deprecated. Support for these ciphers will be removed in a future release.

[options="header"]
|===
| IANA Name
a|
TLS_RSA_WITH_AES_128_GCM_SHA256
a|
TLS_RSA_WITH_AES_256_GCM_SHA384
|===

.Related information

xref:configuring-tenant-accounts-and-connections.adoc[Configure tenant accounts and connections]
