---
permalink: network/appliance-nodes.html
sidebar: sidebar
keywords: networking for appliance, port bond mode
summary: 'You can configure the network ports on StorageGRID appliances to use the port bond modes that meet your requirements for throughput, redundancy, and failover.'
---
= Appliance nodes
:icons: font
:imagesdir: ../media/

[.lead]
You can configure the network ports on StorageGRID appliances to use the port bond modes that meet your requirements for throughput, redundancy, and failover.

The 10/25-GbE ports on the StorageGRID appliances can be configured in Fixed or Aggregate bond mode for connections to the Grid Network and Client Network.

The 1-GbE Admin Network ports can be configured in Independent or Active-Backup mode for connections to the Admin Network.

See the information about port bond modes in the installation instructions for your appliance:

* link:../installconfig/port-bond-modes-for-sg100-and-sg1000.html[Port bond modes for the SG100 and SG1000 appliances]

* link:../installconfig/port-bond-modes-for-sg6000-cn-controller.html[Port bond modes for SG6000-CN controller]

* link:../installconfig/port-bond-modes-for-e5700sg-controller-ports.html[Port bond modes for E5700SG controller ports]

* link:../installconfig/port-bond-modes-for-e5600sg-controller-ports.html[Port bond modes for the E5600SG controller ports]