---
permalink: tenant/creating-groups-for-swift-tenant.html
sidebar: sidebar
keywords: how to create Swift tenant groups
summary: 'You can manage access permissions for a Swift tenant account by importing federated groups or creating local groups. At least one group must have the Swift Administrator permission, which is required to manage the containers and objects for a Swift tenant account.'
---
= Create groups for a Swift tenant
:icons: font
:imagesdir: ../media/

[.lead]
You can manage access permissions for a Swift tenant account by importing federated groups or creating local groups. At least one group must have the Swift Administrator permission, which is required to manage the containers and objects for a Swift tenant account.

.What you'll need

* You are signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].

* You belong to a user group that has the xref:tenant-management-permissions.adoc[Root access permission].

* If you plan to import a federated group, you have xref:using-identity-federation.adoc[configured identity federation], and the federated group already exists in the configured identity source.

== Access the Create group wizard

. Select *ACCESS MANAGEMENT* > *Groups*.

. Select *Create group*.

== Choose a group type

. Select the *Local group* tab to create a local group, or select the *Federated group* tab to import a group from the previously configured identity source.
+
If single sign-on (SSO) is enabled for your StorageGRID system, users belonging to local groups will not be able to sign in to the Tenant Manager, although they can use client applications to manage the tenant's resources, based on group permissions.

. Enter the group's name.

 ** *Local group*: Enter both a display name and a unique name. You can edit the display name later.

 ** *Federated group*: Enter the unique name. For Active Directory, the unique name is the name associated with the `sAMAccountName` attribute. For OpenLDAP, the unique name is the name associated with the `uid` attribute.

. Select *Continue*.

== Manage group permissions

. For *Access mode*, select one of the following:
** *Read-write* (default): Users can sign in to Tenant Manager and manage the tenant configuration.
** *Read-only*: Users can only view settings and features. They cannot make any changes or perform any operations in the Tenant Manager or Tenant Management API. Local read-only users can change their own passwords.
+
NOTE: If a user belongs to multiple groups and any group is set to Read-only, the user will have read-only access to all selected settings and features.

. Select the *Root access* check box if group users need to sign in to the Tenant Manager or Tenant Management API.

. Select *Continue*.

. Select the *Swift administrator* check box if group users need to use the Swift REST API to manage containers and objects.
+
Swift users must have the Root access permission to access the Tenant Manager. However, the Root access permission does not allow them to authenticate into the Swift REST API to create containers and ingest objects.

. If you are creating a local group, select *Continue*. If you are creating a federated group, select *Create group* and *Finish*.

== Add users (local groups only)

. Optionally, select one or more local users for this group.
+
If you have not yet created local users, you can save the group without adding users. You can add this group to the user on the Users page. See xref:../tenant/managing-local-users.adoc[Manage local users].

. Select *Create group* and *Finish*.
+
The group you created appears in the list of groups.
