---
permalink: tenant/creating-groups-for-s3-tenant.html
sidebar: sidebar
keywords: how to create S3 tenant groups
summary: 'You can manage permissions for S3 user groups by importing federated groups or creating local groups.'
---
= Create groups for an S3 tenant
:icons: font
:imagesdir: ../media/

[.lead]
You can manage permissions for S3 user groups by importing federated groups or creating local groups.

.What you'll need
* You are signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You belong to a user group that has the Root Access permission. See xref:tenant-management-permissions.adoc[Tenant management permissions].
* If you plan to import a federated group, you have configured identity federation and the federated group already exists in the configured identity source.

For information about S3, see xref:../s3/index.adoc[Use S3 REST API].

== Access the wizard
. Select *ACCESS MANAGEMENT* > *Groups*.

. Select *Create group*.

== Choose a group type
. Select the *Local group* tab to create a local group, or select the *Federated group* tab to import a group from the previously configured identity source.
+
If single sign-on (SSO) is enabled for your StorageGRID system, users belonging to local groups will not be able to sign in to the Tenant Manager, although they can use client applications to manage the tenant's resources, based on group permissions.

. Enter the group's name.
 ** *Local group*: Enter both a display name and a unique name. You can edit the display name later.
 ** *Federated group*: Enter the unique name. For Active Directory, the unique name is the name associated with the `sAMAccountName` attribute. For OpenLDAP, the unique name is the name associated with the `uid` attribute.
. Select *Continue*.

== Manage group permissions
. For *Access mode*, select whether users in the group can change settings and perform operations in the Tenant Manager and the Tenant Management API or whether they can only view settings and features.
** *Read-write* (default): Users can sign in to Tenant Manager and manage the tenant configuration.
** *Read-only*: Users can only view settings and features. They cannot make any changes or perform any operations in the Tenant Manager or Tenant Management API. Local read-only users can change their own passwords.
+
NOTE: If a user belongs to multiple groups and any group is set to Read-only, the user will have read-only access to all selected settings and features.

. Select one or more permissions for this group.
+
See xref:../tenant/tenant-management-permissions.adoc[Tenant management permissions].

. Select *Continue*.

== Set S3 group policy
. Select a group policy to determine which S3 access permissions the members of this group will have.
** *No S3 Access*: Default. Users in this group do not have access to S3 resources, unless access is granted with a bucket policy. If you select this option, only the root user will have access to S3 resources by default.
** *Read Only Access*: Users in this group have read-only access to S3 resources. For example, users in this group can list objects and read object data, metadata, and tags. When you select this option, the JSON string for a read-only group policy appears in the text box. You cannot edit this string.
** *Full Access*: Users in this group have full access to S3 resources, including buckets. When you select this option, the JSON string for a full-access group policy appears in the text box. You cannot edit this string.

** *Ransomware Mitigation*: This sample policy applies to all buckets for this tenant. Users in this group can perform common actions, but cannot permanently delete objects from buckets that have object versioning enabled.
+
Tenant Manager users who have the Manage all buckets permission can override this group policy. Limit the Manage all buckets permission to trusted users, and use Multi-Factor Authentication (MFA) where available.

** *Custom*: Users in the group are granted the permissions you specify in the text box.

. If you selected *Custom*, enter the group policy. Each group policy has a size limit of 5,120 bytes. You must enter a valid JSON formatted string.
+
For detailed information about group policies, including language syntax and examples, see xref:../s3/example-group-policies.adoc[Example group policies].

. If you are creating a local group, select *Continue*. If you are creating a federated group, select *Create group* and *Finish*. 


== Add users (local groups only)

. Optionally, select one or more local users for this group.
+
If you have not yet created local users, you can save the group without adding users. You can add this group to the user on the Users page. See xref:../tenant/managing-local-users.adoc[Manage local users].

. Select *Create group* and *Finish*.
+
The group you created appears in the list of groups. Changes might take up to 15 minutes to take effect because of caching.