---
permalink: tenant/deleting-s3-bucket.html
sidebar: sidebar
keywords: how to delete S3 bucket
summary: 'You can use the Tenant Manager to delete an S3 bucket that is empty.'
---
= Delete S3 bucket
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Tenant Manager to delete one or more S3 buckets that are empty.

.What you'll need

* You are signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You belong to a user group that has the Manage All Buckets or the Root Access permission. These permissions override the permissions settings in group or bucket policies. See xref:tenant-management-permissions.adoc[Tenant management permissions].
* The buckets you want to delete are empty.

.About this task

These instructions describe how to delete an S3 bucket using the Tenant Manager. You can also delete S3 buckets using the xref:understanding-tenant-management-api.adoc[Tenant Management API] or the xref:../s3/s3-rest-api-supported-operations-and-limitations.adoc[S3 REST API].

You cannot delete an S3 bucket if it contains objects, noncurrent object versions, or delete markers. For information about how S3 versioned objects are deleted, see xref:../ilm/how-objects-are-deleted.adoc[How objects are deleted].

.Steps

. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.
+
The Buckets page appears and shows all existing S3 buckets.

. Use the *Actions* menu or the details page for a specific bucket.
+
[role="tabbed-block"]
====

.Actions menu
--
.. Select the check box for each bucket you want to delete. 
.. Select *Actions* > *Delete buckets*.

--

.Details page
--
.. Select a bucket name to display its details.
.. Select *Delete bucket*.

--

====


. When the confirmation dialog box appears, select *Yes*.
+
StorageGRID confirms that each bucket is empty and then deletes each bucket. This operation might take a few minutes.
+
If a bucket is not empty, an error message appears. You must delete all objects and any delete markers in the bucket before you can delete the bucket.