---
permalink: tenant/delete-all-bucket-objects.html
sidebar: sidebar
keywords: how to remove all bucket objects, empty bucket
summary: 'You can use the Tenant Manager to delete all objects and all object versions in one or more buckets.'
---
= Delete all objects from bucket
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Tenant Manager to delete all objects and all object versions in one or more buckets.

When you delete all objects from a bucket, StorageGRID permanently deletes all copies of all objects in the selected bucket from all nodes and sites in your StorageGRID system. If the bucket has versioning enabled, all versions of each object are removed. StorageGRID also removes any related object metadata. You will not be able to recover this information.

Deleting all bucket objects might take minutes, days, or even weeks, based on the number of objects and concurrent operations. While objects are being deleted, the bucket's state is *Read only: Deleting all objects*.

Buckets with S3 Object Lock enabled might remain in the *Read only: Deleting all objects* state for years. This state persists until the retention date is reached for all objects and any legal holds are removed.

If a bucket has cross-grid replication enabled, deleting all objects from one grid does not delete all objects from the corresponding bucket on the other grid. In addition, no delete markers are replicated to the other grid.

.What you'll need

* You are signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You belong to a user group that has the Root Access permission. This permission overrides the permissions settings in group or bucket policies. See xref:tenant-management-permissions.adoc[Tenant management permissions].

.Steps

. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.
+
The Buckets page appears and shows all existing S3 buckets.

. Use the *Actions* menu or the details page for a specific bucket.
+
[role="tabbed-block"]
====

.Actions menu
--
.. Select the check box for each bucket you want to delete objects from. 
.. Select *Actions* > *Delete objects in bucket*.

--

.Details page
--
.. Select a bucket name to display its details.
.. Select *Delete objects in bucket*.

--

====


. When the confirmation dialog box appears, review the details, enter *Yes*, and select *OK*.
+
Wait for the delete operation to begin. After a few minutes, a warning message appears on the bucket details page, which includes a progress bar.


