---
permalink: tenant/deleting-s3-bucket-objects.html
sidebar: sidebar
keywords: how to delete S3 bucket objects, empty bucket
summary: 'You can use the Tenant Manager to delete all of the objects in one or more S3 buckets.'
---
= Delete objects from S3 bucket
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Tenant Manager to delete all of the objects in one or more S3 buckets.

//Delete all bucket objects
When you delete all bucket objects, StorageGRID permanently deletes all copies of the bucket's objects, including any related metadata. You will not be able to recover this information.

Deleting all bucket objects might take minutes, days, or even weeks, based on the number of objects and concurrent operations. While objects are being deleted, the bucket's state is Read only: Deleting all objects.

Buckets with S3 Object Lock enabled might remain in the Read only: Deleting all objects state for years. This state persists until the retention date is reached for all objects and any legal holds are removed.


.What you'll need

* You are signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You belong to a user group that has the Root Access permission. This permission overrides the permissions settings in group or bucket policies. See xref:tenant-management-permissions.adoc[Tenant management permissions].

.Steps

. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.
+
The Buckets page appears and shows all existing S3 buckets.

. Use the *Actions* menu or the details page for a specific bucket.
+
[role="tabbed-block"]
====

.Actions menu
--
.. Select the check box for each bucket you want to delete objects from. 
.. Select *Actions* > *Delete bucket objects*.

--

.Details page
--
.. Select a bucket name to display its details.
.. Select *Delete bucket objects*.

--

====


. When the confirmation dialog box appears, enter *Yes* and select *OK*.
+
StorageGRID deletes objects from each bucket. This operation might take a few minutes.
