---
permalink: tenant/grid-federation-connections-view.html
sidebar: sidebar
keywords: 
summary: If your tenant account has the Use grid federation connection permission, you can view the allowed connections.
---
= View grid federation connections
:icons: font
:imagesdir: ../media/

[.lead]
If your tenant account has the *Use grid federation connection* permission, you can view the allowed connections.

.What you'll need

* The tenant account has the *Use grid federation connection* permission.
* You are signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have Root Access permission.

.Steps

. Select *STORAGE (S3)* > *Grid federation connections*.
+
NOTE: You must have Root Access permission to see this entry on the sidebar.
+
The Grid federation connection page appears, and includes a table that summarizes the following information:

* The *Connection name* column shows the grid federation connections this tenant has permission to use. 

* The *Buckets with cross-grid replication* column shows which buckets for this tenant on this grid have cross-grid replication enabled. Objects added to these buckets will be replicated to the other grid in the connection.

* The *Last error* column shows the most recent error to occur for this tenant when bucket data was being replicated to the other grid. An error in this column might occur for one of these reasons:

** The source object version was not found.
** The source bucket was not found.
** The destination bucket was deleted.
** The destination bucket was re-created by a different account.	
** The destination bucket has versioning suspended.
** The destination bucket was re-created by same account but is now unversioned.

. Optionally, select a bucket name to xref:viewing-s3-bucket-details.adoc[view bucket details].

. Optionally, select *Clear error* to clear the last error.

