---
permalink: tenant/grid-federation-use-account-clone.html
sidebar: sidebar
keywords: use account clone
summary: 'If your tenant account was assigned the Use grid federation connection permission when it was created, tenant accounts, tenant groups, tenant users, and, optionally, S3 access keys are replicated between a source StorageGRID system and a destination StorageGRID system. '
---
= Use account clone
:icons: font
:imagesdir: ../media/

[.lead]
If your tenant account was assigned the *Use grid federation connection* permission when it was created, tenant accounts, tenant groups, tenant users, and, optionally, S3 access keys are replicated between a source StorageGRID system and a destination StorageGRID system. 

Account clone is required for cross-grid replication. Cloning account information from a source grid to a destination grid ensures that tenant users and groups can access the corresponding buckets and objects on either grid.

For more details, requirements, and a workflow diagram for using account clone, go to link:../admin/grid-federation-what-is-account-clone.html[What is account clone].

== Enable account clone

To enable account clone, a grid admin follows the standard tenant-creation steps but adds the *Use grid federation connection* permission for a specific grid federation connection. When a new tenant with that permission is saved, StorageGRID automatically creates a replica of that tenant on the other grid. For details, see link:../admin/grid-federation-manage-tenants.html[Manage permitted tenants].  

The grid where the tenant is originally created is the tenant's _source grid_. The grid where the tenant is replicated to is the tenant's _destination grid_. Both tenant accounts have the same account ID, name, storage quota, and assigned permissions, but the tenant replicated to the destination grid has fewer capabilities and does not initially have a root user password.

== Configure identity federation on both grids

If your tenant account has the *Use own identity source* permission, follow the instructions in xref:using-identity-federation.adoc[Use identity federation]. Both the source and destination grids must use the same identity source and the same settings.

== Import federated groups and users to the source grid

If identity federation has been configured for the entire StorageGRID system or for your tenant account, note the following:

* To import federated groups, always start from the tenant's source grid. When you create a new group by importing a federated group to the source grid, the same group is automatically cloned to the destination grid. Both the original group and its clone have the same access mode, group permissions and S3 group policy. For instructions, see xref:creating-groups-for-s3-tenant.adoc[Create groups for S3 tenant].

* After you import a federated group to the source grid, federated users can access the source grid. However, federated user can't sign in to the destination grid unless their S3 access keys are manually cloned to the destination grid.

== Create local groups and users on the source grid

If you are not using identity federation, you can create new local groups and users. Note the following:

* To create local groups, always start from the tenant's source grid. When a new group is created on the source grid, the same group is automatically cloned to the destination grid. Both the original group and its clone will have the same access mode, group permissions and S3 group policy. For instructions, see xref:creating-groups-for-s3-tenant.adoc[Create groups for S3 tenant].

* When creating a local group, confirm that the *Unique name* does not already exist on the destination grid. A cloning error will occur if the same Unique name already exists for the tenant on the destination grid.

* To create local users, start from the tenant's source grid. When a new user is created on the source grid, the same user is automatically cloned to the destination grid. Both the original user and its clone will have the same full name, username, *Deny access* setting, and password, and both will belong to the same groups. For instructions, see xref:managing-local-users.adoc[Manage local users].

* When creating a local user, confirm that the *username* does not already exist on the destination grid. A cloning error will occur if the username already exists for the tenant on the destination grid.

== Create S3 access keys on the source grid

* Optionally, S3 access keys created on the source grid can be manually cloned to the destination grid.
+ 
For security reasons, StorageGRID does not automatically clone S3 access keys from the tenant's source grid to the destination grid. If tenant users need to access the buckets on both grids, you must use the Tenant Manager API to manually copy the keys from the source grid to the destination grid. See xref:../tenant/grid-federation-clone-keys-with-api.adoc[Clone S3 access keys using the API].

== Make edits on both grids
Any edits you make to the tenant, users, groups, or access keys on either grid are not cloned to the other grid. If you want to keep this information in sync, you must perform the same edits on both grids.

== Optionally, create groups, users, and keys on destination grid

Account cloning occurs in one direction only. If you import or create groups, users, and S3 access keys on the tenant's destination grid, these items are not cloned back to the source grid. 

