---
permalink: tenant/grid-federation-use-account-clone.html
sidebar: sidebar
keywords: use account clone
summary: 'If your tenant account was assigned the Use grid federation connection permission when it was created, you can use a grid federation connection to perform account clone.'
---
= Use account clone
:icons: font
:imagesdir: ../media/

[.lead]
If your tenant account was assigned the *Use grid federation connection* permission when it was created, you can use a grid federation connection to perform account clone.

== What is account clone?

Account clone is the replication of tenant accounts, tenant groups, tenant users, and, optionally, S3 access keys between a source StorageGRID system and a destination StorageGRID system. Account clone is required for cross-grid replication. Cloning account information from a source grid to a destination grid ensures that tenant users and groups can access the corresponding buckets and objects on either grid.

To enable account clone, a grid admin follows the standard tenant-creation steps but adds the *Use grid federation connection* permission for a specific grid federation connection. When a new tenant with that permission is saved, StorageGRID automatically creates a replica of that tenant on the other grid. For details, see link:../admin/grid-federation-manage-tenants.html[Manage permitted tenants].  

The grid where the tenant is originally created is known as the tenant's _source grid_. The grid where the tenant is replicated is known as the tenant's _destination grid_. Both tenant accounts have the same account ID, name, storage quota, and assigned permissions, but the tenant replicated to the destination grid does not initially have a root user password.

After tenants have been created and replicated, new groups and users are automatically cloned from the tenant's source grid to the tenant's destination grid.

For more details, requirements, and a workflow diagram for using account clone, go to link:../admin/grid-federation-what-is-account-clone.html[What is account clone].
