---
permalink: tenant/grid-federation-use-account-clone.html
sidebar: sidebar
keywords: use account clone
summary: 'If your tenant account was assigned the Use grid federation connection permission when it was created, you can use a grid federation connection to perform account clone.'
---
= Use account clone
:icons: font
:imagesdir: ../media/

[.lead]
If your tenant account was assigned the *Use grid federation connection* permission when it was created, you can use a grid federation connection to perform account clone.

== What is account clone?
Account clone is the automatic replication of selected S3 tenant accounts, users, and groups between two StorageGRID systems. Account clone is required for cross-grid replication. Using cloned accounts ensures that the same tenant users and groups can access the corresponding buckets and objects on each grid.

For details and requirements for using this feature, see link:../admin/grid-federation-overview.html#what-is-account-clone[Use grid federation: What is account clone?]

To see a workflow diagram for how to configure account clone, see link:../admin/grid-federation-workflow.html#workflow-for-account-clone[Workflow for account clone].

