---
permalink: tenant/update-default-retention-settings.html
sidebar: sidebar
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance
summary: 'If you enabled S3 Object Lock when you created the bucket, you can edit the bucket to change the default retention settings. You can enable (or disable) default retention and set a default retention mode and retention period.'
---
= Update S3 Object Lock default retention
:icons: font
:imagesdir: ../media/

[.lead]
If you enabled S3 Object Lock when you created the bucket, you can edit the bucket to change the default retention settings. You can enable (or disable) default retention and set a default retention mode and retention period.

.What you'll need
* You are signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You belong to a user group that has the xref:tenant-management-permissions.adoc[Manage all buckets or Root access permission]. These permissions override the permissions settings in group or bucket policies.

* S3 Object Lock is enabled globally for your StorageGRID system, and you enabled S3 Object Lock when you created the bucket. See xref:using-s3-object-lock.adoc[Use S3 Object Lock to retain objects].

.Steps
. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.

. Select the bucket name from the table.
+
The bucket details page appears.

. From the *Bucket options* tab, select the *S3 Object Lock* accordion.

. Optionally, enable or disable *Default retention* for this bucket.
+
Changes to this setting do not apply to objects already in the bucket or to any objects that might have their own retention periods.

. If *Default retention* is enabled, specify a *Default retention mode* for the bucket.
+
[cols="1a,2a" options="header"]
|===
| Default retention mode| Description

| Compliance
| * The object cannot be deleted until its retain-until-date is reached.

* The object's retain-until-date can be increased, but it cannot be decreased.

* The object's retain-until-date cannot be removed until that date is reached.

| Governance

|* Users with the `s3:BypassGovernanceRetention` permission can use the `x-amz-bypass-governance-retention: true` request header to bypass retention settings.

* These users can delete an object version before its retain-until-date is reached.

* These users can increase, decrease, or remove an object's retain-until-date.

|===


. If *Default retention* is enabled, specify the *Default retention period* for the bucket.
+
The *Default retention period* indicates how long new objects added to this bucket should be retained, starting from the time they are ingested. Specify a value between 1 and 36,500 days or between 1 and 100 years, inclusive.

. Select *Save changes*.