---
permalink: tenant/viewing-s3-bucket-details.html
sidebar: sidebar
keywords: how to view s3 bucket details
summary: 'You can view the buckets in your tenant account.'
---
= View S3 buckets
:icons: font
:imagesdir: ../media/

[.lead]
You can view the buckets in your tenant account.

.What you'll need

* You are signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].

.Steps
. Select *STORAGE (S3)* > *Buckets*.
+
The Buckets page appears and lists all buckets for the tenant account. 

. Review the information for each bucket.
+
As required, you can sort the information by any column, or you can page forward and back through the list.

* *Name*: The bucket's unique name, which cannot be changed.
* *S3 Object Lock*: Whether S3 Object Lock is enabled for this bucket.
+
This column appears only if S3 Object Lock is enabled for the grid. This column also shows information for any legacy Compliant buckets.
* *Region*: The bucket's region, which cannot be changed.
* *Object Count*: The number of objects in this bucket.
* *Space Used*: The logical size of all objects in this bucket. The logical size does not include the actual space required for replicated or erasure-coded copies or for object metadata.
* *Date Created*: The date and time the bucket was created.

+
IMPORTANT: The Object Count and Space Used values displayed are estimates. These estimates are affected by the timing of ingests, network connectivity, and node status. If buckets have versioning enabled, deleted object versions are included in the object count.


