---
permalink: rhel/troubleshooting-installation-issues.html
sidebar: sidebar
keywords: how to troubleshoot red hat linux centos installation
summary: 'If any problems occur while installing your StorageGRID system, you can access the installation log files. Technical support might also need to use the installation log files to resolve issues.'
---
= Troubleshoot installation issues
:icons: font
:imagesdir: ../media/

[.lead]
If any problems occur while installing your StorageGRID system, you can access the installation log files. Technical support might also need to use the installation log files to resolve issues.

The following installation log files are available from the container that is running each node:

* `/var/local/log/install.log` (found on all grid nodes)
* `/var/local/log/gdu-server.log` (found on the primary Admin Node)

The following installation log files are available from the host:

* `/var/log/storagegrid/daemon.log`
* `/var/log/storagegrid/nodes/node-name.log`

To learn how to access the log files, see the instructions for monitoring and troubleshooting StorageGRID. For help troubleshooting appliance installation issues, see the installation and maintenance instructions for your appliances. If you need additional help, contact technical support.

.Related information

link:../monitor/index.html[Monitor and troubleshoot]

link:../sg100-1000/index.html[SG100 and SG1000 services appliances]

link:../sg6100/index.html[SG6100 storage appliances]

link:../sg5700/index.html[SG5700 storage appliances]

https://mysupport.netapp.com/site/global/dashboard[NetApp Support^]
