---
permalink: admin/archiving-to-cloud-through-s3-api.html
sidebar: sidebar
keywords: archive node to aws, amazon web services
summary: 'You can configure an Archive Node to connect directly to Amazon Web Services \(AWS\) or to any other system that can interface to the StorageGRID system through the S3 API.'
---
= Archive to the cloud through the S3 API
:icons: font
:imagesdir: ../media/

[.lead]
You can configure an Archive Node to connect directly to Amazon Web Services (AWS) or to any other system that can interface to the StorageGRID system through the S3 API.

NOTE: Support for Archive Nodes is deprecated and will be removed in a future release. Moving objects from an Archive Node to an external archival storage system through the S3 API has been replaced by ILM Cloud Storage Pools, which offer more functionality. The Cloud Tiering - Simple Storage Service (S3) option is now deprecated. +
If you are currently using an Archive Node with the Cloud Tiering - Simple Storage Service (S3) option, migrate your objects to a Cloud Storage Pool. See link:../ilm/index.html[Manage objects with ILM]. +
Addtionally, you should remove Archive Nodes from active ILM policies in StorageGRID 11.7 or earlier. Removing object data stored on Archive Nodes will simplify future upgrades. See link:../ilm/working-with-ilm-rules-and-ilm-policies.html[Working with ILM rules and ILM policies].