---
permalink: admin/changing-network-options-object-encryption.html
sidebar: sidebar
keywords: enable http, storage node connections
summary: 'You can encrypt stored objects if you want to ensure that data cannot be retrieved in a readable form if an object store is compromised.'
---
= Configure network and object options
:icons: font
:imagesdir: ../media/

[.lead]

You can configure network and object options to help secure the data when the data is retrieved in a readable form if an object store is compromised. By default, StorageGRID does not encrypt stored objects. You can use the Prevent Client Modification grid option to deny specific HTTP client operations.

== Stored object encryption
Stored object encryption enables the encryption of all object data as it is ingested through S3 or Swift. By default, stored objects are not encrypted but you can choose to encrypt objects using the AES‐128 or AES‐256 encryption algorithm. When you enable the setting, all newly ingested objects are encrypted but no change is made to existing stored objects. If you disable encryption, currently encrypted objects remain encrypted but newly ingested objects are not encrypted.

For more details on StorageGRID encryption methods, 

[NOTE]
====
If you change this setting, it will take about one minute for the new setting to be applied. The configured value is cached for performance and scaling.
====

The Stored object encryption setting applies only to S3 objects that have not been encrypted by bucket-level or object-level encryption.

For more details on StorageGRID encryption methods, see xref:../admin/reviewing-storagegrid-encryption-methods.html[Review StorageGRID encryption methods].

== Prevent client modification
Prevent Client Modification is a system wide setting. When the Prevent Client Modification option is selected, the following requests are denied:

* *S3 REST API*
 ** Delete Bucket requests
 ** Any requests to modify an existing object's data, user-defined metadata, or S3 object tagging
+

NOTE: This setting does not apply to buckets with versioning enabled. Versioning already prevents modifications to object data, user-defined metadata, and object tagging.

* *Swift REST API*
 ** Delete Container requests
 ** Requests to modify any existing object. For example, the following operations are denied: Put Overwrite, Delete, Metadata Update, and so on.

== Enable HTTP for Storage Node connections
Use HTTP for Storage Node connections only if S3 and Swift clients need to make HTTP connections directly to Storage Nodes. You do not need to complete this task for clients that only use HTTPS connections or for clients that connect to the Load Balancer service (because you can xref:../admin/configuring-load-balancer-endpoints.adoc[configure each load balancer endpoint] to use either HTTP or HTTPS).

See xref:summary-ip-addresses-and-ports-for-client-connections.adoc[Summary: IP addresses and ports for client connections] to learn which ports S3 and Swift clients use when connecting to Storage Nodes using HTTP or HTTPS.

.What you'll need
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have Root access permission.

.Steps

. Select *CONFIGURATION* > *Security settings* > *Network and objects*.
. For Stored object encryption, select *AES-128*, or *AES-256* to encrypt stored objects, or select *None* (default) if you do not want stored objects to be encrypted.
. For Network options, select *Prevent client modification* or *Enable HTTP for Storage Node connections* or both.
. To enable HTTP connections, select *Enable HTTP for Storage node connections*. 
+

NOTE: Be cautious when enabling HTTP for a production grid because requests will be sent unencrypted.
+

See the information on xref:../admin/configuring-load-balancer-endpoints.adoc[configuring load balancer endpoints] for more information.
+

See xref:../admin/summary-ip-addresses-and-ports-for-client-connections.adoc[IP addresses and ports for client connections] to learn which ports S3 and Swift clients use when connecting to Storage Nodes using HTTP or HTTPS.

(when you select HTTP here, the client has to use a completely different port number in the URL. If they don't know that, their requests will fail.)

. Select *Save*.