---
permalink: admin/changing-browser-session-timeout-interface.html
sidebar: sidebar
keywords: browser inactivity timeout, inactive users
summary: 'You can control whether Grid Manager and Tenant Manager users are signed out if they are inactive for more than a certain amount of time.'
---
= Change browser inactivity timeout
:icons: font
:imagesdir: ../media/

[.lead]
You can control whether Grid Manager and Tenant Manager users are signed out if they are inactive for more than a certain amount of time.

.What you'll need

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have Root access permission.

.About this task

The browser inactivity timeout defaults to 15 minutes. If a user's browser is not active for this amount of time, the user is signed out.

As required, you can increase or decrease the timeout period by setting the *Sign out inactive users after* option.

Browser inactivity timeout is also controlled by the following:

* A separate, non-configurable StorageGRID timer, which is included for system security. By default, each user's authentication token expires 16 hours after the user signs in. When a user's authentication expires, that user is automatically signed out, even if browser inactivity timeout is disabled or the value for the browser timeout has not been reached. To renew the token, the user must sign back in.

* Timeout settings for the identity provider, assuming single sign-on (SSO) is enabled for StorageGRID.
+
If SSO is enabled and a user's browser times out, the user must reenter their SSO credentials to access StorageGRID again. See link:configuring-sso.html[Configure single sign-on]. 

.Steps
. Select *CONFIGURATION* > *Security settings* > *Browser inactivity timeout*.
. In the *Sign out inactive users after* field, specify a browser timeout period between 60 seconds and 7 days.
+
You can specify the browser timeout period in seconds, minutes, hours, or days.

. Select *Save*. If a browser is inactive for the specified amount of time, the user is signed out of the Grid Manager or Tenant Manager.
+
The new setting does not affect currently signed in users. Users must sign in again or refresh their browsers for the new timeout setting to take effect.