---
permalink: admin/configuring-stored-object-compression.html
sidebar: sidebar
keywords: stored object compression, compress stored objects 
summary: 'You can configure stored object compression to reduce the size of objects stored in StorageGRID, so that objects consume less storage.'
---
= Configure stored object compression
:icons: font
:imagesdir: ../media/

[.lead]
You can enable stored object compression to reduce the size of objects stored in StorageGRID, so that objects consume less storage.

.What you'll need
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have specific access permissions.

.About this task
Stored object compression is disabled by default. If you enable compression, StorageGRID attempts to compress each object when saving it, using lossless compression.

NOTE: If you change this setting, it will take about one minute for the new setting to be applied. The configured value is cached for performance and scaling.

Before enabling compression, be aware of the following:

* You should not enable compression unless you know that the data being stored is compressible.
* Applications that save objects to StorageGRID might compress objects before saving them. If a client application has already compressed an object before saving it to StorageGRID, enabling Compress Stored Objects will not further reduce an object's size.
* Do not enable compression if you are using NetApp FabricPool with StorageGRID.
* If stored object compression is enabled, S3 and Swift client applications should avoid performing GET Object operations that specify a range of bytes be returned. These "`range read`" operations are inefficient because StorageGRID must effectively uncompress the objects to access the requested bytes. GET Object operations that request a small range of bytes from a very large object are especially inefficient; for example, it is inefficient to read a 10 MB range from a 50 GB compressed object.
+
If ranges are read from compressed objects, client requests can time out.
+
NOTE: If you need to compress objects and your client application must use range reads, increase the read timeout for the application.

.Steps

. From the top of the Grid Manager, select the help icon and select *API documentation*.
. Select *Go to private API documentation*.
+
NOTE: The StorageGRID API endpoints that are marked “Private” are subject to change without notice. StorageGRID private endpoints also ignore the API version of the request.

. In the *grid-config* section, select the following endpoint to determine the current setting for `objectCompression` (the default is `false`):
+
`GET ​/private​/grid-config`

. Select *Try it out*.

. Select *Execute*.

. As required, use the following endpoint to update the setting for `objectCompression`:
+
`PUT ​/private​/grid-config`
