---
permalink: admin/configuring-client-connections.html
sidebar: sidebar
keywords: s3 connection, swift connection, connect to storagegrid
summary: 'As a grid administrator, you manage the configuration options that control how S3 and Swift tenants can connect client applications to your StorageGRID system to store and retrieve data. There are a number of different options to meet different client and tenant requirements.'
---
= About S3 and Swift client connections
:icons: font
:imagesdir: ../media/

[.lead]
As a grid administrator, you manage the configuration options that control how S3 and Swift tenants can connect client applications to your StorageGRID system to store and retrieve data. There are a number of different options to meet different client and tenant requirements.

Client applications can store or retrieve objects by connecting to any of the following:

* The Load Balancer service on Admin Nodes or Gateway Nodes, or optionally, the virtual IP address of a high availability (HA) group of Admin Nodes or Gateway Nodes
* Storage Nodes, with or without an external load balancer

You can optionally configure the following features on your StorageGRID system:

* *VLAN interfaces*: You can create virtual LAN (VLAN) interfaces on Admin Nodes and Gateway Nodes to isolate and partition client and tenant traffic for security, flexibility, and performance. After creating a VLAN interface, you add it to a high availability (HA) group.

* *High availability groups*: You can create an HA group of the interfaces for Gateway Nodes or Admin Nodes to create an active-backup configuration, or you can use round-robin DNS or a third-party load balancer and multiple HA groups to achieve an active-active configuration. Client connections are made using the virtual IP addresses of HA groups.

* *Load balancer endpoints*: You can enable clients to use the Load Balancer service by creating load balancer endpoints for client connections. When creating a load balancer endpoint, you specify a port number, whether the endpoint accepts HTTP or HTTPS connections, the type of client (S3 or Swift) that will use the endpoint, an optional list of allowed or blocked tenant accounts, and the certificate to be used for HTTPS connections (if applicable).

* *Untrusted Client Network*: You can make the Client Network more secure by configuring it as untrusted. When the Client Network is untrusted, clients can only connect using load balancer endpoints.


You can also enable the use of HTTP for clients that connect to StorageGRID directly to Storage Nodes and you can configure S3 API endpoint domain names for S3 clients.
