---
permalink: admin/creating-traffic-classification-policies-overhaul.html
sidebar: sidebar
keywords: traffic classification, network traffic, traffic limits, policy
summary: 'You create traffic classification policies if you want to monitor, and optionally limit, network traffic by bucket, tenant, IP subnet, or load balancer endpoint. Optionally, you can set limits for a policy based on bandwidth, the number of concurrent requests, or the request rate.'
---
= Create traffic classification policies
:icons: font
:imagesdir: ../media/

[.lead]
You create traffic classification policies if you want to monitor, and optionally limit network traffic by bucket, bucket Regex, CIDR, load balancer endpoint, or tenant. Optionally, you can set limits for a policy based on bandwidth, the number of concurrent requests, or the request rate.

.What you'll need

* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the Root access permission.
* You have created any load balancer endpoints you want to match.
* You have created any tenants you want to match.

.Steps

. Select *CONFIGURATION* > *Network* > *Traffic classification*.
+
The Traffic Classification Policies page appears.
+

. Select *Create*.
+
The Create Traffic Classification Policy wizard appears.
+

. Enter a descriptive name that can be recognized and a description(optional) for the policy and select *Continue*.
+
For example, describe what this traffic classification policy applies to and what it will limit.
+

. Select *Add rule* or select *Add* from the table and select the following details to create a matching rule to the policy. Any policy that you create should have at least one matching rule.
+

[cols="1a,2a" options="header"]
|===
// header row
|Entities |Description

|Type
|Select the type of traffic that the matching rule applies to. Traffic types are Bucket, bucket Regex, CIDR, load balancer endpoint, tenant.

|Match value
|Enter the value that matches for the selected Type.

|Inverse match
|Select an Inverse match rule if you want to exclude traffic for a selected entity for a policy.

If you want to match all network traffic _except_ traffic consistent with the Type and Match Value just defined, select the *Inverse* check box. Otherwise, leave the check box unselected.

For example, if you want this policy to apply to all but one of the load balancer endpoints, specify the load balancer endpoint to be excluded, and select *Inverse*.


// table end
|===
+

. Select *Add a limit* to add one or more limits to control the network traffic matched by a rule. This is an optional step. 
After you select *Add a limit*, select the values for the following fields:
+

[cols="1a,2a" options="header"]
|===
// header row
|Entities |Description

|Type
|The type of limit you want to apply to the network traffic matched by the rule. For example, you can limit bandwidth or request rate.
Hint: Aggregate rate limits are in use. Per-request rate limits are not available.

|Applies to
|Whether this limit applies to client read requests (GET or HEAD) or write requests (PUT, POST, or DELETE).

|Value
|The value that network traffic will be limited to, based on the Unit you select. For example, enter 10 and select MiBs to prevent the network traffic matched by this rule from exceeding 10 MiBs.

|Unit
|The unit that describes the value you entered.

// table end
|===
+

. Select *Save and continue*. You must make sure that you read and review the Traffic classification policy before saving. Use *Previous* button to go back and make changes as required.