---
permalink: admin/deleting-traffic-classification-policy-overhaul.html
sidebar: sidebar
keywords: delete traffic classification policy
summary: 'If you no longer need a traffic classification policy, you can delete it.'
---
= Delete a traffic classification policy
:icons: font
:imagesdir: ../media/

[.lead]
You can delete a traffic classification policy if you no longer need it. Make sure you delete the right policy because a policy cannot be retrieved when deleted.

.What you'll need

* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the Root access permission.

.Steps

. Select *CONFIGURATION* > *Network* > *Traffic classification*.
+
The Traffic classification policies page appears with the existing policies listed in a table.
+
. Select the policy name you want to delete.
. From the *Actions*, select *Remove*.
+
You can also delete a policy by opening the policy details sidebar and selecting *Remove*. 
+
A Warning dialog box appears.
+
. Select *Yes* to confirm that you want to delete the policy.
+
The policy is successfully deleted.