---
permalink: admin/deleting-traffic-classification-policy.html
sidebar: sidebar
keywords: delete traffic classification policy
summary: 'If you no longer need a traffic classification policy, you can delete it.'
---
= Delete a traffic classification policy
:icons: font
:imagesdir: ../media/

[.lead]
You can delete a traffic classification policy if you no longer need it. Make sure you delete the right policy because a policy cannot be retrieved when deleted.

.What you'll need

* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the Root access permission.

.Steps

. Select *CONFIGURATION* > *Network* > *Traffic classification*.
+
The Traffic classification policies page appears with the existing policies listed in a table.
+
. Select the policy name you want to delete.
. Delete a policy in either of the following ways:
+

** Traffic classification policy page
... Select the check box for the policy.
... Select *Actions* > *Remove*.
+

** Policy details sidebar
... Select the policy name.
... Select the *Remove* button beside the policy name.
+

A Warning dialog box appears.
+
. Select *Yes* to confirm that you want to delete the policy.
+
The policy is deleted.