---
permalink: admin/editing-traffic-classification-policy.html
sidebar: sidebar
keywords: edit traffic classification policy
summary: 'You can edit a traffic classification policy to change its name or description, or to create, edit, or delete any rules or limits for the policy.'
---
= Edit traffic classification policy
:icons: font
:imagesdir: ../media/

[.lead]
You can edit a traffic classification policy to change its name or description, or to create, edit, or delete any rules or limits for the policy.

.What you'll need

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the Root access permission.

.Steps

. Select *CONFIGURATION* > *Network* > *Traffic classification*.
+
The Traffic classification policies page appears and the existing policies are listed in a table.

. Select the policy to edit:
+
[role="tabbed-block"]
====

.Traffic classification policy page
--

.. Select the check box for the policy.
.. Select *Actions* > *Edit*.

--
.Policy details page
--

.. Select the policy name.
.. Select the *Edit* button beside the policy name.
--
====

. For the Enter policy name step, optionally edit the policy name or description, and select *Continue*.

. For the Add matching rules step, optionally add a rule or edit the *Type* and *Match value* of the existing rule, and select *Continue*. For details, see the instructions for link:../admin/creating-traffic-classification-policies.html[creating traffic classification policies].

. For the Set limits step, optionally add, edit, or delete a limit, and select *Continue*. For details, see the instructions for link:../admin/creating-traffic-classification-policies.html[creating traffic classification policies].

. Review the updated policy, and select *Save and continue*.
+
The changes you made to the policy are saved, and network traffic is now handled according to the traffic classification policies. You can view traffic charts and verify that the polices are enforcing the traffic limits you expect.