---
permalink: admin/editing-traffic-classification-policy.html
sidebar: sidebar
keywords: edit traffic classification policy
summary: 'You can edit a traffic classification policy to change its name or description, or to create, edit, or delete any rules or limits for the policy.'
---
= Edit traffic classification policy
:icons: font
:imagesdir: ../media/

[.lead]
You can edit a traffic classification policy to change its name or description, or to create, edit, or delete any rules or limits for the policy.

.What you'll need

* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the Root access permission.

.Steps

. Select *CONFIGURATION* > *Network* > *Traffic classification*.
+
The Traffic Classification Policies page appears, and the existing policies are listed in the table.

. Select the policy you want to edit.
. Select *Edit*.
+
The Edit traffic classification policy wizard appears.

+
.. Edit a traffic classification policy name or description in the Enter policy name step and select *Continue*.
.. Add a rule or edit the *Type* and *Match value* of the existing rule in the Add matching rules step and select *Continue*. You can also follow the instructions mentioned in adding a rule.
.. Optionally, you can add, edit, or delete a limit in the Set limits step and select *Continue*. You can also follow the instructions mentioned in adding a rule.
.. Select *Save and continue*. You must make sure that you read and review the updated Traffic classification policy before saving. 

The changes you made to the policy are saved, and network traffic is now handled according to the traffic classification policies. You can view traffic charts and verify that the polices are enforcing the traffic limits you expect.
