---
permalink: admin/grid-federation-troubleshoot.html
sidebar: sidebar
keywords: grid federation, troubleshoot
summary: 'You might need to troubleshoot alerts related to grid federation as well as any permanent errors that occur when tenant accounts use a grid federation connection to clone account data between StorageGRID systems or cross-grid replication to copy objects between buckets.'
---
= Troubleshoot grid federation errors
:icons: font
:imagesdir: ../media/

[.lead]
You might need to troubleshoot alerts related to grid federation as well as any permanent errors that occur when tenant accounts use a grid federation connection to clone account data between StorageGRID systems or cross-grid replication to copy objects between buckets.

// doc task: https://jira.vtc.eng.netapp.com/browse/SGWS-21308

// doc task: https://jira.vtc.eng.netapp.com/browse/SGWS-22990

// doc task: https://jira.vtc.eng.netapp.com/browse/SGWS-22991

// see https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-troubleshoot.html

After making any changes to resolve a connection issue, test the connection to ensure that its connection status is *Connected*. For instructions, see link:grid-federation-manage-connection.html[Manage grid federation connections].

== Troubleshoot account clone errors

=== Unable to sign in to a cloned tenant account

For security reasons, when a tenant account is cloned from the tenant's source grid to the tenant's destination grid, the password you set for the tenant's local root user is not cloned. Similarly, when a tenant creates local users on its source grid, the local user passwords are not cloned to the destination grid.

Before the root user can sign in to the tenant's destination grid, a grid administrator for that grid must first link:changing-password-for-tenant-local-root-user.html[change the password for the local root user].

Before a cloned local user can sign in to the tenant's destination grid, the root user for the cloned tenant must add a password for the user on the destination grid. For instructions, see link:../tenant/managing-local-users.html[Manage local users].

== Troubleshoot cross-grid replication errors

=== Cross-grid replication permanent failure alert

The *Cross-grid replication permanent failure* alert indicates that tenant objects can't be replicated between the buckets on two grids for a reason that requires user intervention to resolve. This alert is typically caused by a change to either the source or the destination bucket. 

To troubleshoot this alert, follow these steps:

. Sign into the grid where the alert was triggered.
. Go to *CONFIGURATION* > *System* > *Grid federation*, and locate the connection name listed in the alert.

. On the Permitted tenants tab, look at the *Last error* column to determine which tenant accounts have errors.

. To learn more about the failure, review the <<cross-grid-metrics,cross-grid replication metrics>>.

. For each affected tenant account:

.. Select the tenant name to display the tenant details page.
.. Confirm that the tenant has not exceeded its quota for this grid.
.. As required, increase the quota to allow new objects to be saved.

.. Repeat these steps for the corresponding tenant account on the other grid in the connection.
	
. For each affected tenant, sign in to Tenant Manager on both grids, so you can compare the list of buckets.

. For each bucket that has cross-grid replication enabled, confirm the following:

* There is a corresponding bucket for the same tenant on the other grid (must use the exact name). 
* Both buckets have object versioning enabled (versioning cannot be suspended on either grid).
* Both buckets have S3 Object Lock disabled. 
* Neither bucket is in the *Deleting objects: read-only* state.

. Confirm that the issue was resolved, you can review the cross-grid replication metrics or perform these steps:

.. Go back to the Grid Federation page.
.. Select the affected tenant, and select *Clear Error* in the *Last error* column.
+
The error message no longer appears. However, if the issue was not resolved (or if a different error is encountered), the error message will be shown in the *Last error* column after new objects are saved to one of the tenant's buckets.

.. Ingest new objects in to the bucket, and confirm that the error does not reappear. 
+
NOTE: It might take up to a day for the alert to clear after it is resolved.

=== Cross-grid replication resource unavailable alert

The *Cross-grid replication resource unavailable* alert indicates that cross-grid replication requests are pending because a resource is unavailable. For example, there might be a network error.

To troubleshoot this alert, follow these steps:

. Monitor the alert to see if the issue resolves on its own.

. If the issue persists, determine if either grid has a *Grid federation connection failure* alert for the same connection or an *Unable to communicate with node* alert for a node. This alert might be resolved when you resolve those alerts.

. To learn more about the failure, review the <<cross-grid-metrics,cross-grid replication metrics>>. 

. If you cannot resolve the alert, contact technical support.

Cross-grid replication will proceed as normal once the issue is resolved.

== [[cross-grid-metrics]]Use cross-grid replication metrics

You can use the Cross-Grid Replication dashboard in Grafana to view metrics about cross-grid replication operations on your grid.

. From the Grid Manager, go to *SUPPORT* > *Tools* > *Metrics*.
+
NOTE: The tools available on the Metrics page are intended for use by technical support. Some features and menu items within these tools are intentionally non-functional and are subject to change. See the list of xref:../monitor/commonly-used-prometheus-metrics.adoc[commonly used Prometheus metrics].

. In the Grafana section of the page, select *Cross Grid Replication*. 

For detailed instructions, see xref:../monitor/reviewing-support-metrics.adoc[Review support metrics].

//. To retry replication of objects that failed to replicate, see <cgr troubleshooting topic link implemented in SGWS-22825>  //  

