---
permalink: admin/grid-federation-overview.html
sidebar: sidebar
keywords: grid federation, cross-grid replication, account sync, cgr, disaster recovery
summary: 'You can use grid federation to replicate tenants and their objects between two StorageGRID systems for disaster recovery.'
---
= Use grid federation: Overview
:icons: font
:imagesdir: ../media/

[.lead]
You can use grid federation to replicate tenants and their objects between two StorageGRID systems for disaster recovery.

== What is a grid federation connection?

A grid federation connection is a trusted and secure connection between high availability (HA) groups in two discrete StorageGRID systems. A grid federation connection is a prerequisite for both account sync and cross-grid replication.


== What is account sync?

Account sync is the automatic replication of tenant accounts and tenant details between two StorageGRID systems. 

* *Account sync for tenants*: To enable account sync for a tenant, a grid admin creates an S3 tenant account on either grid in a grid federation connection. When creating the tenant, the admin assigns a permission that allows the tenant to use the grid federation connection. Saving a tenant that is allowed to use both grids automatically creates the same tenant and the same root user on both grids.

* *Account sync for tenant details*:, the tenant creates a new S3 access key, group, or user. If account sync is enabled for the item, the new key, group, or user is automatically copied to the tenant on the other grid. Any subsequent changes to the item are also sync'd.

Account sync is required for cross-grid replication.


=== What is cross-grid replication?

After the grid administrator establishes a grid federation connection between two grids and creates a new S3 tenant with permission to use that connection, the tenant can create new S3 buckets on each grid and optionally enable cross-grid replication for those buckets. If cross-grid replication is enabled, all operations to add or remove objects to the bucket are automatically replicated on the other grid.


== What are the requirements?

// List of considerations and requirements here



== What happens if a grid fails?



