---
permalink: admin/grid-federation-create-connection.html
sidebar: sidebar
keywords: grid federation, create connection, configure connection
summary: 'You can create a grid federation connection between two StorageGRID systems to replicate the object data in selected tenant buckets between grids (_cross-grid replication_).'
---
= Create grid federation connections
:icons: font
:imagesdir: ../media/

[.lead]
You can create a grid federation connection between two StorageGRID systems to replicate the object data in selected tenant buckets between grids (_cross-grid replication_).

Creating a grid federation connection is a two-step process. You start the configuration on one grid and complete it on the other grid. You can start the configuration on either grid.

. To start the configuration, a grid administrator signs in to the primary Admin Node on the first grid to enter connection details and download a verification file. 

. To complete the configuration, a grid administrator signs in to the primary Admin Node on the second grid to upload the verification file and save and test the connection. 

.What you'll need

* You have reviewed the xref:grid-federation-overview.adoc[considerations and requirements] for configuring grid federation connections. 
* If you plan to use fully qualified domain names (FQDNs) for each grid instead of IP or VIP addresses, you know which names to use. The DNS servers for each grid have the appropriate entries.
* You are using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* Whoever starts the configuration has Root access permission and the provisioning passphrase for the first grid.
* Whoever completes the configuration has Root access permission and the provisioning passphrase for the second grid. 

== [[start_configuration]]Start the configuration

To start the configuration, enter connection details and download the verification file.

. Sign in to the Grid Manager from the primary Admin Node on either grid.

. Select *CONFIGURATION* > *System* > *Grid federation*.

. Select *Add connection* > *Start configuration*.

. Enter details for the connection.
+
[cols="1a,2a" options="header"]
|===
| Field| Description

|Connection name
|A unique name to help you recognize this connection, for example, "`Grid 1-Grid 2.`"

|FQDN or IP for this grid
|One of the following:

* The FQDN of the grid you are currently signed into
* A VIP address of an HA group on this grid
* An IP address of an Admin Node or Gateway Node on this grid

|Port
|The port you want to use for this connection. You can enter any unused port number from 23000 to 23999.

Both grids in this connection will use the same port. You must ensure that no node in either grid uses this port for other connections.

|Certificate valid days (this grid)
|The number of days you want the security certificates for this grid in the connection to be valid. The default value is 730 days (2 years), but you can enter any value from 1 to 762 days.

StorageGRID automatically generates client and server certificates for each grid when you save the connection.

|Provisioning passphrase for this grid
|The provisioning passphrase for the grid you are signed in to.

|FQDN or IP for the other grid
|One of the following:

* The FQDN of the grid you want to connect to
* A VIP address of an HA group on the other grid
* An IP address of an Admin Node or Gateway Node on the other grid

|===

. Select *Save and continue*.

. For the Download verification file step, select *Download verification file*.
+
After the connection is successfully completed on the other grid, you can no longer download the verification file from this grid.

. When the green checkmark appears, locate the downloaded file (`_connection-name_.grid-federation`), and save it to a safe location.
+
[IMPORTANT]
The verification file contains secrets and must be securely stored and transmitted.

. Select *Close* to return to the Grid federation page. 

. Confirm that the new connection is shown and that its *Connection status* is *Waiting to connect*.

. Provide the `_connection-name_.grid-federation` file to the grid admin for the other grid.

== Complete the connection

Perform these steps on the StorageGRID system you are connecting to (the other grid).

. Sign in to the Grid Manager from the primary Admin Node.

. Select *CONFIGURATION* > *System* > *Grid federation*.

. Select *Add connection* > *Upload verification file*. 

. Select *Upload verification file*. Then, browse to and select the file that was downloaded from the first grid (`_connection-name_.grid-federation`).
+
The details for the connection are shown.

. Optionally, enter a different number of valid days for the security certificates for this grid. *Certificate valid days* defaults to the value you entered on the first grid, but each grid can use different expiration dates.
+
In general, use the same number of days for the certificates on both sides of the connection. If the certificates on either end of the connection expire, the connection will stop working and data will no longer be replicated between grids. 

. Enter the provisioning passphrase for the grid you are currently signed in to.

. Select *Save and test*.
+
If the connection can be established, a success message appears. Otherwise, an error message appears. Review the message and address any issues.

. From the Grid federation page, confirm that the new connection is shown and that its *Connection status* is *Connected*.

. After the connection has been established, securely delete all copies of the verification file.
+
[IMPORTANT]
This file contains secrets and must be deleted after the connection is established. If you edit this connection, a new verification file will be created. The original file cannot be reused.
