---
permalink: admin/kms-removing.html
sidebar: sidebar
keywords: remove kms, remove key management server
summary: 'You might want to remove a key management server in some cases. For example, you might want to remove a site-specific KMS if you have decommissioned the site.'
---
= Remove a key management server (KMS)
:icons: font
:imagesdir: ../media/

[.lead]
You might want to remove a key management server in some cases. For example, you might want to remove a site-specific KMS if you have decommissioned the site.

.Before you begin

* You have reviewed the link:kms-considerations-and-requirements.html[considerations and requirements for using a key management server].

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the Root access permission.

.About this task

You can remove a KMS in these cases:

* You can remove a site-specific KMS if the site has been decommissioned or if the site includes no appliance nodes with node encryption enabled.
* You can remove the default KMS if a site-specific KMS already exists for each site that has appliance nodes with node encryption enabled.

.Steps

. Select *CONFIGURATION* > *Security* > *Key management server*.
+
The Key management server page appears and shows all key management servers that have been configured.


. Select the KMS you want to remove, and select *Actions* > *Remove*.
+
You can also remove a KMS by selecting the KMS name in the table and selecting *Remove* from the KMS details page.

. Confirm the following is true:
* You are removing a site-specific KMS for a site that has no appliance node with node encryption enabled.
* You are removing the default KMS, but a site-specific KMS already exists for each site with node encryption. 

. Select *Yes*.
+
The KMS configuration is removed.
