---
permalink: admin/manage-firewall-controls.html
sidebar: sidebar
keywords: firewall controls, untrusted client network, privileged IP address, manage external access
summary: 'StorageGRID includes a firewall on each node that enhances the security of your grid by enabling you to customize access to the Grid Network, Admin Network, and Client Network.'
---


= Manage firewall controls
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID includes an internal firewall on each node that enhances the security of your grid by enabling you to control access to the Grid Network, Admin Network, and Client Network. You should use the firewall to prevent network access on all ports except those necessary for your specific grid deployment. The configuration changes you make on the *Firewall control* page are deployed to each node. 

Use the three tabs on the *Firewall control* page to: 

* Manage external network access to your nodes.
* Create a list of privileged IP addresses that can access ports that would otherwise be blocked.
* Manage an untrusted Client Network.

The settings you make one one tab might affect the settings you make on another tab. In general, the Untrusted Client Network settings override Privileged address list settings, which in turn override the settings on the Manage external access tab. Be sure to check the settings on all tabs to ensure your network behaves in the way you expect. 

To configure firewall controls, see xref:../admin/configure-firewall-controls.adoc[Configure firewall controls].

For more information on external firewalls and network security, see xref:../admin/controlling-access-through-firewalls.adoc[Control access through firewalls].

== Manage external access and privileged IP addresses tabs: overview
You can enhance the security of your grid by limiting the external network access of the ports on your grid nodes. The Manage external access tab on the *Firewall control* page enables you to block access to selected ports or all configurable ports. The Privileged IP address tab enables you to register one or more IP addresses that are granted access to grid ports that would otherwise be blocked. 

NOTE: Privileged IPs do not have internal grid access by default. 

=== Example 1: Limit access to the Grid Manager and Tenant Manager
Suppose you want to limit access to the Grid Manager and Tenant manager for security reasons. You could use the Manage external access tab to block port 443, but allow access to the Grid Manager only via port 8443 and the Tenant Manager only via port 9443.

You could further limit access to the Grid Manager by blocking both ports 443 and 8443, but you would then have to use the privileged IP address list to add the address of the system that you use to connect to the Grid Manager. 

=== Example 2: Use a jump host for maintenance tasks

You might want to use a jump host (a security hardened host) for network administration. For example, you could use the Manage external access tab to block all ports and then use the Privileged IP address tab to grant the jump host access to an Admin node so you can perform maintenance tasks securely. 

=== Example 3: Lock down sensitive ports
Suppose you want to lock down sensitive ports and the service on that port (for example, SSH on port 22). You can use the Manage external access tab in conjunction with the Privileged address list tab so that only hosts on the privileged address list can access the service. All other hosts will be denied access to the service no matter what interface the request comes from.

=== Example 4: Disable access to unused services
The Manage external access tab may also be used to disable at a network level some services that you do not intend to use. For example you might choose to block ports 18083 and 18085 because you have no intention of providing Swift access.

== Untrusted Client Networks tab: overview

If you are using a Client Network, you can help secure StorageGRID from hostile attacks by accepting inbound client traffic only on explicitly configured endpoints.

By default, the Client Network on each grid node is _trusted_. That is, by default, StorageGRID trusts inbound connections to each grid node on all available external ports (see the information about external communications in the xref:../network/index.adoc[Networking guidelines]).

You can reduce the threat of hostile attacks on your StorageGRID system by specifying that the Client Network on each node be _untrusted_. If a node's Client Network is untrusted, the node only accepts inbound connections on ports explicitly configured as load balancer endpoints and any additional ports you designate using the Untrusted Client Network tab on the Firewall Controls page. See xref:../admin/configuring-load-balancer-endpoints.adoc[Configure load balancer endpoints] and xref:../admin/configure-firewall-controls.adoc[Configure firewall controls].

=== Example 1: Gateway Node only accepts HTTPS S3 requests

Suppose you want a Gateway Node to refuse all inbound traffic on the Client Network except for HTTPS S3 requests. You would perform these general steps:

. From the Load Balancer Endpoints page, configure a load balancer endpoint for S3 over HTTPS on port 443.
. From the *Firewall controls* page, select Untrusted to specify that the Client Network on the Gateway Node is untrusted.

After you save your configuration, all inbound traffic on the Gateway Node's Client Network is dropped except for HTTPS S3 requests on port 443 and ICMP echo (ping) requests.

=== Example 2: Storage Node sends S3 platform services requests

Suppose you want to enable outbound S3 platform service traffic from a Storage Node, but you want to prevent any inbound connections to that Storage Node on the Client Network. You would perform this general step:

* From the Untrusted Client Networks tab of the *Firewall controls* page, indicate that the Client Network on the Storage Node is untrusted.

After you save your configuration, the Storage Node no longer accepts any incoming traffic on the Client Network, but it continues to allow outbound requests to Amazon Web Services.

