---
permalink: admin/manage-firewall-controls.html
sidebar: sidebar
keywords: firewall controls, untrusted client network, privileged IP address, manage external access
summary: 'StorageGRID includes a firewall on each node that enhances the security of your grid by enabling you to customize access to the Grid Network, Admin Network, and Client Network.'
---


= Manage firewall controls
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID includes an internal firewall on each node that enhances the security of your grid by enabling you to control access to the Grid Network, Admin Network, and Client Network. You should use the firewall to prevent network access on all ports except those necessary for your specific grid deployment. The configuration changes you make on the *Firewall control* page are deployed to each node. 

Use the three tabs on the *Firewall control* page to: 

* Manage external network access to your nodes.
* Create a list of privileged IP addresses that can access ports that would otherwise be blocked.
* Manage an untrusted Client Network.

These three tabs can be used together to customize the amount of access you need for your grid. The settings you make one one tab might affect the settings you make on another tab. In general, the Untrusted Client Network settings override Privileged address list settings, which in turn override the settings on the Manage external access tab. Be sure to check the settings on all tabs to ensure your network behaves in the way you expect. 

To configure firewall controls, see xref:../admin/configure-firewall-controls.adoc[Configure firewall controls].

For more information on external firewalls and network security, see xref:../admin/controlling-access-through-firewalls.adoc[Control access through firewalls].

== Manage external access and Privileged IP addresses tabs: overview
You can enhance the security of your grid by limiting the external network access of the ports on your grid nodes. The Manage external access tab on the *Firewall control* page enables you to block access to selected ports or all configurable ports. The Privileged IP address tab enables you to register one or more IP addresses that are granted access to grid ports that would otherwise be blocked. These two tabs often can be used together to customize the exact network access you need to allow for your grid.

NOTE: Privileged IPs do not have internal grid access by default. 

=== Example 1: Limit access to the Grid Manager and Tenant Manager
Suppose you want to limit access to the Grid Manager and Tenant manager for security reasons. You could use these general steps: 

. Use the toggle on the Manage external access tab to block port 443.
. Use the toggle on the Manage external access tab to allow access to port 8443.
. Use the toggle on the Manage external access tab to allow access to port 9443. 

After you save your configuration, hosts will not be able to access port 443, but they can still access the Grid Manager via port 8443 and the Tenant manger via port 9443.

You could further limit access to the Grid Manager by performing the following general steps: 

[start=1]
. Use the Privileged IP address tab to add the address of the system that you use to connect to the Grid Manager.
. Use the toggle on the Manage external access tab to block port 443.
. Use the toggle on the Manage external access tab to block port 8443.

IMPORTANT: You must be sure to add the privileged IP address before you block both ports 443 and 8443. Otherwise, you will lose access to the Grid Manager. 

After you save your configuration, the Grid Manager cannot be accessed by any host except the system you use for administrative tasks. 

=== Example 2: Use a jump host for maintenance tasks

You might want to use a jump host (a security hardened host) for network administration. For example, you could use these general steps:

. Use the Manage external access tab to block all ports
. Use the Privileged IP address tab to add the IP address of the jump host. 

After you save your configuration, all external ports on the Admin Node in your grid will be blocked for all hosts except the jump host. You can then use the jump host to perform maintenance tasks on your grid more securely. 

=== Example 3: Lock down sensitive ports
Suppose you want to lock down sensitive ports and the service on that port (for example, SSH on port 22). You could use the following general steps: 

. Use the Manage external access tab to block all ports. 
. Use the Privileged IP address tab to grant access only to the hosts that need access to the service.

After you save your configuration, port 22 and SSH service will be available to hosts on the privileged IP address list. All other hosts will be denied access to the service no matter what interface the request comes from.

=== Example 4: Disable access to unused services
You could disable at a network level some services that you do not intend to use. For example if you have not intention of providing Swift access, you could perform the following general steps: 

. Use the toggle on the Manage external access tab to block port 18083. 
. Use the toggle on the Manage external access tab to block port 18085.

After you save your configuration, the Storage Node no longer allows Swift connectivity to Amazon Web Services, but continues to allow access to other services on unblocked ports.

== Untrusted Client Networks tab: overview

If you are using a Client Network, you can help secure StorageGRID from hostile attacks by accepting inbound client traffic only on explicitly configured endpoints.

By default, the Client Network on each grid node is _trusted_. That is, by default, StorageGRID trusts inbound connections to each grid node on all available external ports (see the information about external communications in the xref:../network/index.adoc[Networking guidelines]).

You can reduce the threat of hostile attacks on your StorageGRID system by specifying that the Client Network on each node be _untrusted_. If a node's Client Network is untrusted, the node only accepts inbound connections on ports explicitly configured as load balancer endpoints and any additional ports you designate using the Untrusted Client Network tab on the Firewall Controls page. See xref:../admin/configuring-load-balancer-endpoints.adoc[Configure load balancer endpoints] and xref:../admin/configure-firewall-controls.adoc[Configure firewall controls].

=== Example 1: Gateway Node only accepts HTTPS S3 requests

Suppose you want a Gateway Node to refuse all inbound traffic on the Client Network except for HTTPS S3 requests. You would perform these general steps:

. From the Load Balancer Endpoints page, configure a load balancer endpoint for S3 over HTTPS on port 443.
. From the *Firewall controls* page, select Untrusted to specify that the Client Network on the Gateway Node is untrusted.

After you save your configuration, all inbound traffic on the Gateway Node's Client Network is dropped except for HTTPS S3 requests on port 443 and ICMP echo (ping) requests.

=== Example 2: Storage Node sends S3 platform services requests

Suppose you want to enable outbound S3 platform service traffic from a Storage Node, but you want to prevent any inbound connections to that Storage Node on the Client Network. You would perform this general step:

* From the Untrusted Client Networks tab of the *Firewall controls* page, indicate that the Client Network on the Storage Node is untrusted.

After you save your configuration, the Storage Node no longer accepts any incoming traffic on the Client Network, but it continues to allow outbound requests to Amazon Web Services.

