---
permalink: admin/managing-tenants.html
sidebar: sidebar
keywords: manage tenants, tenant account, what is a tenant
summary: 'As a grid administrator, you create and manage the tenant accounts that S3 and Swift clients use to store and retrieve objects, monitor storage usage, and manage the actions that clients are able to perform using your StorageGRID system.'
---
= Manage tenants: Overview
:icons: font
:imagesdir: ../media/

[.lead]
As a grid administrator, you create and manage the tenant accounts that S3 and Swift clients use to store and retrieve objects, monitor storage usage, and manage the actions that clients are able to perform using your StorageGRID system.

== What are tenant accounts?

Tenant accounts allow client applications that use the Simple Storage Service (S3) REST API or the Swift REST API to store and retrieve objects on StorageGRID.

Each tenant account supports the use of either the S3 or the Swift client protocol, which you specify when you create the account. Each tenant account has its own account ID, authorized groups and users, buckets or containers, and objects.

Optionally, you can create additional tenant accounts if you want to segregate the objects stored on your system by different entities. For example, you might set up multiple tenant accounts in either of these use cases:

* *Enterprise use case:* If you are administering a StorageGRID system in an enterprise application, you might want to segregate the grid's object storage by the different departments in your organization. In this case, you could create tenant accounts for the Marketing department, the Customer Support department, the Human Resources department, and so on.
+
NOTE: If you use the S3 client protocol, you can use S3 buckets and bucket policies to segregate objects between the departments in an enterprise. You do not need to use tenant accounts. See instructions for implementing xref:../s3/bucket-and-group-access-policies.adoc[S3 buckets and bucket policies] for more information.

* *Service provider use case:* If you are administering a StorageGRID system as a service provider, you can segregate the grid's object storage by the different entities that will lease the storage on your grid. In this case, you would create tenant accounts for Company A, Company B, Company C, and so on.

For more information, see xref:../tenant/index.adoc[Use a tenant account].

== How do I create a tenant account?

When you create a tenant account, you specify the following information:

* Tenant name and description

* Client protocol for the tenant account (S3 or Swift)

* Optionally, a storage quota for the account, which is the maximum amount of storage available for the tenant's objects. If the quota is exceeded, the tenant cannot create new objects.
+
NOTE: A tenant's storage quota represents a logical amount (object size), not a physical amount (size on disk).

* Any special permissions for the tenant account, including whether the tenant account can configure its own identity source, use platform services with S3 buckets, use S3 Select, or use a grid federation connection for account clone and cross-grid replication.

* The root user for the account, which might be a local root user or a federated group with Root access permission.


== What is Tenant Manager used for?

After you create the tenant account, tenant users can sign in to the Tenant Manager to perform tasks such as the following:

* Set up identity federation (unless the identity source is shared with the grid) and create local groups and users
* Monitor storage usage
* Manage S3 access keys
* Create and manage S3 buckets, including buckets with S3 Object Lock enabled
* Use S3 platform services 
* Use S3 Select 
* Use a grid federation connection for account clone and cross-grid replication 

IMPORTANT: S3 tenant users can create and manage S3 access key and buckets with the Tenant Manager, but they must use an S3 client application to ingest and manage objects.

IMPORTANT: Swift users must have the Root access permission to access the Tenant Manager. However, the Root access permission does not allow users to authenticate into the Swift REST API to create containers and ingest objects. Users must have the Swift Administrator permission to authenticate into the Swift REST API.
