---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html
sidebar: sidebar
keywords: ip addresses for client, how to connect to storagegrid, ports, vip
summary: 'Client applications can connect to StorageGRID using the IP address of a grid node and the port number of a service on that node. If high availability \(HA\) groups are configured, client applications can connect using the virtual IP address of the HA group.'
---
= Summary: IP addresses and ports for client connections
:icons: font
:imagesdir: ../media/

[.lead]
Client applications can connect to StorageGRID using the IP address of a grid node and the port number of a service on that node. If high availability (HA) groups are configured, client applications can connect using the virtual IP address of the HA group.

This table summarizes the different ways that clients can connect to StorageGRID and the IP addresses and ports that are used for each type of connection. The instructions describe how to find this information in the Grid Manager if load balancer endpoints and high availability (HA) groups are already configured.

[cols="1a,1a,1a,1a" options="header"]
|===
| Where connection is made| Service that client connects to| IP address| Port

|HA group
|Load Balancer
|Virtual IP address of an HA group
|Load balancer endpoint port

|Admin Node
|Load Balancer
|IP address of the Admin Node
|Load balancer endpoint port

|Gateway Node
|Load Balancer
|IP address of the Gateway Node
|Load balancer endpoint port

|Storage Node
|LDR
|IP address of Storage Node
|Default S3 ports:

* HTTPS: 18082
* HTTP: 18084

Default Swift ports:

* HTTPS: 18083
* HTTP:18085

|===

== Example URLs

To connect a client application to the Load Balancer endpoint of an HA group of Gateway Nodes, use a URL structured as shown below:

`https://_VIP-of-HA-group:LB-endpoint-port_`

For example, if the virtual IP address of the HA group is 192.0.2.5 and the port number of the load balancer endpoint is 10443, then an application could use the following URL to connect to StorageGRID:

`\https://192.0.2.5:10443`

Optionally, you can configure DNS entries to associate StorageGRID IP addresses to a fully qualified domain name (FQDN).


== Where to find IP addresses

. Sign in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
. To find the IP address of a grid node:
 .. Select *NODES*.
 .. Select the Admin Node, Gateway Node, or Storage Node to which you want to connect.
 .. Select the *Overview* tab.
 .. In the Node Information section, note the IP addresses for the node.
 .. Select *Show more* to view IPv6 addresses and interface mappings.
+
You can establish connections from client applications to any of the IP addresses in the list:

  * *eth0:* Grid Network
  * *eth1:* Admin Network (optional)
  * *eth2:* Client Network (optional)
+
NOTE: If you are viewing an Admin Node or a Gateway Node and it is the active node in a high availability group, the virtual IP address of the HA group is shown on eth2.
. To find the virtual IP address of a high availability group:
 .. Select *CONFIGURATION* > *Network* > *High availability groups*.
 .. In the table, note the virtual IP address of the HA group.

. To find the port number of a Load Balancer endpoint:

.. Select *CONFIGURATION* > *Network* > *Load balancer endpoints*.
.. Note the port number for the endpoint you want to use.
+
NOTE: If the port number is 80 or 443, the endpoint is configured only on Gateway Nodes, because those ports are reserved on Admin Nodes. All other ports are configured on both Gateway Nodes and Admin Nodes.

.. Select the name of the endpoint from the table.

.. Confirm that the *Client type* (S3 or Swift) matches the client application that will use the endpoint. 

