---
permalink: admin/use-s3-setup-wizard.html
sidebar: sidebar
keywords: S3, S3 setup wizard
summary: 'You can use the S3 setup wizard to configure StorageGRID as the object storage system for a S3 application.'
---
= S3 setup wizard: Considerations and requirements
:icons: font
:imagesdir: ../media/

[.lead]

You can use the S3 setup wizard to configure StorageGRID as the object storage system for an S3 application.

== When to use the S3 setup wizard

The S3 setup wizard guides you through each step of configuring StorageGRID for use with S3 and automatically configures certain entities for you, such as the ILM and traffic classification policies. As part of completing the wizard, you download a file that you can use to enter values into S3. Use the wizard to configure your system more quickly and to make sure your settings conform to StorageGRID. 

If you have the Root access permission, you can complete the S3 setup wizard when you start using the StorageGRID Grid Manager, or you can access and complete the wizard at any later time. Depending on your requirements, you can also configure some or all of the required items manually and then use the wizard to assemble the values that S3 needs into a single file.

== Before using the wizard

Before using the wizard, confirm you have completed this prerequisite step.

=== Review best practices

* You have reviewed the best practices for:

** xref:best-practices-for-high-availability-groups.adoc[High availability groups]
** xref:best-practices-for-load-balancing.adoc[Load balancing and the load balancer certificate]
