---
permalink: admin/what-is-autosupport.html
sidebar: sidebar
keywords: autosupport, technical support, storagegrid health, system status, Active IQ
summary: 'The AutoSupport feature enables your StorageGRID system to send health and status messages to technical support.'
---
= Use AutoSupport: Overview
:icons: font
:imagesdir: ../media/

[.lead]
The AutoSupport feature enables your StorageGRID system to send health and status messages to technical support. 

Using AutoSupport can significantly speed problem determination and resolution. Technical support can also monitor the storage needs of your system and help you determine if you need to add new nodes or sites. Optionally, you can configure AutoSupport messages to be sent to one additional destination.

You should configure StorageGRID AutoSupport only on the primary Admin Node. However, you must configure <<hardware_autosupport,hardware AutoSupport>> on each appliance.

== Information included in AutoSupport messages

include::../_include/autosupport-message-info.adoc[]

== What is Active IQ?

include::../_include/autosupport-activeiq.adoc[]

== Protocols for sending AutoSupport messages

You can choose one of three protocols for sending AutoSupport messages:

* HTTPS
* HTTP
* SMTP

NOTE: As of the StorageGRID 11.7 release, NetApp's AutoSupport servers will reject messages sent using HTTP. You must configure a proxy server to forward AutoSupport messages as HTTPS.

If you use SMTP as the protocol for AutoSupport messages, you must configure an SMTP mail server.

== AutoSupport options

You can use any combination of the following options to send AutoSupport messages to technical support:

* *Weekly*: Automatically send AutoSupport messages once per week. Default setting: Enabled.
* *Event-triggered*: Automatically send AutoSupport messages every hour or when significant system events occur. Default setting: Enabled.
* *On Demand*: Allow technical support to request that your StorageGRID system send AutoSupport messages automatically, which is useful when they are actively working an issue (requires HTTPS AutoSupport transmission protocol). Default setting: Disabled.
* *User-triggered*: Manually send AutoSupport messages at any time.

== [[hardware_autosupport]] AutoSupport for appliances

AutoSupport for appliances reports StorageGRID hardware issues, while StorageGRID AutoSupport reports StorageGRID software issues (except for SGF6112 where StorageGRID AutoSupport reports both hardware and software issues). You must configure AutoSupport on each appliance, except for the SGF6112 which does not does not require additional configuration. AutoSupport is implemented differently for services and storage appliances.

You must enable AutoSupport in SANtricity for each storage appliance. You can configure SANtricity AutoSupport during initial appliance setup or after an appliance has been installed:

* For SG6000 and SG5700 appliances, link:../installconfig/accessing-and-configuring-santricity-system-manager.html[configure AutoSupport in SANtricity System Manager]

AutoSupport messages from E-Series appliances can be included in StorageGRID AutoSupport if you configure AutoSupport delivery by proxy in link:../admin/sending-eseries-autosupport-messages-through-storagegrid.html[SANtricity System Manager].

StorageGRID AutoSupport does not report hardware issues, such as DIMM or host interface card (HIC) faults. However, some component failures might trigger link:../monitor/alerts-reference.html[hardware alerts]. For StorageGRID appliances with a baseboard management controller (BMC), such as the SG100, SG1000, SG6060, or SGF6024, you can configure email and SNMP traps to report hardware failures:

* link:../installconfig/setting-up-email-notifications-for-alerts.html[Set up email notifications for alerts]
* link:../installconfig/configuring-snmp-settings-for-bmc.html[Configure SNMP settings] for the SG6000-CN controller or the SG100 and SG1000 services appliances

.Related information

https://mysupport.netapp.com/site/global/dashboard[NetApp Support^]
