---
permalink: admin/what-admin-node-is.html
sidebar: sidebar
keywords: admin nodes
summary: 'Admin Nodes provide management services such as system configuration, monitoring, and logging. Each grid must have one primary Admin Node and might have any number of non-primary Admin Nodes for redundancy.'
---
= What an Admin Node is
:icons: font
:imagesdir: ../media/

[.lead]
Admin Nodes provide management services such as system configuration, monitoring, and logging. Each grid must have one primary Admin Node and might have any number of non-primary Admin Nodes for redundancy.

When you sign in to the Grid Manager or the Tenant Manager, you are connecting to an Admin Node. You can connect to any Admin Node, and each Admin Node displays a similar view of the StorageGRID system. However, maintenance procedures must be performed using the primary Admin Node.

Admin Nodes can also be used to load balance S3 and Swift client traffic.

== What is the preferred sender 

If your StorageGRID deployment includes multiple Admin Nodes, the primary Admin Node is the default _preferred sender_ for alert notifications, legacy alarm notifications, AutoSupport messages, and SNMP traps and informs. 

Under normal system operations, only the preferred sender sends notifications. However, all other Admin Nodes monitor the preferred sender. If a problem is detected, other Admin Nodes act as _standby senders_.

Multiple notifications might sent in these cases:

* If Admin Nodes become “islanded” from each other, both the preferred sender and the standby senders will attempt to send notifications, and multiple copies of notifications might be received.

* If standby sender detects problems with the preferred sender and starts sending notifications, the preferred sender might regain its ability to send notifications. If this occurs, duplicate notifications might be sent. The standby sender will stop sending notifications when it no longer detects errors on the preferred sender.
+
NOTE: When you test AutoSupport messages, all Admin Nodes send the test email. When you test alert notifications, you must sign in to every Admin Node to verify connectivity.


== Primary services for Admin Nodes

include::../_include/services-admin-node.adoc[]








