---
permalink: s3/custom-operations-on-buckets.html
sidebar: sidebar
keywords: operations, buckets, custom, custom operations on buckets
summary: 'The StorageGRID system supports custom bucket operations that are added on to the S3 REST API and are specific to the system.'
---
= Custom operations on buckets
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID system supports custom bucket operations that are added on to the S3 REST API and are specific to the system.

The following table lists the custom bucket operations supported by StorageGRID.

[cols="1a,1a,1a" options="header"]
|===
| Operation| Description| For more information
a|
GET Bucket consistency
a|
Returns the consistency level being applied to a particular bucket.
a|
link:get-bucket-consistency-request.html[GET Bucket consistency]
a|
PUT Bucket consistency
a|
Sets the consistency level applied to a particular bucket.
a|
link:put-bucket-consistency-request.html[PUT Bucket consistency]
a|
GET Bucket last access time
a|
Returns whether last access time updates are enabled or disabled for a particular bucket.
a|
link:get-bucket-last-access-time-request.html[GET Bucket last access time]
a|
PUT Bucket last access time
a|
Allows you to enable or disable last access time updates for a particular bucket.
a|
link:put-bucket-last-access-time-request.html[PUT Bucket last access time]
a|
DELETE Bucket metadata notification configuration
a|
Deletes the metadata notification configuration XML associated with a particular bucket.
a|
link:delete-bucket-metadata-notification-configuration-request.html[DELETE Bucket metadata notification configuration]
a|
GET Bucket metadata notification configuration
a|
Returns the metadata notification configuration XML associated with a particular bucket.
a|
link:get-bucket-metadata-notification-configuration-request.html[GET Bucket metadata notification configuration]
a|
PUT Bucket metadata notification configuration
a|
Configures the metadata notification service for a bucket.
a|
link:put-bucket-metadata-notification-configuration-request.html[PUT Bucket metadata notification configuration]
a|
PUT Bucket with compliance settings
a|
Deprecated and not supported: You can no longer create new buckets with Compliance enabled.
a|
link:deprecated-put-bucket-request-modifications-for-compliance.html[Deprecated: PUT Bucket with compliance settings]
a|
GET Bucket compliance
a|
Deprecated but supported: Returns the compliance settings currently in effect for an existing legacy Compliant bucket.
a|
link:deprecated-get-bucket-compliance-request.html[Deprecated: GET Bucket compliance]
a|
PUT Bucket compliance
a|
Deprecated but supported: Allows you to modify the compliance settings for an existing legacy Compliant bucket.
a|
link:deprecated-put-bucket-compliance-request.html[Deprecated: PUT Bucket compliance]
|===
.Related information

link:s3-operations-tracked-in-audit-logs.html[S3 operations tracked in the audit logs]
