---
permalink: s3/index.html
sidebar: sidebar
keywords: about s3, s3 rest api, s3 overview
summary: 'StorageGRID supports the Simple Storage Service \(S3\) API, which is implemented as a set of Representational State Transfer \(REST\) web services.'
---
= S3 REST API supported versions and updates
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID supports the Simple Storage Service (S3) API, which is implemented as a set of Representational State Transfer (REST) web services.

Support for the S3 REST API enables you to connect service-oriented applications developed for S3 web services with on-premises object storage that uses the StorageGRID system. Minimal changes to a client application's current use of S3 REST API calls are required.

== Supported versions

StorageGRID supports the following specific versions of S3 and HTTP.

[cols="1a,1a" options="header"]
|===
| Item| Version

|S3 specification
|_Simple Storage Service API Reference_ 2006-03-01

|HTTP
|1.1

For more information about HTTP, see HTTP/1.1 (RFCs 7230-35).

*Note*: StorageGRID does not support HTTP/1.1 pipelining.

|===

.Related information

https://datatracker.ietf.org/doc/html/rfc2616[IETF RFC 2616: Hypertext Transfer Protocol (HTTP/1.1)^]

http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html[Amazon Web Services (AWS) Documentation: Amazon Simple Storage Service API Reference^]

== Support for StorageGRID platform services

StorageGRID platform services enable StorageGRID tenant accounts to leverage external services such as a remote S3 bucket, a Simple Notification Service (SNS) endpoint, or an Elasticsearch cluster to extend the services provided by a grid.

The following table summarizes the available platform services and the S3 APIs used to configure them.

[cols="1a,4a,2a" options="header"]
|===
| Platform service| Purpose| S3 API used to configure the service

|CloudMirror replication
|Replicates objects from a source StorageGRID bucket to the configured remote S3 bucket.
|PUT Bucket replication

|Notifications
|Sends notifications about events in a source StorageGRID bucket to a configured Simple Notification Service (SNS) endpoint.
|PUT Bucket notification

|Search integration
|Sends object metadata for objects stored in a StorageGRID bucket to a configured Elasticsearch index.
|PUT Bucket metadata notification

*Note:* This is a StorageGRID custom S3 API.

|===

A grid administrator must enable the use of platform services for a tenant account before they can be used. Then, a tenant administrator must create an endpoint that represents the remote service in the tenant account. This step is required before a service can be configured.

Before using platform services, note the following recommendations:

* NetApp recommends that you allow no more than 100 active tenants with S3 requests requiring CloudMirror replication, notifications, and search integration. Having more than 100 active tenants can result in slower S3 client performance.
* If an S3 bucket in the StorageGRID system has both versioning and CloudMirror replication enabled, NetApp recommends that the destination endpoint also have S3 bucket versioning enabled. This allows CloudMirror replication to generate similar object versions on the endpoint.
* CloudMirror replication is not supported if the source bucket has S3 Object Lock enabled.
* CloudMirror replication will fail with an AccessDenied error if the destination bucket has legacy Compliance enabled.

.Related information

link:../tenant/index.html[Use a tenant account]

link:../admin/index.html[Administer StorageGRID]

link:operations-on-buckets.html[Operations on buckets]

link:put-bucket-metadata-notification-configuration-request.html[PUT Bucket metadata notification configuration request]

== Updates to S3 REST API support

[cols="1a,4a" options="header"]
|===
| Release| Comments

|11.7
|
* Added support for using GOVERNANCE mode with S3 Object Lock.
* Added support for the StorageGRID-specific `x-ntap-sg-cgr-replication-status` response header for GET Object and HEAD Object requests. This header provides an object's replication status for cross-grid replication.
* SelectObjectContent requests now support Parquet objects.

|11.6
|
* Added support for using the `partNumber` request parameter in GET Object and HEAD Object requests.
* Added support for a default retention mode and a default retention period at the bucket level for S3 Object Lock.
* Added support for the `s3:object-lock-remaining-retention-days` policy condition key to set the range of allowable retention periods for your objects.
* Changed the maximum _recommended_ size for a single PUT Object operation to 5 GiB (5,368,709,120 bytes). If you have objects that are larger than 5 GiB, use multipart upload instead. 

|11.5
|
* Added support for managing bucket encryption.
* Added support for S3 Object Lock and deprecated legacy Compliance requests.
* Added support for using DELETE Multiple Objects on versioned buckets.
* The `Content-MD5` request header is now correctly supported.

|11.4
|
* Added support for DELETE Bucket tagging, GET Bucket tagging, and PUT Bucket tagging. Cost allocation tags are not supported.
* For buckets created in StorageGRID 11.4, restricting object key names to meet performance best practices is no longer required.
* Added support for bucket notifications on the `s3:ObjectRestore:Post` event type.
* AWS size limits for multipart parts are now enforced. Each part in a multipart upload must be between 5 MiB and 5 GiB. The last part can be smaller than 5 MiB.
* Added support for TLS 1.3

|11.3
|
* Added support for server-side encryption of object data with customer-provided keys (SSE-C).
* Added support for DELETE, GET, and PUT Bucket lifecycle operations (Expiration action only) and for the `x-amz-expiration` response header.
* Updated PUT Object, PUT Object - Copy, and Multipart Upload to describe the impact of ILM rules that use synchronous placement at ingest.
* TLS 1.1 ciphers are no longer supported.

|11.2
|Added support for POST Object restore for use with Cloud Storage Pools. Added support for using the AWS syntax for ARN, policy condition keys, and policy variables in group and bucket policies. Existing group and bucket policies that use the StorageGRID syntax will continue to be supported.

*Note:* Uses of ARN/URN in other configuration JSON/XML, including those used in custom StorageGRID features, have not changed.

|11.1
|Added support for cross-origin resource sharing (CORS), HTTP for S3 client connections to grid nodes, and compliance settings on buckets.

|11.0
|Added support for configuring platform services (CloudMirror replication, notifications, and Elasticsearch search integration) for buckets. Also added support for object tagging location constraints for buckets, and the Available consistency control setting.

|10.4
|Added support for ILM scanning changes to versioning, Endpoint Domain Names page updates, conditions and variables in policies, policy examples, and the PutOverwriteObject permission.

|10.3
|Added support for versioning.

|10.2
|Added support for group and bucket access policies, and for multipart copy (Upload Part - Copy).

|10.1
|Added support for multipart upload, virtual hosted-style requests, and v4 authentication.

|10.0
|Initial support of the S3 REST API by the StorageGRID system.The currently supported version of the _Simple Storage Service API Reference_ is 2006-03-01.

|===
