---
permalink: s3/recommendations-for-implementing-s3-rest-api.html
sidebar: sidebar
keywords: implement s3 rest api
summary: 'You should follow these recommendations when implementing the S3 REST API for use with StorageGRID.'
---
= Recommendations for implementing S3 REST API
:icons: font
:imagesdir: ../media/

[.lead]
You should follow these recommendations when implementing the S3 REST API for use with StorageGRID.

== Recommendations for HEADs to non-existent objects

If your application routinely checks to see if an object exists at a path where you do not expect the object to actually exist, you should use the "`Available`" consistency control. For example, you should use the "`Available`" consistency control if your application HEADs a location before PUT-ing to it.

Otherwise, if the HEAD operation does not find the object, you might receive a high number of 500 Internal Server errors if one or more Storage Nodes are unavailable.

You can set the "`Available`" consistency control for each bucket using the PUT Bucket consistency request, or you can specify the consistency control in the request header for an individual API operation.

== Recommendations for object keys

Follow these recommendations for object key names, based on when the bucket was first created.

.Buckets created in StorageGRID 11.4 or earlier

* Do not use random values as the first four characters of object keys. This is in contrast to the former AWS recommendation for key prefixes. Instead, use non-random, non-unique prefixes, such as `image`.

* If you do follow the former AWS recommendation to use random and unique characters in key prefixes, prefix the object keys with a directory name. That is, use this format:
+
`mybucket/mydir/f8e3-image3132.jpg`
+
Instead of this format:
+
`mybucket/f8e3-image3132.jpg`

.Buckets created in StorageGRID 11.4 or later

Restricting object key names to meet performance best practices is not required. In most cases, you can use random values for the first four characters of object key names.

CAUTION: An exception to this is traffic that includes a large number of small S3 objects that have a short retention cycle. For this use case, you should use non-random prefixes.

== Recommendations for "`range reads`"

If the link:../admin/configuring-stored-object-compression.html[global option to compress stored objects] is enabled, S3 client applications should avoid performing GET Object operations that specify a range of bytes be returned. These "`range read`" operations are inefficient because StorageGRID must effectively uncompress the objects to access the requested bytes. GET Object operations that request a small range of bytes from a very large object are especially inefficient; for example, it is very inefficient to read a 10 MB range from a 50 GB compressed object.

If ranges are read from compressed objects, client requests can time out.

NOTE: If you need to compress objects and your client application must use range reads, increase the read timeout for the application.

.Related information

* link:consistency-controls.html[Consistency controls]

* link:put-bucket-consistency-request.html[PUT Bucket consistency request]

* link:../admin/index.html[Administer StorageGRID]
