---
permalink: s3/s3-request-reference.html
sidebar: sidebar
keywords: s3 request headers, s3 command support, request syntax, not supported requests, aws s3
summary: 'Get a quick summary of StorageGRID support for Amazon Simple Storage Service (S3) APIs.'
---
= S3 request reference
:icons: font
:imagesdir: ../media/

[.lead]
Get a quick summary of StorageGRID support for Amazon Simple Storage Service (S3) APIs.


== A-E

.AbortMultipartUpload
[%collapsible]

====
.Request syntax

Go to https://docs.aws.amazon.com/AmazonS3/latest/API/API_AbortMultipartUpload.html[Amazon Simple Storage Service (S3) > API Reference > AbortMultipartUpload^].

.StorageGRID support

StorageGRID does not support these parameters:

`x-amz-request-payer`

.Learn more
xref:operations-for-multipart-uploads.adoc[Operations for multipart uploads]

====

.CompleteMultipartUpload
[%collapsible]

====

.Request syntax

Go to https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html[Amazon Simple Storage Service (S3) > API Reference > CompleteMultipartUpload^].

.StorageGRID support

StorageGRID does not support these parameters:

`x-amz-request-payer`

.Learn more
xref:complete-multipart-upload.adoc[Complete Multipart Upload]

====

.CopyObject (PUT Object-Copy)
[%collapsible]

====
.Request syntax


Go to https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html[Amazon Simple Storage Service (S3) > API Reference > CopyObject^].

.StorageGRID support

StorageGRID does not support these parameters:

----
Cache-Control
Expires
x-amz-grant-full-control
x-amz-grant-read
x-amz-grant-read-acp
x-amz-grant-write-acp
x-amz-website-redirect-location
x-amz-server-side-encryption-aws-kms-key-id
x-amz-server-side-encryption-context
x-amz-request-payer
----

.Learn more
xref:put-object-copy.html.adoc[PUT Object-Copy]

====

.CreateBucket (PUT Bucket)
[%collapsible]

====

.Request syntax

Go to https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html[Amazon Simple Storage Service (S3) > API Reference > CreateBucket^].

.StorageGRID support

StorageGRID does not support these parameters:

----
x-amz-acl
x-amz-grant-full-control
x-amz-grant-read
x-amz-grant-read-acp
x-amz-grant-write
x-amz-grant-write-acp
----

.Learn more
xref:operations-on-buckets.adoc[Operations on buckets]

====

== F-J


=== GetBucketAcl

.Request syntax

Go to https://https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketAcl.html[Amazon Simple Storage Service (S3) > API Reference > GetBucketAcl^].

.StorageGRID support
Implemented with all Amazon S3 REST API behavior.

.Learn more
xref:operations-on-buckets.adoc[Operations on buckets]

=== GetBucketAnalyticsConfiguration
Not supported.


== ListBucketAnalyticsConfigurations
Not supported.

== ListBucketInventoryConfigurations
Not supported.

== ListBucketMetricsConfigurations
Not supported.

== ListBuckets
.Request syntax

Go to https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListBuckets.html[Amazon Simple Storage Service (S3) > API Reference > ListBuckets^].

.StorageGRID support
Implemented with all Amazon S3 REST API behavior.

.Learn more
xref:operations-on-buckets.adoc[Operations on buckets]





