---
permalink: monitor/index.html
sidebar: sidebar
keywords: monitor StorageGRID
summary: 'Use these instructions to monitor a StorageGRID system and to assess and resolve issues that might occur.'
---
= Monitor a StorageGRID system: Overview
:icons: font
:imagesdir: ../media/

[.lead]
Use these instructions to monitor a StorageGRID system and to assess issues that might occur. 

These instructions describe how to use the Grid Manager to monitor a StorageGRID system. You will learn which information you should monitor regularly, how to manage alerts and legacy alarms, how to use SNMP for monitoring, and how to obtain additional StorageGRID data, including metrics and diagnostics.

.What you'll need
* You must be signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You must have link:../admin/admin-group-permissions.html[specific access permissions].

NOTE: To change units for the storage values displayed in the Grid Manager, select the user drop-down in the upper right of the Grid Manager, then select *User preferences*.