---
permalink: sg6100/index.html
sidebar: sidebar
keywords: storagegrid, sg6100 storage appliance, SGF6112 storage appliance, maintain, maintaining, hardware, procedures, tasks
summary: 'You might need to perform maintenance procedures on the appliance. The procedures in this section assume that the appliance has already been deployed as a Storage Node in a StorageGRID system.'
---
= Maintain SG6100 appliances
:icons: font
:imagesdir: ../media/

[.lead]
You might need to perform maintenance procedures on your appliance. The procedures in this section assume that the appliance has already been deployed as a Storage Node in a StorageGRID system.

Procedures specific to maintaining your SGF6112 appliance are in this section. 

Maintenance configuration procedures include procedures that are performed using software including the Appliance Installer, Grid Manager, or BMC interface such as:

* Turn controller identify LED on and off
* Locate controller in data center
* Shut down the appliance
* Change link configuration of the appliance

Hardware procedures are procedurs that require the physical manipulation of components such as: 

* Replace one or both power supplies
* Replace fans
* Replace drives
* Replace entire appliance


See xref:../commonhardware/index.adoc[Common procedures] for maintenance procedures that are used by all appliances. 

See xref:../installconfig/configuring-hardware.adoc[Set up hardware] for maintenance procedures that are also performed during initial appliance installation and configuration.
