---
permalink: maintain/configuring-dns-servers.html
sidebar: sidebar
keywords: storagegrid, dns, configuring dns, configure dns, domain name system
summary: 'You can add, remove, and update domain name system \(DNS\) servers, so that you can use fully qualified domain name \(FQDN\) hostnames rather than IP addresses.'
---
= Configure DNS servers
:icons: font
:imagesdir: ../media/

[.lead]
You can add, remove, and update domain name system (DNS) servers, so that you can use fully qualified domain name (FQDN) hostnames rather than IP addresses.

To use fully qualified domain names (FQDNs) instead of IP addresses when specifying hostnames for external destinations, specify the IP address of each domain name system (DNS) server you will use. These entries are used for AutoSupport, alert emails, SNMP notifications, platform services endpoints, Cloud Storage Pools, and more.

.What you'll need

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have the Maintenance or Root Access permission.
* You must have the IP addresses of the DNS servers to configure.

Specifying DNS server information allows you to use fully qualified domain name (FQDN) hostnames rather than IP addresses for email or SNMP notifications and AutoSupport.

IMPORTANT: Specify the IP address of at least one DNS server. Specifying at least two servers is recommended. If possible, use servers that each site can access locally to ensure that an islanded site can resolve the FQDNs for external destinations. After configuring the grid-wide DNS server list, you can xref:modifying-dns-configuration-for-single-grid-node.adoc[further customize the DNS server list for each node].

If the DNS server information is omitted or incorrectly configured, a DNST alarm is triggered on each grid node's SSM service. The alarm clears when the DNS is configured correctly and the new server information has reached all grid nodes.

.Steps

. Select *MAINTENANCE* > *Network* > *DNS servers*.
. Select *Add another server* to add a new DNS server.
. Select *Save*.

To delete an IP address of a DNS server, select the delete icon image:../media/  next to the IP address.


