---
permalink: maintain/index.html
sidebar: sidebar
keywords: maintain overview, maintenance overview, about maintain, about maintenance
summary: 'Use these instructions to maintain your StorageGRID system and to recover from failures.'
---
= Recover and maintain: Overview
:icons: font
:imagesdir: ../media/

[.lead]
Use these instructions to maintain your StorageGRID system and to recover from failures.

== About these instructions
These instructions describe how to apply a software hotfix, recover grid nodes, recover a failed site, decommission grid nodes or an entire site, perform network maintenance, perform host-level and middleware maintenance procedures, and perform grid node procedures.

NOTE: In these instructions, "`Linux`" refers to a Red Hat速 Enterprise Linux速, Ubuntu速, CentOS, or Debian速 deployment. Use the https://imt.netapp.com/matrix/#welcome[NetApp Interoperability Matrix Tool^] to get a list of supported versions. 

== Before you begin

* You have a broad understanding of the StorageGRID system. 
* You have reviewed your StorageGRID system's topology and you understand the grid configuration.

* You understand that you must follow all instructions exactly and heed all warnings.

* You understand that maintenance procedures not described are not supported or require a services engagement.

== Maintenance procedures for appliances

For hardware procedures, see the maintenance instructions for your StorageGRID appliance.

* link:../sg6100/index.html[SGF6112 storage appliances]

* link:../sg6000/index.html[SG6000 storage appliances]

* link:../sg5700/index.html[SG5700 storage appliances]

* link:../sg100-1000/index.html[SG100 and SG1000 services appliances]
