---
permalink: maintain/rename-grid-site-node-overview.html
sidebar: sidebar
keywords: rename grid, rename site, rename node, change display name, bulk rename tool
summary: 'As required, you can change the display names that are shown throughout the Grid Manager for your entire grid, each site, and each node. You can update display names safely and whenever you need.'
---
= Requirements and best practices for display names
:icons: font
:imagesdir: ../media/

[.lead]
As required, you can change the display names that are shown throughout the Grid Manager for the entire grid, each site, and each node. You can update display names safely and whenever you need. 

== What is the rename procedure?

When you install StorageGRID initially, you specify a name for the grid, each site, and each node. These initial names are known as _system names_, and they are the names initially shown throughout StorageGRID.

System names are required for internal StorageGRID operations and cannot be changed. However, you can use the rename procedure to define new _display names_ for the grid, each site, and each node. When defined, display names appear in various StorageGRID locations instead of (or in some cases, in addition to) the item's underlying _system name_. 

Use the rename procedure to correct typos, to implement a different naming convention, or to indicate that a site and all of its nodes have been relocated. Unlike system names, display names can be updated whenever required and without impacting StorageGRID operations. 

== Where do system and display names appear?
The following table summarizes where system names and display names are shown in the StorageGRID user interface and in StorageGRID files.

[cols="1a,1a,1a" options="header"]
|===
// header row
|Location
|System name
|Display name

|Grid Manager pages
|Shown when a display name is not defined. 

|When defined, shown instead of the system name in these locations:

* Nodes page
* Alerts
* Storage pool definitions
* Maintenance procedures
* Support pages


|*NODES* > *Overview* tab for a node
|Always shown 
|Always shown

When a display name is not defined, the values for *Display name* and  *System name* on this tab are the same.

|Legacy pages in the Grid Manager (for example, *SUPPORT* > *Grid Topology*)
|Shown 
|Not shown



|Prompt when using SSH to access a node

|
Shown as the primary name when a display name is not defined:

`admin@SYSTEM-NAME: ~ $`

Included in parentheses when a display name is defined:

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`


|When defined, shown as the primary name:

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



|`Passwords.txt` file in the Recovery Package
|Shown as `Name`
|Shown as `Display name`

|/etc/hosts file on all nodes

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`

|Always shown in the second column
|When defined, shown in the fourth column

|topology_display_names.json file 
|_Not applicable_
|When display names have been defined, this file is included with ASUP data. It maps grid, site, and node IDs to their display names. 

|Prometheus metrics
|
|

// table end
|===

== Display name requirements

Before using this procedure, review the requirements for display names. 

Display names for nodes must follow these rules:

* Must be unique across your StorageGRID system.
* Cannot be the same as the system name for any other item in your StorageGRID system.
* Must contain at least 1 and no more than 32 characters.
* Can contain numbers, hyphens (-), and uppercase and lowercase letters.
* Can start or end with a letter or number, but cannot start or end with a hyphen.
* Cannot be all numbers.
* Are case-insensitive. For example, `DC1-ADM` and `dc1-adm` will be flagged as duplicates.

Display names for the grid and sites follow the same rules with these exceptions:

* Can include spaces.
* Can include these special characters: `= - _ : , . @ !`
* Can start and end with the special characters, including hyphens.
* Can be all numbers or special characters.


== Display name best practices

If you plan to rename multiple items, document your general naming scheme before using this procedure. Come up with a system that ensures that names are unique, consistent, and easy to understand at a glance.

You can use any naming convention that fits your organizational requirements. Consider these basic suggestions of what to include:

* *Site indicator*: If you have multiple sites, add a site code to each node name. 
* *Node type*: Node names typically indicate the node's type. You can use abbreviations like `s`, `adm`, `gw`, and `arc` (Storage Node, Admin Node, Gateway Node, and Archive Node).
* *Node number*: If a site contains more than one of a particular type of node, add a unique number to each node's name.

Think twice before adding specific details to the names that are likely to change over time. For example, do not include IP addresses in node names because these addresses can be changed. Similarly, rack location or appliance model numbers can change if you move equipment or upgrade the hardware.


=== Example display names 
Suppose your StorageGRID system has three data centers and has nodes of different types at each data center. Your display names might be as simple as these:

* *Grid*: `StorageGRID Deployment`

* *Site*: `Data Center 1`

** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`

* *Site*: `Data Center 2`
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`

* *Site*: `Data Center 3`
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`

