---
permalink: maintain/replacing-storage-node.html
sidebar: sidebar
keywords: storagegrid, recover, replace storage node, replacing storage node
summary: 'If the system drive has failed, you must first replace the Storage Node.'
---
= Replace the Storage Node
:icons: font
:imagesdir: ../media/

[.lead]
If the system drive has failed, you must first replace the Storage Node.

You must select the node replacement procedure for your platform. The steps to replace a node are the same for all types of grid nodes.

NOTE: This procedure applies to software-based Storage Nodes only. You must follow a different procedure to link:recovering-storagegrid-appliance-storage-node.html[recover an appliance Storage Node].

*Linux:* If you aren't sure if your system drive has failed, follow the instructions to replace the node to determine which recovery steps are required.

[cols="1a,2a" options="header"]
|===
| Platform
| Procedure

| VMware
| link:all-node-types-replacing-vmware-node.html[Replace a VMware node]

| Linux
| link:all-node-types-replacing-linux-node.html[Replace a Linux node]

| OpenStack
| NetApp-provided virtual machine disk files and scripts for OpenStack are no longer supported for recovery operations. If you need to recover a node running in an OpenStack deployment, download the files for your Linux operating system. Then, follow the procedure for link:all-node-types-replacing-linux-node.html[replacing a Linux node].

|===
