---
permalink: maintain/restoring-volume.html
sidebar: sidebar
keywords: storagegrid, restore, volume
summary: 'In some situations, storage volumes restoration can be started in Grid Manager. Grid Manager can also monitor volume restoration processes in progress and display a volume restoration history.'
---
= Restore volume using Grid Manager
:icons: font
:imagesdir: ../media/

[.lead]
In some situations, storage volumes restoration can be started in Grid Manager. Grid Manager can also monitor volume restoration processes in progress and display a volume restoration history.

.What you'll need



.About this task

List situations/restrictions for GUI vs CLI

Explain that monitoring and history are available for both GUI and CLI

Notes in CLI topics about monitoring and history in GUI and that an XXXX volume restore can be performed in the GUI or CLI (GUI preferred unless scripting?).

.Steps

To restore a lost volume:

. In Grid Manager go to *Maintenance* > *Volume restoration*.

. Select the *Pending data* tab.
+
The number on the tab indicates the number of nodes requiring restoration.

. Expand each node to see the volumes in it that need restoration and their status.
 
. Correct any issues preventing restoration, as indicated.

. Select the node to restore.
+
You can only restore one node at a time.
+
Each volume in the node should indicate that it is ready to restore.

. Select *Start restore*.

. Address any warnings that might display or select *Start anyway*.

Nodes are moved from the Pending data tab to the Restoration progress tab when the restoration starts.

== View restoration progress

The Restoration progress tab shows the status of the restoration process and information about the volumes in a node being restored.

Can monitor restorations initiated in GUI or triggered by CLI commands (old method).



== View restoration history

.Related information


