---
permalink: expand/configuring-expanded-storagegrid-system.html
sidebar: sidebar
keywords: expansion, configuration
summary: 'After completing an expansion, you must perform additional integration and configuration steps.'
---
= Configuration steps after expansion
:icons: font
:imagesdir: ../media/

[.lead]
After completing an expansion, you must perform additional integration and configuration steps.

.About this task

You must complete the configuration tasks listed below for the grid nodes or sites you are adding in your expansion. Some tasks might be optional, depending on the options selected when installing and administering your system, and how you want to configure the nodes and sites added during the expansion.

.Steps

. If you added a Storage Node, complete the following configuration tasks:

.. Manage the storage pools used in your ILM rules to ensure the new storage will be used. 

* If you added a site, xref:../ilm/creating-storage-pool.adoc[create a storage pool] for the site and each storage grade you selected for the new Storage Nodes. Confirm that the ILM policy meets the new requirements. If rule changes are required, link:../ilm/access-create-ilm-rule-wizard.html[create new rules] and link:../ilm/working-with-ilm-rules-and-ilm-policies.html[update the ILM policy]. If the rules are already correct, link:../ilm/activating-ilm-policy.html[activate a new policy] with no rule changes to ensure StorageGRID uses the new nodes.

* If you added one or more Storage Nodes to an existing site, xref:../ilm/viewing-storage-pool-details.adoc[view storage pool details] to confirm that each node you added is included in the expected storage pools and used in the expected ILM rules.

.. xref:verifying-storage-node-is-active.adoc[Verify that the Storage Node is active] and able to ingest objects.

.. Rebalance erasure-coded data (only if you were unable to add the recommended number of Storage Nodes). See 
xref:rebalancing-erasure-coded-data-after-adding-storage-nodes.adoc[Rebalance erasure-coded data after adding Storage Nodes].


. If you added a Gateway Node, complete the following configuration task:

** If high availability (HA) groups are used for client connections, optionally add the Gateway Node to an HA group. Select *CONFIGURATION* > *Network* > *High availability groups* to review the list of existing HA groups and to add the new node. See xref:../admin/configure-high-availability-group.adoc[Configure high availability groups].

. If you added an Admin Node, complete the following configuration tasks:

.. If single sign-on (SSO) is enabled for your StorageGRID system, create a relying party trust for the new Admin Node. You cannot sign in to the node until you create this relying party trust. See
xref:../admin/configuring-sso.adoc[Configure single sign-on].

.. If you plan to use the Load Balancer service on Admin Nodes, optionally add the new Admin Node to a HA group. Select *CONFIGURATION* > *Network* > *High availability groups* to review the list of existing HA groups and to add the new node. See xref:../admin/configure-high-availability-group.adoc[Configure high availability groups].

.. Optionally, copy the Admin Node database from the primary Admin Node to the expansion Admin Node if you want to keep the attribute and audit information consistent on each Admin Node. See xref:copying-admin-node-database.adoc[Copy the Admin Node database].

.. Optionally, copy the Prometheus database from the primary Admin Node to the expansion Admin Node if you want to keep the historical metrics consistent on each Admin Node. See  xref:copying-prometheus-metrics.adoc[Copy Prometheus metrics].

.. Optionally, copy the existing audit logs from the primary Admin Node to the expansion Admin Node if you want to keep the historical log information consistent on each Admin Node. See xref:copying-audit-logs.adoc[Copy audit logs].

.. Optionally, configure access to the system for auditing purposes through an NFS file share. See xref:../admin/configuring-audit-client-access.adoc[Configure audit client access for NFS].

. If you added an Archive Node, complete the following configuration tasks.

.. Configure the Archive Node's connection to the targeted external archival storage system. When you complete the expansion, Archive Nodes are in an alarm state until you configure connection information through the *ARC* > *Target* component. See xref:../admin/archiving-to-cloud-through-s3-api.adoc[Archive to the cloud through the S3 API] or xref:../admin/archiving-to-tape-through-tsm-middleware.adoc[Archive to tape through TSM middleware].

.. xref:../ilm/creating-ilm-policy.adoc[Update the ILM policy] to archive object data through the new Archive Node.

.. xref:../monitor/creating-custom-alert-rules.adoc[Configure custom alarms] for the attributes that are used to monitor the speed and efficiency of object data retrieval from Archive Nodes.

. To check if expansion nodes were added with an untrusted Client Network or to change whether a node's Client Network is untrusted or trusted, go to *CONFIGURATION* > *Security* > *Firewall control*.
+
If the Client Network on the expansion node is untrusted, then connections to the node on the Client Network must be made using a load balancer endpoint. See xref:../admin/manage-firewall-controls.adoc[Manage firewall controls].

. Configure the Domain Name System (DNS).
+
If you have been specifying DNS settings separately for each grid node, you must add custom per-node DNS settings for the new nodes. See xref:../maintain/modifying-dns-configuration-for-single-grid-node.adoc[Modify DNS configuration for single grid node].
+
The best practice is for the grid-wide DNS server list to contain some DNS servers that are accessible locally from each site. If you just added a new site, add new DNS servers for the site to the grid-wide DNS configuration.
+
IMPORTANT: Provide two to six IPv4 addresses for DNS servers. You should select DNS servers that each site can access locally in the event of network islanding. This is to ensure an islanded site continues to have access to the DNS service. After configuring the grid-wide DNS server list, you can further customize the DNS server list for each node. For details, see xref:../maintain/modifying-dns-configuration-for-single-grid-node.adoc[Modify DNS configuration for single grid node]..

. If you added a new site, confirm that Network Time Protocol (NTP) servers are accessible from that site. See xref:../maintain/configuring-ntp-servers.adoc[Manage NTP servers].
+
IMPORTANT: Make sure that at least two nodes at each site can access at least four external NTP sources. If only one node at a site can reach the NTP sources, timing issues will occur if that node goes down. In addition, designating two nodes per site as primary NTP sources ensures accurate timing if a site is isolated from the rest of the grid.
