---
permalink: troubleshoot/troubleshoot-s3-put-object-size-too-large-alert.html
sidebar: sidebar
keywords: how to troubleshoot S3 PUT Object size too large alert, S3 PUT Object size
summary: 'The S3 PUT Object size too large alert is triggered if a tenant attempts a PUT Object operation that exceeds the S3 size limit of 5 GiB.'
---
= Troubleshoot S3 PUT Object size too large alert
:icons: font
:imagesdir: ../media/

[.lead]
The S3 PUT Object size too large alert is triggered if a tenant attempts a PUT Object operation that exceeds the S3 size limit of 5 GiB.

.What you'll need
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have link:../admin/admin-group-permissions.html[specific access permissions].

Determine which tenants use objects that are larger than 5 GiB, so you can notify them.

.Steps

. Go to *CONFIGURATION* > *Monitoring* > *Audit and syslog server*.
 
. If Client Writes are Normal, access the audit log:
.. Enter `ssh admin@_primary_Admin_Node_IP_`
.. Enter the password listed in the `Passwords.txt` file.
.. Enter the following command to switch to root: `su -`
.. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
.. Enter `cd /var/local/audit/export`
.. Enter `grep "CSIZ(UI64):[0-9]*[5-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]" audit.log |grep SPUT`
.. Review the results to identify which tenants use objects greater than 5 GiB.  Look for CSIZ values greater than 5,368,709,120 bytes and locate the corresponding ID in the S3AI field.
+
[cols="1a,2a" options="header"]
|===
| Code| Description

|SAIP
|Source IP

|S3AI
|Tenant ID

|S3BK
|Bucket

|S3KY
|Object 

|CSIZ
|Size (bytes)
|===

. If Client Writes are Normal, use the tenant ID from the alert to identify the tenant:
.. Go to *SUPPORT* > *Tools* > *Logs*. Collect application logs for the Storage Node in the alert. Specify 15 minutes before and after the alert.
.. Extract the file and go to `bycast.log`:
+
`/GID<grid_id>_<time_stamp>/<site_node>/<time_stamp>/grid/bycast.log`
.. Search the log for `method=PUT` and identify the client in the `clientIP` field.
 
. Inform tenants that the maximum PUT Object size is 5 GiB.
 
. Use multipart uploads for objects > 5 GiB.
 
. Ignore the alert for one week if the application has been changed.