---
permalink: ilm/creating-cloud-storage-pool.html
sidebar: sidebar
keywords: how to create cloud storage pool
summary: 'When you create a Cloud Storage Pool, you specify the name and location of the external bucket or container that StorageGRID will use to store objects, the cloud provider type \(Amazon S3 or Azure Blob Storage\), and the information StorageGRID needs to access the external bucket or container.'
---
= Create a Cloud Storage Pool
:icons: font
:imagesdir: ../media/

[.lead]
When you create a Cloud Storage Pool, you specify the name and location of the external bucket or container that StorageGRID will use to store objects, the cloud provider type (Amazon S3 or Azure Blob Storage), and the information StorageGRID needs to access the external bucket or container.

A Cloud Storage Pool specifies a single external Amazon S3 bucket or Azure Blob Storage container. StorageGRID validates the Cloud Storage Pool as soon as you save it, so you must ensure that the bucket or container specified in the Cloud Storage Pool exists and is reachable.

.What you'll need
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the xref:../admin/admin-group-permissions.adoc[required permissions].
* You have reviewed the guidelines for configuring Cloud Storage Pools.
* The external bucket or container referenced by the Cloud Storage Pool already exists.
* To access the bucket or container, you have the authentication information for the authentication type you will choose:
//tabbed blocks start here
+
[role="tabbed-block"]
====
.Access key
--
Use *Access key* or *Anonymous* for the Amazon S3/GCP provider type. If you use *Access key*, you know the following information for the external S3 bucket:

* The Access Key ID for the account that owns the external bucket.
* The associated Secret access key.
--
//end Access key, begin CAP

.C2S access portal
--
To use the Commercial Cloud Services (C2S) S3 service as a Cloud Storage Pool, you must configure C2S Access Portal (CAP) as the authentication type, so that StorageGRID can request temporary credentials to access the S3 bucket in your C2S account.

* You know the complete URL that StorageGRID will use to obtain temporary credentials from the CAP server, including all the required and optional API parameters assigned to your C2S account.
* You have a server CA certificate issued by an appropriate Government Certificate Authority (CA). StorageGRID uses this certificate to verify the identity of the CAP server. The server CA certificate must use PEM encoding.
* You have a client certificate issued by an appropriate Government Certificate Authority (CA). StorageGRID uses this certificate to identity itself to the CAP server. The client certificate must use PEM encoding and must have been granted access to your C2S account.
* You have a PEM-encoded private key for the client certificate.
* If the private key for the client certificate is encrypted, you have the passphrase for decrypting it.
--
//end C2S, begin Azure
.Azure Block Storage
--
* You know the Uniform Resource Identifier (URI) used to access the Blob storage container used for the Cloud Storage Pool.

* You know the name of the storage account and the account key. You can use the Azure portal to find these values.
====
//end tabbed blocks

.Steps
. Select *ILM* > *Storage pools* > *Cloud Storage Pools*.

. Select *Create*, then enter the following information:
+
[cols="1a,3a" options="header"]
|===
| Field| Description

|Cloud Storage Pool name
|A name that briefly describes the Cloud Storage Pool and its purpose. Use a name that will be easy to identify when you configure ILM rules.

|Provider type
|Which cloud provider you will use for this Cloud Storage Pool:

* *Amazon S3/GCP*: Select this option for an Amazon S3, Commercial Cloud Services (C2S) S3, Google Cloud Platform (GCP), or other S3-compatible provider. 
* *Azure Blob Storage*

|Bucket or container
|The name of the external S3 bucket or Azure container. The name you specify here must exactly match the bucket or container's name, or Cloud Storage Pool creation will fail. You cannot change this value after the Cloud Storage Pool is saved.
|===

. Based on your Provider type selection, enter the Service endpoint information.

//tabbed blocks start here

[role="tabbed-block"]
====

.Amazon S3/GCP
--

.. For the protocol, select either HTTPS or HTTP.
+
NOTE: Do not use HTTP connections for sensitive data.
+
.. Enter the hostname.
.. Select the URL style:
+
[cols="1a,3a" options="header"]
|===
| Option| Description

|Auto-detect
|Attempt to automatically detect which URL style to use, based on the information provided. For example, if you specify an IP address, StorageGRID will use a path-style URL. Select this option only if you don't know which specific style to use.

|Virtual hosted-style
|Use a virtual hosted-style URL to access the bucket. Virtual hosted-style URLs include the bucket name as part of the domain name. Example: `+https://bucket-name.s3.company.com/key-name+`

|Path-style
|Use a path-style URL to access the bucket. Path-style URLs include the bucket name at the end. Example: `+https://s3.company.com/bucket-name/key-name+`

*Note:* The path-style URL is being deprecated.
|===
+
.. Optionally, enter the port number.
--
//end Amazon S3, begin Azure

.Azure Blob Storage
--
.. Using one of the following formats, enter the URI for the service endpoint.

* `+https://host:port+`
 `+http://host:port+`
====
//end tabbed blocks

[start=4]
. Select *Continue*. Then select the authentication type and  enter the required information for the Cloud Storage Pool endpoint:
+
[cols="1a,1a,1a,3a" options="header"]
|===
| Provider type| Authentication type| Option|Information to enter

|Amazon S3/GCP
|Access key
|
|
* Access key ID
* Secret access key
|
.1+|Anonymous
|
|No information required

|
|CAP (C2S access portal)
|Must use for C2S S3 only
|
* Temporary credential URL
* Server CA certificate
* Client certificate
* Client private key
* Client private key passphrase (if the private key for the client certificate is encrypted)

|Anonymous
|Everyone has access to the Cloud Storage Pool bucket. No additional information is required.
|===
+
. Complete the Service endpoint, Authentication and Server Verification sections of the page, based on the selected provider type.
+
* xref:s3-authentication-details-for-cloud-storage-pool.adoc[S3: Specify authentication details for a Cloud Storage Pool]
* xref:c2s-s3-authentication-details-for-cloud-storage-pool.adoc[C2S S3: Specify authentication details for a Cloud Storage Pool]
* xref:azure-authentication-details-for-cloud-storage-pool.adoc[Azure: Specify authentication details for a Cloud Storage Pool]