---
permalink: ilm/guidelines-for-creating-storage-pools.html
sidebar: sidebar
keywords: storage pool guidelines
summary: 'Configure and use storage pools to protect against data loss by distributing data across multiple sites. Replicated copies and erasure-coded copies require different storage pool configurations.'
---
= Guidelines for creating storage pools
:icons: font
:imagesdir: ../media/

[.lead]
Configure and use storage pools to protect against data loss by distributing data across multiple sites. Replicated copies and erasure-coded copies require different storage pool configurations.

See link:using-multiple-storage-pools-for-cross-site-replication.html[Examples of enabling site-loss protection using replication and erasure coding].

== Guidelines for all storage pools

* Keep storage pool configurations as simple as possible. Do not create more storage pools than necessary.
* Create storage pools with as many nodes as possible. Each storage pool should contain two or more nodes. A storage pool with insufficient nodes can cause ILM backlogs if a node becomes unavailable.
* Avoid creating or using storage pools that overlap (contain one or more of the same nodes). If storage pools overlap, more than one copy of object data might be saved on the same node.
* StorageGRID includes a default storage pool, All Storage Nodes, that uses the default site, All Sites, and the storage grade, *includes all storage grades*. The All Storage Nodes storage pool is automatically updated whenever you add new data center sites.
+
NOTE: In general, do not use the All Storage Nodes storage pool or the All Sites site. These items are automatically updated to include any new sites you add in an expansion, which might not be the behavior you want. Before using the All Storage Nodes storage pool or the default site, carefully review the guidelines for creating storage pools used for replicated and erasure-coded copies.

== Guidelines for storage pools used for replicated copies

* For site-loss protection using link:what-replication-is.html[replication], create each storage pool so that it consists of only one site. Then, specify one or more site-specific storage pools in the link:create-ilm-rule-define-placements.html[placement instructions for each ILM rule].
+
Using a storage pool for each site ensures that replicated object copies are placed exactly where you expect (for example, one copy of every object at each site for site-loss protection).
* If you add a site in an expansion, create a new storage pool that contains only the new site. Then, link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule[update ILM rules] to control which objects are stored on the new site.
* If you are creating `_n_` copies, you must add `_n_` or more storage pools. For example, if a rule is configured to make three copies, you must specify three or more storage pools.
* If the number of copies is less than the number of storage pools, the system distributes the copies to balance disk usage among the pools.
* If the storage pools overlap (contain the same Storage Nodes), all copies of the object might be saved at only one site. You must ensure that the selected storage pools do not contain the same Storage Nodes.

== Guidelines for storage pools used for erasure-coded copies

* For site-loss protection using link:what-erasure-coding-is.html[erasure coding], create storage pools that consist of at least three sites. If a storage pool includes only two sites, you cannot use that storage pool for erasure coding. No erasure-coding schemes are available for a storage pool that has two sites.
* The number of Storage Nodes and sites contained in the storage pool determine which link:what-erasure-coding-schemes-are.html[erasure-coding schemes] are available.
* If possible, a storage pool should include more than the minimum number of Storage Nodes required for the erasure-coding scheme you select. For example, if you use a 6+3 erasure-coding scheme, you must have at least nine Storage Nodes. However, having at least one additional Storage Node per site is recommended.
* Distribute Storage Nodes across sites as evenly as possible. For example, to support a 6+3 erasure-coding scheme, configure a storage pool that includes at least three Storage Nodes at three sites.
* If you have high throughput requirements, using a storage pool that includes multiple sites is not recommended if the network latency between sites is greater than 100 ms. As latency increases, the rate at which StorageGRID can create, place, and retrieve object fragments decreases sharply due to the decrease in TCP network throughput.
+
The decrease in throughput affects the maximum achievable rates of object ingest and retrieval (when Balanced or Strict are selected as the ingest behavior) or could lead to ILM queue backlogs (when Dual commit is selected as the ingest behavior). See link:what-ilm-rule-is.html#ilm-rule-ingest-behavior[ILM rule ingest behavior].
+
NOTE: If your grid includes only one site, you are prevented from using the All Storage Nodes storage pool or the All Sites default site in an erasure coding profile. This behavior prevents the erasure coding profile from becoming invalid if a second site is added.
* You cannot use Archive Nodes for erasure-coded data.

== Guidelines for storage pools used for archived copies

* You cannot create a storage pool that includes both Storage Nodes and Archive Nodes. Archived copies require a storage pool that only includes Archive Nodes.
* When using a storage pool that includes Archive Nodes, you should also maintain at least one replicated or erasure-coded copy on a storage pool that includes Storage Nodes.
* If the global S3 Object Lock setting is enabled and you are creating a compliant ILM rule, you cannot use a storage pool that includes Archive Nodes. See the instructions for managing objects with S3 Object Lock.
* If an Archive Node's Target Type is Cloud Tiering - Simple Storage Service (S3), the Archive Node must be in its own storage pool. See link:../admin/index.html[Administer StorageGRID].