---
permalink: ilm/removing-cloud-storage-pool.html
sidebar: sidebar
keywords: remove cloud storage pool
summary: 'You can remove a Cloud Storage Pool if it not used in an ILM rule and it does not contain object data.'
---
= Remove a Cloud Storage Pool
:icons: font
:imagesdir: ../media/

[.lead]
You can remove a Cloud Storage Pool if it not used in an ILM rule and it does not contain object data.

.What you'll need
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:../admin/admin-group-permissions.html[required access permissions].


== If needed, use ILM to move object data

If the Cloud Storage Pool you want to remove contains object data, you must use ILM to move the data to a different location. For example, you can move the data to Storage Nodes on your grid or to a different Cloud Storage Pool.

.Steps

. Select *ILM* > *Storage pools* > *Cloud Storage Pools*.

. Look at the ILM usage column in the table to determine whether you can remove the Cloud Storage Pool.
+
You cannot remove a Cloud Storage Pool if it is being used in an ILM rule or in an erasure coding profile. 

. If the Cloud Storage Pool is being used, select *_cloud storage pool name_* > *ILM usage*.

. link:creating-cloud-storage-pool.html[Create a new Cloud Storage Pool] or determine which storage pool or pools you want to use for the existing objects.

. link:working-with-ilm-rules-and-ilm-policies.html[Clone each ILM rule] that currently places objects in the Cloud Storage Pool you want to remove.

. Edit each of the rules you cloned to use the new Cloud Storage Pool or a storage pool instead.
+
For Step 2 of the Create ILM rule wizard, select the new location from the *copies at* field.

. link:creating-proposed-ilm-policy.html[Create a new proposed ILM policy] and replace each of the old rules with a cloned rule.

. Activate the new policy.

. Wait for ILM to remove objects from the original Cloud Storage Pool and place them in the new location. 


== Delete Cloud Storage Pool

When the Cloud Storage Pool is empty and not used in any ILM rules, you can delete it.

.What you'll need

* You have removed any ILM rules that might have used the pool.

* You have confirmed that the S3 bucket or Azure container does not contain any objects.
+
An error occurs if you attempt to remove a Cloud Storage Pool if it contains objects. See link:troubleshooting-cloud-storage-pools.html[Troubleshoot Cloud Storage Pools].
+
NOTE: When you create a Cloud Storage Pool, StorageGRID writes a marker file to the bucket or container to identify it as a Cloud Storage Pool. Do not remove this file, which is named `x-ntap-sgws-cloud-pool-uuid`.

.Steps

. Select *ILM* > *Storage pools* > *Cloud Storage Pools*.
. If the ILM usage column indicates that Cloud Storage Pool is not being used, select the check box.
. Select *Actions* > *Remove*.
. Select *OK*.
