---
permalink: ilm/removing-cloud-storage-pool.html
sidebar: sidebar
keywords: remove cloud storage pool
summary: 'You can remove a Cloud Storage Pool that is not used in an ILM rule and that does not contain object data.'
---
= Remove a Cloud Storage Pool
:icons: font
:imagesdir: ../media/

[.lead]
You can remove a Cloud Storage Pool that is not used in an ILM rule and that does not contain object data.

.What you'll need
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the xref:../admin/admin-group-permissions.adoc[required access permissions].
* You have confirmed that the S3 bucket or Azure container does not contain any objects. An error occurs if you attempt to remove a Cloud Storage Pool if it contains objects. See xref:troubleshooting-cloud-storage-pools.adoc[Troubleshoot Cloud Storage Pools].
+
NOTE: When you create a Cloud Storage Pool, StorageGRID writes a marker file to the bucket or container to identify it as a Cloud Storage Pool. Do not remove this file, which is named `x-ntap-sgws-cloud-pool-uuid`.

* You have already removed any ILM rules that might have used the pool.

.Steps
. Select *ILM* > *Storage pools* > *Cloud Storage Pools*.

. Look at the ILM usage column in the table to determine whether you can remove the Cloud Storage Pool.
+
You cannot remove a Cloud Storage Pool if it is being used in an ILM rule or in an erasure coding profile. As required, select *_cloud storage pool name_* > *ILM usage* to determine where the storage pool is used.

. If the Cloud Storage Pool you want to remove is not being used, select the check box.
. Select *Remove*.
. Select *OK*.
