---
permalink: fabricpool/after-you-finish.html
sidebar: sidebar
keywords: fabricPool, dns, volume tiering policies, 
summary: 'After you have obtained the required StorageGRID information, you can go to ONTAP to add StorageGRID as a cloud tier, add the cloud tier as an aggregate, and set volume tiering policies.'
---
= After you finish
:icons: font
:imagesdir: ../media/

[.lead]
After you have obtained the required StorageGRID information, you can go to ONTAP to configure the DNS server, add StorageGRID as a cloud tier, add the cloud tier as an aggregate, and set volume tiering policies.

== Configure the DNS server for StorageGRID IP addresses
After configuring high availability groups and load balancer endpoints, you must ensure that the domain name system (DNS) for the ONTAP system includes a record to associate the StorageGRID server name (fully qualified domain name) to the IP address that FabricPool will use to make connections.

The IP address you enter in the DNS record depends on whether you are using an HA group of load-balancing nodes:

* If you have configured a HA group, FabricPool will connect to the virtual IP addresses of that HA group.
* If you are not using a HA group, FabricPool can connect to the StorageGRID Load Balancer service using the IP address of any Gateway Node or Admin Node.

You must also ensure that the DNS record references all required endpoint domain names, including any wildcard names.
