---
permalink: fabricpool/best-practices-for-load-balancing.html
sidebar: sidebar
keywords: fabricPool, load balancer, endpoint, load balancing, Layer 7, cloud tier, best practices
summary: 'Before attaching StorageGRID as a FabricPool cloud tier, learn about load balancer endpoints and review the best practices for using load balancers with FabricPool.'
---
= Best practices for load balancing
:icons: font
:imagesdir: ../media/

[.lead]
Before attaching StorageGRID as a FabricPool cloud tier, learn about load balancer endpoints and review the best practices for using load balancers with FabricPool.

== What is load balancing?

When data is tiered from FabricPool to a StorageGRID system, StorageGRID uses a load balancer to manage the ingest and retrieval workload. Load balancing maximizes speed and connection capacity by distributing the FabricPool workload across multiple Storage Nodes.

The StorageGRID Load Balancer service is installed on all Admin Nodes and all Gateway Nodes and provides Layer 7 load balancing. It performs Transport Layer Security (TLS) termination of client requests, inspects the requests, and establishes new secure connections to the Storage Nodes.

The Load Balancer service on each node operates independently when forwarding client traffic to the Storage Nodes. Through a weighting process, the Load Balancer service routes more requests to Storage Nodes with higher CPU availability.

Although the StorageGRID Load Balancer service is the recommended load balancing mechanism, you might want to integrate a third-party load balancer instead. For information, contact your NetApp account representative or refer to https://www.netapp.com/pdf.html?item=/media/17068-tr4626pdf.pdf[TR-4626: StorageGRID third-party and global load balancers^].


== Best practices for StorageGRID load balancing

As a general best practice, each site in your StorageGRID system should include two or more nodes with the Load Balancer service. For example, a site might include two Gateway Nodes or both an Admin Node and a Gateway Node. Make sure that there is adequate networking, hardware, or virtualization infrastructure for each load-balancing node, whether you are using SG100 or SG1000 services appliances, bare metal nodes, or virtual machine (VM) based nodes.

You must configure a StorageGRID load balancer endpoint to define the port that Gateway Nodes and Admin Nodes will use for incoming and outgoing FabricPool requests.

== Best practices for the load balancer security certificate

When you create a StorageGRID load balancer endpoint for FabricPool use, you should select *HTTPS* as the protocol. Using FabricPool without Transport Layer Security (TLS) encryption is supported but not recommended.

After you select *HTTPS* for the endpoint, you must provide the security certificate that will allow ONTAP to authenticate with StorageGRID. You can do one of the following:

* Recommended. Upload a certificate that is signed by either a publicly trusted or a private certificate authority (CA).
* Generate a self-signed certificate.
* Use a custom version of the global StorageGRID S3 and Swift certificate.

As a best practice, you should use a publicly trusted CA server certificate to secure the connection. In contrast to generated certificates, certificates signed by a CA can be rotated nondisruptively, which can help avoid expiration issues.

When requesting a CA certificate for use with the load balancer endpoint, ensure that the domain name on the certificate matches the server name you will enter in ONTAP for the cloud tier. If possible, use a wildcard (*) to allow for virtual hosted-style URLs. For example:

----
*.s3.storagegrid.company.com
----

When you add StorageGRID as a FabricPool cloud tier, you must install the same certificate to the ONTAP cluster, as well as the root and any subordinate certificate authority (CA) certificates.

To learn more about the server certificate for a load balancing endpoint:

* xref:../admin/configuring-load-balancer-endpoints.adoc[Configure load balancer endpoints]
* xref:../harden/hardening-guideline-for-server-certificates.adoc[Hardening guidelines for server certificates]

== What happens if a certificate expires?

IMPORTANT: If the certificate used to secure the connection between ONTAP and StorageGRID expires, FabricPool will temporarily stop working and ONTAP will temporarily lose access to data tiered to StorageGRID. 

To avoid certificate expiration issues, follow these best practices:

* Carefully monitor any alerts that warn of approaching certificate expiration dates, including the *Expiration of load balancer endpoint certificate* and *Expiration of global server certificate for S3 and Swift API* alerts.

* Always keep the StorageGRID and ONTAP versions of the certificate in sync. If you replace or renew the certificate used for a load balancer endpoint, you must replace or renew the equivalent certificate used by ONTAP for the cloud tier.

* Use a CA-signed certificate. If you use a certificate signed by a CA, you can use the Grid Management API to automate certificate rotation. This allows you to replace soon-to-expire certificates nondisruptively. 

* If you have generated a self-signed StorageGRID certificate and that certificate is about to expire, manually replace the certificate in both StorageGRID and in ONTAP before the existing certificate expires. If a self-signed certificate has already expired, turn off certificate validation in ONTAP to prevent access loss.
+
See https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_configure_a_new_StorageGRID_self-signed_server_certificate_on_an_existing_ONTAP_FabricPool_deployment[NetApp Knowledge Base: How to configure a new StorageGRID self-signed server certificate on an existing ONTAP FabricPool deployment^] for instructions.