---
permalink: fabricpool/best-practices-for-high-availability-groups.html
sidebar: sidebar
keywords: fabricPool, high availability group, HA group, active-active, active-backup, cloud tier, best practices
summary: 'Before attaching StorageGRID as a FabricPool cloud tier, learn about StorageGRID high availability (HA) groups and review the best practices for using HA groups with FabricPool.'
---
= Best practices for high availability (HA) groups
:icons: font
:imagesdir: ../media/

[.lead]

Before attaching StorageGRID as a FabricPool cloud tier, learn about StorageGRID high availability (HA) groups and review the best practices for using HA groups with FabricPool.

== What is an HA group?

A high availability (HA) group is a collection of interfaces from multiple StorageGRID Gateway Nodes, Admin Nodes, or both. An HA group helps to keep client data connections available. If the active interface in the HA group fails, a backup interface can manage the workload with little impact on FabricPool operations.

Each HA group provides highly available access to the shared services on the associated nodes. For example, an HA group that consists of interfaces only on Gateway Nodes or on both Admin Nodes and Gateway Nodes provides highly available access to the shared Load Balancer service.

To learn more about high availability groups, see link:../admin/managing-high-availability-groups.html[Manage high availability (HA) groups].

== Using HA groups

The best practices for creating a StorageGRID HA group for FabricPool depend on the workload.

* If you plan to use FabricPool with primary workload data, you must create an HA group that includes at least two load-balancing nodes to prevent data retrieval interruption.
* If you plan to use the FabricPool snapshot-only volume tiering policy or non-primary local performance tiers (for example, disaster recovery locations or NetApp SnapMirror® destinations), you can configure an HA group with only one node.

These instructions describe setting up an HA group for Active-Backup HA (one node is active and one node is backup). However, you might prefer to use DNS Round Robin or Active-Active HA. To learn the benefits of these other HA configurations, see link:../admin/configuration-options-for-ha-groups.html[Configuration options for HA groups].
