---
permalink: fabricpool/best-practices-for-load-balancing.html
sidebar: sidebar
keywords: fabricPool, load balancer, endpoint, load balancing, Layer 7, cloud tier, best practices
summary: 'Before attaching StorageGRID as a FabricPool cloud tier, learn about load balancer endpoints and review the best practices for using load balancers with FabricPool.'
---
= Best practices for load balancing
:icons: font
:imagesdir: ../media/

[.lead]
Before attaching StorageGRID as a FabricPool cloud tier, learn about load balancer endpoints and review the best practices for using load balancers with FabricPool.

== What is load balancing?

When data is tiered from FabricPool to a StorageGRID system, StorageGRID uses a load balancer to manage the ingest and retrieval workload. Load balancing maximizes speed and connection capacity by distributing the FabricPool workload across multiple Storage Nodes.

The StorageGRID Load Balancer service is installed on all Admin Nodes and all Gateway Nodes and provides Layer 7 load balancing. It performs Transport Layer Security (TLS) termination of client requests, inspects the requests, and establishes new secure connections to the Storage Nodes.

The Load Balancer service on each node operates independently when forwarding client traffic to the Storage Nodes. Through a weighting process, the Load Balancer service routes more requests to Storage Nodes with higher CPU availability.

Although the StorageGRID Load Balancer service is the recommended load balancing mechanism, you might want to integrate a third-party load balancer instead. For information, contact your NetApp account representative or refer to https://www.netapp.com/pdf.html?item=/media/17068-tr4626pdf.pdf[TR-4626: StorageGRID third-party and global load balancers^].


== Best practices for StorageGRID load balancing

As a general best practice, each site in your StorageGRID system should include two or more nodes with the Load Balancer service. For example, a site might include two Gateway Nodes or both an Admin Node and a Gateway Node. Make sure that there is adequate networking, hardware, or virtualization infrastructure for each load-balancing node, whether you are using SG100 or SG1000 services appliances, bare metal nodes, or virtual machine (VM) based nodes.

You must configure a StorageGRID load balancer endpoint to define the port that Gateway Nodes and Admin Nodes will use for incoming and outgoing FabricPool requests.

