---
permalink: fabricpool/best-practices-ilm.html
sidebar: sidebar
keywords: FabricPool, best practices, ILM, information lifecycle management, ILM rule, ILM policy, erasure-coding, replication
summary: 'If you are using FabricPool to tier data to StorageGRID, you must understand the requirements for using StorageGRID information lifecycle management (ILM) with FabricPool data. You must ensure the ILM rules that apply to FabricPool data are not disruptive.'
---
= Best practices for using ILM with FabricPool data
:icons: font
:imagesdir: ../media/

[.lead]
If you are using FabricPool to tier data to StorageGRID, you must understand the requirements for using StorageGRID information lifecycle management (ILM) with FabricPool data. You must ensure the ILM rules that apply to FabricPool data are not disruptive.

IMPORTANT: FabricPool has no knowledge of StorageGRID ILM rules or policies. Data loss can occur if the StorageGRID ILM policy is misconfigured. For detailed information, see xref:../ilm/what-ilm-rule-is.adoc[Create an ILM rule: Overview] and xref:../ilm/creating-ilm-policy.adoc[Create an ILM policy: Overview].

== What is an ILM policy?
An information lifecycle management policy is an ordered set of ILM rules that determines how the StorageGRID system manages object data over time.

The active ILM policy for your StorageGRID system controls the placement, duration, and ingest behavior of all objects.

When clients save objects to StorageGRID, the objects are evaluated against the ordered set of ILM rules in the active policy, as follows:

. If the filters for the first rule in the policy match an object's metadata, the object is ingested according to that rule's ingest behavior and stored according to that rule's placement instructions.

. If the filters for the first rule do not match the object's metadata, the object is evaluated against each subsequent rule in the policy until a match is made.
. If no rules match an object, the ingest behavior and placement instructions for the default rule in the policy are applied. The default rule is the last rule in a policy. The default rule must apply to all tenants, all buckets, and all object versions and cannot use any advanced filters.

== What are ILM rules?

ILM rules define:

* Which objects should be stored. You use filters to identify which objects a rule applies to. For example, a rule can apply only to objects associated with certain tenant accounts, specific S3 buckets, or specific metadata values.
* The storage type and location. You select one or more storage pools for a rule to control which nodes are used to store the object. 
* The type and number of  object copies made. Copies can be replicated or erasure coded.
* The changes over time to an object's storage location and type of copies. 
* How object data is protected as objects are ingested into the grid. A rule's ingest behavior controls whether object copies are immediately placed according to the instructions in the rule, or if interim copies are made and the placement instructions are applied later.

Note that object metadata is not managed by ILM rules. Instead, object metadata is stored in a Cassandra database in what is known as a metadata store. Three copies of object metadata are automatically maintained at each site to protect the data from loss. The copies are evenly distributed across all Storage Nodes.

== Guidelines for using ILM with FabricPool
When you use the FabricPool setup wizard, the wizard automatically creates a new ILM rule for each S3 bucket you create, adds that rule to a proposed policy, and prompts you to activate the new policy as part of completing the wizard. The automatically created rule follows the recommended best practices: it uses 2+1 erasure coding at a single site.

If you are configuring StorageGRID manually instead of using the FabricPool setup wizard, review these guidelines to ensure that your ILM rules and ILM policy are suitable for FabricPool data and your business requirements. You might need to create new rules and update your active ILM policy to meet these guidelines.

* You can use any combination of replication and erasure-coding rules to protect cloud tier data.
+
The recommended best practice is to use 2+1 erasure coding within a site for cost-efficient data protection. Erasure coding uses more CPU, but offers significantly less storage capacity, than replication. The 4+1 and 6+1 schemes use less capacity than the 2+1 scheme. However, the 4+1 and 6+1 schemes are less flexible if you need to add Storage Nodes during grid expansion. For details, see xref:../expand/adding-storage-capacity-for-erasure-coded-objects.adoc[Add storage capacity for erasure-coded objects].

* Each rule applied to FabricPool data must either use erasure coding or it must create at least two replicated copies.
+
IMPORTANT: An ILM rule that creates only one replicated copy for any time period puts data at risk of permanent loss. If only one replicated copy of an object exists, that object is lost if a Storage Node fails or has a significant error. You also temporarily lose access to the object during maintenance procedures such as upgrades.

* Do not use an ILM rule that will expire or delete FabricPool cloud tier data. Set the retention period in each ILM rule to "`forever`" to ensure that FabricPool objects are not deleted by StorageGRID ILM.
* Do not create rules that will move FabricPool cloud tier data out of the bucket to another location. You cannot use ILM rules to archive FabricPool data to tape using an Archive Node or use a Cloud Storage Pool to move FabricPool data to another object store.
+
NOTE: Using Cloud Storage Pools with FabricPool is not supported because of the added latency to retrieve an object from the Cloud Storage Pool target.

* Starting with ONTAP 9.8, you can optionally create object tags to help classify and sort tiered data for easier management. For example, you can set tags only on FabricPool volumes attached to StorageGRID. Then, when you create ILM rules in StorageGRID, you can use the Object Tag advanced filter to select and place this data.
