---
permalink: fabricpool/configure-dns-server.html
sidebar: sidebar
keywords: dns, vip, virtual ip, fqdn, server name 
summary: 'After configuring high availability groups and load balancer endpoints, you must ensure that the domain name system (DNS) includes a record to associate the StorageGRID server name (fully qualified domain name) to the IP address that FabricPool will use to make connections.'
---
= Configure the DNS server
:icons: font
:imagesdir: ../media/

[.lead]
After configuring high availability groups and load balancer endpoints, you must ensure that the domain name system (DNS) includes a record to associate the StorageGRID server name (fully qualified domain name) to each StorageGRID IP address you will use.

The IP addresses you enter in the DNS depend on whether you are using an HA group of load-balancing nodes:

* If you have configured a HA group, ONTAP will connect to the virtual IP addresses of that HA group.

* If you are not using a HA group, ONTAP can connect to the StorageGRID Load Balancer service using the IP address of any Gateway Node or Admin Node.

* If the server name resolves to more than one IP address, ONTAP establishes client connections with all IP addresses (up to a maximum of 16 IP addresses). The IP addresses are picked up in a round-robin method when connections are established.

You must also ensure that the DNS record references all required endpoint domain names, including any wildcard names.

 