---
permalink: fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html
sidebar: sidebar
keywords: fabricPool, best practices, audit log, encryption, compressions, tiering, AFF, consistency
summary: 'When configuring a StorageGRID system for use with FabricPool, you should avoid setting global options that might affect how your data is saved.'
---
= Other best practices for StorageGRID and FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
When configuring a StorageGRID system for use with FabricPool, you should avoid setting global options that might affect how your data is saved.

== Audit message and log destinations
FabricPool workloads often have a high rate of read operations, which can generate a high volume of audit messages. 

* If you do not require a record of client read operation for FabricPool or for any other S3 client application, optionally go to xref:../monitor/configure-audit-messages.adoc[Configure audit messages and log destinations]. Change the *Client Reads* setting to *Error*.

* If you have a large grid, use many different S3 clients, or you don't want to lose audit data, configure an external syslog server and save audit information remotely. Using an external server minimizes the performance impact and allows you to maintain a full history of audit data.  See xref:../monitor/considerations-for-external-syslog-server.adoc[Considerations for external syslog server] for details.
 

== Object encryption

When configuring StorageGRID, you can optionally enable the global *Stored Object Encryption* setting if data encryption is required for other StorageGRID clients (*CONFIGURATION* > *System* > *Grid options*). The data that is tiered from FabricPool to StorageGRID is already encrypted, so enabling the StorageGRID setting is not required. Client-side encryption keys are owned by ONTAP.

== Object compression

When configuring StorageGRID, do not enable the global *Compress Stored Objects* setting (*CONFIGURATION* > *System* > *Grid options*). The data that is tiered from FabricPool to StorageGRID is already compressed. Enabling *Compress Stored Objects* will not further reduce an object's size.

== Consistency level

For FabricPool buckets, the recommended bucket consistency level is "`read-after-new-write.`" The "`available`" consistency level is not recommended. For details, see xref:../tenant/changing-consistency-level.adoc[Change a bucket's consistency level].

== FabricPool tiering

If the StorageGRID node uses storage assigned from a NetApp AFF system, confirm that the volume does not have a FabricPool tiering policy enabled. For example, if a StorageGRID node is running on a VMware host, ensure the volume backing the datastore for the StorageGRID node does not have a FabricPool tiering policy enabled. Disabling FabricPool tiering for volumes used with StorageGRID nodes simplifies troubleshooting and storage operations.

IMPORTANT: Never use FabricPool to tier any data related to StorageGRID back to StorageGRID itself. Tiering StorageGRID data back to StorageGRID increases troubleshooting and operational complexity.
