---
permalink: fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html
sidebar: sidebar
keywords: fabricPool, best practices, audit log, encryption, compressions, tiering, AFF, consistency
summary: 'When configuring a StorageGRID system for use with FabricPool, you might need to change other StorageGRID options. Before changing a global setting, consider how the change will affect other S3 applications.'
---
= Other best practices for StorageGRID and FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
When configuring a StorageGRID system for use with FabricPool, you might need to change other StorageGRID options. Before changing a global setting, consider how the change will affect other S3 applications.

== Audit message and log destinations
FabricPool workloads often have a high rate of read operations, which can generate a high volume of audit messages. 

* If you do not require a record of client read operations for FabricPool or any other S3 application, optionally go to *CONFIGURATION* > *Monitoring* > *Audit and syslog server*. Change the *Client Reads* setting to *Error*. See xref:../monitor/configure-audit-messages.adoc[Configure audit messages and log destinations] for details.

* If you have a large grid, use multiple types of S3 applications, or want to retain all audit data, configure an external syslog server and save audit information remotely. Using an external server minimizes the performance impact of audit message logging without reducing the completeness of of audit data. See xref:../monitor/considerations-for-external-syslog-server.adoc[Considerations for external syslog server] for details.
 

== Object encryption

When configuring StorageGRID, you can optionally enable the global *Stored Object Encryption* setting if data encryption is required for other StorageGRID clients (*CONFIGURATION* > *System* > *Grid options*). The data that is tiered from FabricPool to StorageGRID is already encrypted, so enabling the StorageGRID setting is not required. Client-side encryption keys are owned by ONTAP.

== Object compression

When configuring StorageGRID, do not enable the global *Compress Stored Objects* setting (*CONFIGURATION* > *System* > *Grid options*). The data that is tiered from FabricPool to StorageGRID is already compressed. Enabling *Compress Stored Objects* will not further reduce an object's size.

== Bucket consistency level
For FabricPool buckets, the recommended bucket consistency level is *Read-after-new-write*, which is the default setting for a new bucket. Do not edit FabricPool buckets to use *Available* or any other consistency level.

== FabricPool tiering

If a StorageGRID node uses storage assigned from a NetApp ONTAP system, confirm that the volume does not have a FabricPool tiering policy enabled. For example, if a StorageGRID node is running on a VMware host, ensure the volume backing the datastore for the StorageGRID node does not have a FabricPool tiering policy enabled. Disabling FabricPool tiering for volumes used with StorageGRID nodes simplifies troubleshooting and storage operations.

IMPORTANT: Never use FabricPool to tier any data related to StorageGRID back to StorageGRID itself. Tiering StorageGRID data back to StorageGRID increases troubleshooting and operational complexity.
