---
permalink: fabricpool/use-fabricpool-setup-wizard.html
sidebar: sidebar
keywords: fabricPool, FabricPool setup wizard, ontap system manager
summary: 'You can use the FabricPool setup wizard to configure StorageGRID as the object storage system for a FabricPool cloud tier. After you complete the setup wizard, you can enter the required details into ONTAP System Manager.'
---
= FabricPool setup wizard: Considerations and requirements
:icons: font
:imagesdir: ../media/

[.lead]

You can use the FabricPool setup wizard to configure StorageGRID as the object storage system for a FabricPool cloud tier. After you complete the setup wizard, you can enter the required details into ONTAP System Manager.

== When to use the FabricPool setup wizard

The FabricPool setup wizard guides you through each step of configuring StorageGRID for use with FabricPool and automatically configures certain entities for you, such as the ILM and traffic classification policies. As part of completing the wizard, you download a file that you can use to enter values into ONTAP System Manager. Use the wizard to configure your system more quickly and to make sure your settings conform to StorageGRID and FabricPool best practices. 

Assuming you have Root access permission, you can complete the FabricPool setup wizard when you start using the StorageGRID Grid Manager, or you can access and complete the wizard at any later time. Depending on your requirements, you can also configure some or all of the required items manually and then use the wizard to assemble the values that ONTAP needs into a single file.

Use the wizard unless you have special requirements or your implementation needs significant customization. For example, you cannot use the FabricPool setup wizard if S3 Object Lock is enabled for your grid. Instead, you must configure each item manually in StorageGRID. Start by xref:creating-ha-group-for-fabricpool.adoc[creating an HA group].

NOTE: If you want to configure StorageGRID for use with any other S3 client application, go to xref:../admin/use-s3-setup-wizard.adoc[Use S3 setup wizard].

== How many StorageGRID tenants and buckets do I need?

These instructions describe how to connect StorageGRID as a single cloud tier to a single ONTAP local tier. However, you might want to connect the same StorageGRID system to multiple local tiers. Attaching a single cloud tier to multiple local tiers in a cluster is the general best practice. 

NetApp does not recommend attaching a single cloud tier to local tiers in multiple clusters.

Here are the requirements for attaching StorageGRID to multiple local tiers: 

* *If you use more than one local tier, you must use a different S3 bucket for each tier.* You can reuse the high availability (HA) group, load balancer endpoint, and tenant. Follow these general steps:

.. From StorageGRID Grid Manager, complete the FabricPool setup wizard for the first cloud tier.
.. From ONTAP System Manager, add a cloud tier and use the file you downloaded from StorageGRID to provide the required values.  
.. From StorageGRID Tenant Manager, sign in to the tenant that was created by the wizard, and create a second bucket.
.. Complete the FabricPool wizard again. Select the existing HA group, load balancer endpoint, and tenant. Then, select the new bucket you created manually. Create a new ILM rule for the new bucket and activate an ILM policy to include that rule.
.. From ONTAP, add a second cloud tier but provide the new bucket name.

* *Optionally, you can configure a separate tenant and S3 access keys for each cloud tier.* Using separate tenants and keys provides additional isolation between the tiers, but is somewhat more complex to configure and manage. Follow these general steps:

.. From StorageGRID Grid Manager, complete the FabricPool setup wizard for the first cloud tier.
.. From ONTAP System Manager, add a cloud tier and use the file you downloaded from StorageGRID to provide the required values. 
.. Complete the FabricPool wizard again. Select the existing HA group and load balancer endpoint. Create a new tenant and bucket. Create a new ILM rule for the new bucket and activate an ILM policy to include that rule. 
.. From ONTAP, add a second cloud tier but provide the new access key, secret key, and bucket name.

* *If you are using FabricPool with NetApp MetroCluster™, you must use a separate tenant, user, and S3 access keys for each ONTAP cluster.* See https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf[TR-4598: FabricPool Best Practices in ONTAP^] for the best practices for using StorageGRID with MetroCluster and FabricPool Mirror.

== Before using the wizard

Confirm you have completed these prerequisite steps.

=== Review best practices

* You have a general understanding of the xref:information-needed-to-attach-storagegrid-as-cloud-tier.adoc[information needed to attach StorageGRID as a cloud tier].

* You have reviewed the best practices for:

** xref:best-practices-for-high-availability-groups.adoc[High availability (HA) groups]
** xref:best-practices-for-load-balancing.adoc[Load balancing and the load balancer certificate]
** xref:best-practices-ilm.adoc[ILM rules and policy]

=== Obtain IP addresses and set up VLAN interfaces

If you will configure an HA group, you know which nodes ONTAP will connect to and which StorageGRID network will be used. You also know which values to enter for the subnet CIDR, gateway IP address, and virtual IP (VIP) addresses. 

If you plan to use a virtual LAN to segregate FabricPool traffic, you have already configured the VLAN interface. See xref:../admin/configure-vlan-interfaces.adoc[Configure VLAN interfaces].

=== Configure identity federation and SSO

If you plan to use identity federation or single sign-on (SSO) for your StorageGRID system, you have enabled these features. You also know which federated group should have root access for the tenant account that ONTAP will use. See xref:../admin/using-identity-federation.adoc[Use identity federation] and xref:../admin/configuring-sso.adoc[Configure single sign-on].

=== Obtain and configure domain names

* You know which fully qualified domain name (FQDN) to use for StorageGRID. Domain name server (DNS) entries will map this FQDN to the virtual IP (VIP) addresses of the HA group that you create using the wizard. See xref:../fabricpool/configure-dns-server.adoc[Configure DNS server].

* If you plan to use S3 virtual hosted-style requests, you have xref:../admin/configuring-s3-api-endpoint-domain-names.adoc[configured S3 API endpoint domain names]. ONTAP uses path-style URLs by default, but using virtual hosted-style requests is recommended.

=== Obtain custom TLS certificates
If you plan to use the StorageGRID load balancer, you have reviewed the best practices for the xref:best-practices-for-load-balancing.adoc[load balancer endpoint certificate] and you know whether you will upload or generate this certificate.

* If you plan to upload a CA-signed security certificate (recommended), you have the following files: 

** The custom server certificate file.
** The custom server certificate private key file.
** Optionally, a CA bundle of the certificates from each intermediate issuing certificate authority. 
+
The certificate must include the FQDN that ONTAP will use for StorageGRID. 

* If you plan to generate a self-signed certificate, you know which values to use.

* If you plan to use the global StorageGRID S3 and Swift API certificate, you have already updated or generated a custom version. See xref:../admin/configuring-custom-server-certificate-for-storage-node-or-clb.adoc[Configure S3 and Swift API certificates]. 

If you plan to use an external (third-party) load balancer endpoint, you have the fully qualified domain name (FQDN), port, and certificate for that load balancer.

=== Confirm ILM storage pool configuration
If you upgraded to StorageGRID 11.7 from a previous StorageGRID version, you have configured the storage pool you will use. In general, you should create a storage pool for each StorageGRID site you will use to store ONTAP data. 

NOTE: This prerequisite does not apply to new StorageGRID 11.7 installations. When you install StorageGRID 11.7 on a new grid, storage pools are automatically created for each site.






