---
permalink: fabricpool/use-fabricpool-setup-wizard.html
sidebar: sidebar
keywords: fabricPool, FabricPool and S3 setup wizard, ontap system manager
summary: 'You can use the FabricPool and S3 setup wizard to configure StorageGRID as the object storage system for a FabricPool cloud tier. After you complete the setup wizard, you can upload or enter the required details into ONTAP System Manager.'
---
= FabricPool setup wizard: Overview
:icons: font
:imagesdir: ../media/

[.lead]

You can use the FabricPool and S3 setup wizard to configure StorageGRID as the object storage system for a FabricPool cloud tier. After you complete the setup wizard, you can upload or enter the required details into ONTAP System Manager.

== When to use the FabricPool and S3 setup wizard

The FabricPool and S3 setup wizard guides you through each step of configuring StorageGRID for use with FabricPool and automatically configures certain entities for you, such as the ILM and traffic classification policies. As part of completing the wizard, you download a file that you can use to enter values into ONTAP System Manager. Use the wizard to configure your system more quickly and to make sure your settings conform to StorageGRID and FabricPool best practices. 

NOTE: If you are using ONTAP System Manager version 9.12.1 or later, you can upload the StorageGRID settings directly to the Add Cloud Tier page. If you have an earlier version of ONTAP System Manager or if you are using the ONTAP CLI, you can enter the same values manually. 

Assuming you have Root access permission, you can complete the FabricPool and S3 setup wizard when you start using the StorageGRID Grid Manager, or you can access and complete the wizard at any later time. Depending on your requirements, you can also configure some or all of the required items manually and then use the wizard to assemble the values that ONTAP needs into a single file.

Use the wizard unless you know you have special requirements or your implementation will require significant customization. For example, you cannot use the FabricPool and S3 setup wizard if S3 Object Lock is enabled for your grid. Instead, you must configure each item manually in StorageGRID. Start by xref:creating-ha-group-for-fabricpool.adoc[creating an HA group].

== How to create connections for more than one cluster

If you plan to connect the same StorageGRID system to multiple ONTAP systems, use the FabricPool and S3 setup wizard to create an HA group, load balancer endpoint, tenant, and bucket for the first cluster.

Then, as required, complete the wizard for each additional cluster. You can select same HA group, and load balancer endpoint, but you must create or select a different tenant and bucket.

== Before using the wizard

Confirm each of the following items before using the wizard:

* You have a general understanding of the xref:information-needed-to-attach-storagegrid-as-cloud-tier.adoc[information needed to attach StorageGRID as a cloud tier].
* You have reviewed the best practices for:

** xref:best-practices-for-high-availability-groups.adoc[High availability groups]
** xref:best-practices-for-load-balancing.adoc[Load balancing]
** xref:best-practices-ilm.adoc[ILM rules and policy]

* If you plan to use a virtual LAN to segregate FabricPool traffic, you have configured the VLAN interface. See xref:../admin/configure-vlan-interfaces.adoc[Configure VLAN interfaces].

* If you plan to use identity federation or single sign-on (SSO) for your StorageGRID system, you have enabled these features and you know which federated group ONTAP should use. See xref:../admin/using-identity-federation.adoc[Use identity federation] and xref:../admin/configuring-sso.adoc[Configure single sign-on].

* You know which fully qualified domain name (FQDN) to use for StorageGRID. Domain name server (DNS) entries will map this FQDN to the virtual IP (VIP) addresses of the high availability (HA) group that you create using the wizard. See xref:../fabricpool/configure-dns-server.adoc[Configure DNS server].

* If you plan to use S3 virtual hosted-style requests (recommended), you have xref:../admin/configuring-s3-api-endpoint-domain-names.adoc[configured S3 API endpoint domain names]. ONTAP uses path-style URLs by default, but you can configure it to use virtual hosted-style requests.

* If you plan to upload a security certificate for the StorageGRID load balancer, you have the following files: 

** The custom server certificate file.
** The custom server certificate private key file.
** Optionally, a CA bundle of the certificates from each intermediate issuing certificate authority. 
+
The certificate must include the FQDN that ONTAP will use for StorageGRID. 

* If you plan to use an external (third-party) load balancer endpoint, you have the fully qualified domain name (FQDN), port, and certificate for that load balancer.

* If your StorageGRID system include multiple sites, you know which site will be used to store ONTAP data.

* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].

* You have the Root access permission.

